// File: src/common/entity/alchemy/PotionBrewing.hpp
//
// MC 26.3 brewing. In 26.3 the recipes are data (RecipeType.BREWING,
// world/item/crafting/BrewingRecipe.java) generated by VanillaBrewingProvider
// through BrewingProvider / BrewingRecipeBuilder:
//
//   brewingMix(container, inPotion, reagent, outPotion) for every container
//     (lingering, potion, splash) — input PotionIngredient(container,
//     PotionsPredicate.ofPotion(inPotion)), reagent the item, output the
//     container carrying PotionContents(outPotion);
//   brewingContainerTransform(container, potion, reagent, outContainer) for
//     potion + gunpowder → splash and splash + dragon's breath → lingering,
//     once for every potion any mix mentions.
//
// The engine has no brewing recipe type in its data pipeline, so this table
// is that provider run once in code — the same rows, the same order. The
// lookups mirror what BrewingStandBlockEntity / BrewingStandMenu ask the
// RecipeManager:
//   FindBrewingResult    quickCheck.getRecipeFor(BrewingInput(input, reagent))
//   IsBrewingReagent     RecipePropertySet.BREWING_REAGENTS
//   IsBrewingPotionInput PotionIngredient.isPotionInput (BREWING_INPUTS or
//                        #brewing_potion_inputs)
//   brewing fuel         DataComponents.BREWING_FUEL — only blaze powder
//                        (Items.java: brewingFuel(BREWING_DEFAULT_USES) = 20
//                        uses at the default speed multiplier 1.0)
#pragma once

#include <optional>

namespace Game {

    struct ItemStack;

    // The assembled output for `input` brewed with `reagent`, or nullopt when
    // no recipe matches.
    std::optional<ItemStack> FindBrewingResult(const ItemStack& input, const ItemStack& reagent);

    bool IsBrewingReagent(const ItemStack& stack);
    bool IsBrewingPotionInput(const ItemStack& stack);

    // BREWING_FUEL: uses per fuel item (0 = not a fuel) and the speed
    // multiplier it brews at.
    int   GetBrewingFuelUses(const ItemStack& stack);
    float GetBrewingFuelSpeedMultiplier(const ItemStack& stack);

} // namespace Game
