// File: src/common/world/spawn/GeneratedMobSpawns.hpp
// AUTO-GENERATED by tools/gen_mob_spawns.py — DO NOT EDIT BY HAND.
//
// Per-biome spawn weights, from data/minecraft/worldgen/biome/*.json.
// Regenerate after any Minecraft version bump; see CLAUDE.md.
#pragma once

#include "common/entity/EntityType.hpp"
#include "common/entity/MobCategory.hpp"

#include <cstdint>
#include <string_view>

namespace Game {

    struct MobSpawnEntry {
        MobCategory  category;
        EntityTypeId type;
        int          weight;
        int          minCount;
        int          maxCount;
    };

    struct BiomeSpawnList {
        std::string_view     biome;
        const MobSpawnEntry* entries;
        int                  count;
    };

    // Sorted by biome slug so lookup can binary-search.
    extern const BiomeSpawnList kBiomeSpawnLists[];
    extern const int            kBiomeSpawnListCount;

    // Null when the biome has no spawns for any implemented mob.
    const BiomeSpawnList* FindBiomeSpawnList(std::string_view biomeSlug);

} // namespace Game
