// File: src/common/world/spawn/GeneratedSpawnTags.cpp
// AUTO-GENERATED by tools/gen_spawn_tags.py — DO NOT EDIT BY HAND.
#include "common/world/spawn/GeneratedSpawnTags.hpp"

#include <algorithm>
#include <iterator>

namespace Game::SpawnTags {

    namespace {
        bool Contains(const BlockID* first, const BlockID* last, BlockID block) {
            return std::binary_search(first, last, block);
        }
        bool Contains(const std::string_view* first, const std::string_view* last,
                      std::string_view slug) {
            return std::binary_search(first, last, slug);
        }
    } // namespace

    static const BlockID k_AnimalsSpawnableOn[] = {
        BlockID::Grass,
    };
    bool AnimalsSpawnableOn(BlockID block) {
        return Contains(std::begin(k_AnimalsSpawnableOn), std::end(k_AnimalsSpawnableOn), block);
    }

    static const BlockID k_ArmadilloSpawnableOn[] = {
        BlockID::BrownTerracotta,
        BlockID::CoarseDirt,
        BlockID::Grass,
        BlockID::LightGrayTerracotta,
        BlockID::OrangeTerracotta,
        BlockID::RedSand,
        BlockID::RedTerracotta,
        BlockID::Terracotta,
        BlockID::WhiteTerracotta,
        BlockID::YellowTerracotta,
    };
    bool ArmadilloSpawnableOn(BlockID block) {
        return Contains(std::begin(k_ArmadilloSpawnableOn), std::end(k_ArmadilloSpawnableOn), block);
    }

    static const BlockID k_AxolotlsSpawnableOn[] = {
        BlockID::Clay,
    };
    bool AxolotlsSpawnableOn(BlockID block) {
        return Contains(std::begin(k_AxolotlsSpawnableOn), std::end(k_AxolotlsSpawnableOn), block);
    }

    static const BlockID k_BatsSpawnableOn[] = {
        BlockID::Andesite,
        BlockID::Deepslate,
        BlockID::Diorite,
        BlockID::Granite,
        BlockID::Stone,
        BlockID::Tuff,
    };
    bool BatsSpawnableOn(BlockID block) {
        return Contains(std::begin(k_BatsSpawnableOn), std::end(k_BatsSpawnableOn), block);
    }

    static const BlockID k_CamelsSpawnableOn[] = {
        BlockID::RedSand,
        BlockID::Sand,
        BlockID::SuspiciousSand,
    };
    bool CamelsSpawnableOn(BlockID block) {
        return Contains(std::begin(k_CamelsSpawnableOn), std::end(k_CamelsSpawnableOn), block);
    }

    static const BlockID k_FoxesSpawnableOn[] = {
        BlockID::CoarseDirt,
        BlockID::Grass,
        BlockID::Podzol,
        BlockID::SnowLayer,
        BlockID::Snow,
    };
    bool FoxesSpawnableOn(BlockID block) {
        return Contains(std::begin(k_FoxesSpawnableOn), std::end(k_FoxesSpawnableOn), block);
    }

    static const BlockID k_FrogsSpawnableOn[] = {
        BlockID::Grass,
        BlockID::MangroveRoots,
        BlockID::Mud,
        BlockID::MuddyMangroveRoots,
    };
    bool FrogsSpawnableOn(BlockID block) {
        return Contains(std::begin(k_FrogsSpawnableOn), std::end(k_FrogsSpawnableOn), block);
    }

    static const BlockID k_GoatsSpawnableOn[] = {
        BlockID::Grass,
        BlockID::Gravel,
        BlockID::PackedIce,
        BlockID::SnowLayer,
        BlockID::Snow,
        BlockID::Stone,
    };
    bool GoatsSpawnableOn(BlockID block) {
        return Contains(std::begin(k_GoatsSpawnableOn), std::end(k_GoatsSpawnableOn), block);
    }

    static const BlockID k_MooshroomsSpawnableOn[] = {
        BlockID::Mycelium,
    };
    bool MooshroomsSpawnableOn(BlockID block) {
        return Contains(std::begin(k_MooshroomsSpawnableOn), std::end(k_MooshroomsSpawnableOn), block);
    }

    static const BlockID k_ParrotsSpawnableOn[] = {
        BlockID::Air,
        BlockID::AcaciaLeaves,
        BlockID::AcaciaLog,
        BlockID::AcaciaWood,
        BlockID::AzaleaLeaves,
        BlockID::BirchLeaves,
        BlockID::BirchLog,
        BlockID::BirchWood,
        BlockID::CherryLeaves,
        BlockID::CherryLog,
        BlockID::CherryWood,
        BlockID::CrimsonHyphae,
        BlockID::CrimsonStem,
        BlockID::DarkOakLeaves,
        BlockID::DarkOakLog,
        BlockID::DarkOakWood,
        BlockID::FloweringAzaleaLeaves,
        BlockID::Grass,
        BlockID::JungleLeaves,
        BlockID::JungleLog,
        BlockID::JungleWood,
        BlockID::MangroveLeaves,
        BlockID::MangroveLog,
        BlockID::MangroveWood,
        BlockID::OakLeaves,
        BlockID::OakLog,
        BlockID::OakWood,
        BlockID::PaleOakLeaves,
        BlockID::PaleOakLog,
        BlockID::PaleOakWood,
        BlockID::SpruceLeaves,
        BlockID::SpruceLog,
        BlockID::SpruceWood,
        BlockID::StrippedAcaciaLog,
        BlockID::StrippedAcaciaWood,
        BlockID::StrippedBirchLog,
        BlockID::StrippedBirchWood,
        BlockID::StrippedCherryLog,
        BlockID::StrippedCherryWood,
        BlockID::StrippedCrimsonHyphae,
        BlockID::StrippedCrimsonStem,
        BlockID::StrippedDarkOakLog,
        BlockID::StrippedDarkOakWood,
        BlockID::StrippedJungleLog,
        BlockID::StrippedJungleWood,
        BlockID::StrippedMangroveLog,
        BlockID::StrippedMangroveWood,
        BlockID::StrippedOakLog,
        BlockID::StrippedOakWood,
        BlockID::StrippedPaleOakLog,
        BlockID::StrippedPaleOakWood,
        BlockID::StrippedSpruceLog,
        BlockID::StrippedSpruceWood,
        BlockID::StrippedWarpedHyphae,
        BlockID::StrippedWarpedStem,
        BlockID::WarpedHyphae,
        BlockID::WarpedStem,
    };
    bool ParrotsSpawnableOn(BlockID block) {
        return Contains(std::begin(k_ParrotsSpawnableOn), std::end(k_ParrotsSpawnableOn), block);
    }

    static const BlockID k_PolarBearsSpawnableOnAlternate[] = {
        BlockID::Ice,
    };
    bool PolarBearsSpawnableOnAlternate(BlockID block) {
        return Contains(std::begin(k_PolarBearsSpawnableOnAlternate), std::end(k_PolarBearsSpawnableOnAlternate), block);
    }

    static const BlockID k_RabbitsSpawnableOn[] = {
        BlockID::Grass,
        BlockID::Sand,
        BlockID::SnowLayer,
        BlockID::Snow,
    };
    bool RabbitsSpawnableOn(BlockID block) {
        return Contains(std::begin(k_RabbitsSpawnableOn), std::end(k_RabbitsSpawnableOn), block);
    }

    static const BlockID k_WolvesSpawnableOn[] = {
        BlockID::CoarseDirt,
        BlockID::Grass,
        BlockID::Podzol,
        BlockID::SnowLayer,
        BlockID::Snow,
    };
    bool WolvesSpawnableOn(BlockID block) {
        return Contains(std::begin(k_WolvesSpawnableOn), std::end(k_WolvesSpawnableOn), block);
    }

    static const BlockID k_PreventMobSpawningInside[] = {
        BlockID::ActivatorRail,
        BlockID::DetectorRail,
        BlockID::PoweredRail,
        BlockID::Rail,
    };
    bool PreventMobSpawningInside(BlockID block) {
        return Contains(std::begin(k_PreventMobSpawningInside), std::end(k_PreventMobSpawningInside), block);
    }

    static const BlockID k_Sand[] = {
        BlockID::RedSand,
        BlockID::Sand,
        BlockID::SuspiciousSand,
    };
    bool Sand(BlockID block) {
        return Contains(std::begin(k_Sand), std::end(k_Sand), block);
    }

    static const BlockID k_EndermanHoldable[] = {
        BlockID::Allium,
        BlockID::AzureBluet,
        BlockID::BlueOrchid,
        BlockID::BrownMushroom,
        BlockID::Cactus,
        BlockID::CactusFlower,
        BlockID::CarvedPumpkin,
        BlockID::Clay,
        BlockID::ClosedEyeblossom,
        BlockID::CoarseDirt,
        BlockID::Cornflower,
        BlockID::CrimsonFungus,
        BlockID::CrimsonNylium,
        BlockID::CrimsonRoots,
        BlockID::Dandelion,
        BlockID::Dirt,
        BlockID::Grass,
        BlockID::Gravel,
        BlockID::LilyOfTheValley,
        BlockID::Melon,
        BlockID::MossBlock,
        BlockID::Mud,
        BlockID::MuddyMangroveRoots,
        BlockID::Mycelium,
        BlockID::OpenEyeblossom,
        BlockID::OrangeTulip,
        BlockID::OxeyeDaisy,
        BlockID::PaleMossBlock,
        BlockID::PinkTulip,
        BlockID::Podzol,
        BlockID::Poppy,
        BlockID::Pumpkin,
        BlockID::RedMushroom,
        BlockID::RedSand,
        BlockID::RedTulip,
        BlockID::RootedDirt,
        BlockID::Sand,
        BlockID::Tnt,
        BlockID::Torchflower,
        BlockID::WarpedFungus,
        BlockID::WarpedNylium,
        BlockID::WarpedRoots,
        BlockID::WhiteTulip,
        BlockID::WitherRose,
    };
    bool EndermanHoldable(BlockID block) {
        return Contains(std::begin(k_EndermanHoldable), std::end(k_EndermanHoldable), block);
    }

    static const std::string_view k_AllowsSurfaceSlimeSpawns[] = {
        "mangrove_swamp",
        "swamp",
    };
    bool AllowsSurfaceSlimeSpawns(std::string_view biomeSlug) {
        return Contains(std::begin(k_AllowsSurfaceSlimeSpawns), std::end(k_AllowsSurfaceSlimeSpawns), biomeSlug);
    }

    static const std::string_view k_AllowsTropicalFishSpawnsAtAnyHeight[] = {
        "lush_caves",
    };
    bool AllowsTropicalFishSpawnsAtAnyHeight(std::string_view biomeSlug) {
        return Contains(std::begin(k_AllowsTropicalFishSpawnsAtAnyHeight), std::end(k_AllowsTropicalFishSpawnsAtAnyHeight), biomeSlug);
    }

    static const std::string_view k_MoreFrequentDrownedSpawns[] = {
        "frozen_river",
        "river",
    };
    bool MoreFrequentDrownedSpawns(std::string_view biomeSlug) {
        return Contains(std::begin(k_MoreFrequentDrownedSpawns), std::end(k_MoreFrequentDrownedSpawns), biomeSlug);
    }

    static const std::string_view k_PolarBearsSpawnOnAlternateBlocks[] = {
        "deep_frozen_ocean",
        "frozen_ocean",
    };
    bool PolarBearsSpawnOnAlternateBlocks(std::string_view biomeSlug) {
        return Contains(std::begin(k_PolarBearsSpawnOnAlternateBlocks), std::end(k_PolarBearsSpawnOnAlternateBlocks), biomeSlug);
    }

    static const std::string_view k_ReduceWaterAmbientSpawns[] = {
        "frozen_river",
        "river",
    };
    bool ReduceWaterAmbientSpawns(std::string_view biomeSlug) {
        return Contains(std::begin(k_ReduceWaterAmbientSpawns), std::end(k_ReduceWaterAmbientSpawns), biomeSlug);
    }

} // namespace Game::SpawnTags
