// GENERATED by tools/gen_mob_defs.py — do not edit by hand.
//
// One row per mob that has no hand-written class: the base to build on, its
// attribute overrides from MC's createAttributes(), and its texture.
//
// Behaviour is NOT here — see the generator's docstring. Every generated mob
// gets the shared goal set from MakeGenericMob().
#pragma once

#include "common/entity/Attributes.hpp"
#include "common/entity/GeneratedEntityTypes.hpp"

#include <string_view>

namespace Game {

    enum class MobBase : uint8_t { Mob, PathfinderMob, Monster, Animal };

    struct MobAttrOverride {
        Attribute attribute;
        double    value;
    };

    struct MobDef {
        EntityTypeId     type;
        MobBase          base;
        std::string_view texture;      // "" when the renderer's path was not found
        int              firstAttr, attrCount;
        int              firstFood, foodCount;

        // MC goal speed modifiers. The mob's real walk speed is
        // `modifier * MOVEMENT_SPEED` (MoveControl.java:99), and MC picks the
        // modifier per goal per mob — 0.35 for a wandering trader, 2.0 for a
        // camel. Assuming 1.0 for everyone made 13 mobs too fast and the
        // brain-driven ones half speed.
        double strollSpeed;            // 0 = MC gives this mob no stroll goal
        double panicSpeed;
        double meleeSpeed;
        float  lookDistance;

        // MC SmoothSwimmingMoveControl's outsideWaterSpeedModifier. 1.0 for
        // every mob with the ordinary MoveControl; 0.1 for frog/dolphin/
        // tadpole and 0.0 for the nautilus, which is what keeps a mob with
        // MOVEMENT_SPEED 1.0 from sprinting once it is on land.
        float  landSpeedFactor;

        // MC uses the plain RandomStrollGoal for 8 mobs and the water-avoiding
        // variant for the rest; they are different goals, not a detail.
        bool   strollAvoidsWater;

        // MC LivingEntity.updateWalkAnimation, overridden by camel, frog and
        // creaking. `walkAnimScale` is blocks-travelled -> animation rate; the
        // default is 4, a frog is 25. Getting it wrong plays the right
        // keyframes at the wrong speed.
        float  walkAnimScale, walkAnimCap, walkAnimFactor, walkAnimBabyScale;


        // MC SetEntityLookTargetSometimes' UniformInt interval, for the twelve
        // mobs whose brain looks at the player on a TIMER rather than through
        // LookAtPlayerGoal's 2% roll. 0 = use the goal's probability, which is
        // what MC does for every mob that has a registerGoals.
        int    lookIntervalMin, lookIntervalMax;
        // MC NearestAttackableTargetGoal / AvoidEntityGoal, generated from the
        // `Class<T>` each mob passes. `targetsPlayers` is MC's Player.class
        // case; the spans are everything else, flattened through MC's abstract
        // classes (AbstractVillager -> villager + wandering_trader).
        int    firstTargetType, targetTypeCount;
        int    firstAvoidType,  avoidTypeCount;
        bool   targetsPlayers, avoidsPlayers;

        // MC RestrictSunGoal + FleeSunGoal. AbstractSkeleton only — a zombie
        // caught in daylight just burns, a skeleton runs for shade.
        bool   seeksShade;
    };

    inline constexpr int kMobDefCount = 81;
    extern const MobDef          kMobDefs[kMobDefCount];
    extern const MobAttrOverride kMobAttrs[];

    // Who each mob hunts and flees, indexed by MobDef's spans.
    extern const EntityTypeId    kMobTargetTypes[];
    extern const EntityTypeId    kMobAvoidTypes[];

    // The items MC's isFood accepts, flattened from the item tag it names.
    // TemptGoal and BreedGoal read this; a mob with none of them gets neither
    // goal, which is MC's behaviour for anything whose isFood returns false.
    //
    // Slugs rather than ItemIDs because a food may be a BLOCK item — cactus,
    // bamboo, seagrass and thirty-odd flowers — whose ItemID is derived from
    // its BlockID and so has no constant in GeneratedItemList. Resolved once at
    // startup through RecipeManager::ItemFromSlug, the same way recipes and
    // loot tables already do it.
    extern const char* const      kMobFoodSlugs[];

    // Null for the eight hand-written mobs and for anything not a mob.
    const MobDef* FindMobDef(EntityTypeId type);

} // namespace Game
