// GENERATED by tools/gen_entity_types.py — do not edit by hand.
//
// Every number here is transcribed from MC's EntityType.java. They are not
// tunable: `sized(0.6F, 1.95F)` really is 1.95, and the difference is whether
// a zombie fits under a two-block ceiling.
//
// ORDERING IS WIRE-VISIBLE. AddEntityS2C sends the type as an index into this
// enum, so entries may be APPENDED but never reordered or removed. The
// generator preserves the existing order for exactly that reason.
#pragma once

#include "common/entity/MobCategory.hpp"

#include <cstdint>
#include <string_view>

namespace Game {

    enum class EntityTypeId : uint16_t {
        Zombie = 0,  // "zombie"
        Skeleton = 1,  // "skeleton"
        Creeper = 2,  // "creeper"
        Spider = 3,  // "spider"
        Cow = 4,  // "cow"
        Pig = 5,  // "pig"
        Sheep = 6,  // "sheep"
        Chicken = 7,  // "chicken"
        Arrow = 8,  // "arrow"
        Allay = 9,  // "allay"
        Armadillo = 10,  // "armadillo"
        Axolotl = 11,  // "axolotl"
        Bat = 12,  // "bat"
        Bee = 13,  // "bee"
        Blaze = 14,  // "blaze"
        Bogged = 15,  // "bogged"
        Breeze = 16,  // "breeze"
        Camel = 17,  // "camel"
        CamelHusk = 18,  // "camel_husk"
        Cat = 19,  // "cat"
        CaveSpider = 20,  // "cave_spider"
        Cod = 21,  // "cod"
        Creaking = 22,  // "creaking"
        Dolphin = 23,  // "dolphin"
        Donkey = 24,  // "donkey"
        Drowned = 25,  // "drowned"
        ElderGuardian = 26,  // "elder_guardian"
        EnderDragon = 27,  // "ender_dragon"
        Enderman = 28,  // "enderman"
        Endermite = 29,  // "endermite"
        Evoker = 30,  // "evoker"
        Fox = 31,  // "fox"
        Frog = 32,  // "frog"
        Ghast = 33,  // "ghast"
        Giant = 34,  // "giant"
        GlowSquid = 35,  // "glow_squid"
        Goat = 36,  // "goat"
        Guardian = 37,  // "guardian"
        HappyGhast = 38,  // "happy_ghast"
        Hoglin = 39,  // "hoglin"
        Horse = 40,  // "horse"
        Husk = 41,  // "husk"
        Illusioner = 42,  // "illusioner"
        Llama = 43,  // "llama"
        MagmaCube = 44,  // "magma_cube"
        Mooshroom = 45,  // "mooshroom"
        Mule = 46,  // "mule"
        Nautilus = 47,  // "nautilus"
        Ocelot = 48,  // "ocelot"
        Panda = 49,  // "panda"
        Parched = 50,  // "parched"
        Parrot = 51,  // "parrot"
        Phantom = 52,  // "phantom"
        Piglin = 53,  // "piglin"
        PiglinBrute = 54,  // "piglin_brute"
        Pillager = 55,  // "pillager"
        PolarBear = 56,  // "polar_bear"
        Pufferfish = 57,  // "pufferfish"
        Rabbit = 58,  // "rabbit"
        Ravager = 59,  // "ravager"
        Salmon = 60,  // "salmon"
        Shulker = 61,  // "shulker"
        Silverfish = 62,  // "silverfish"
        SkeletonHorse = 63,  // "skeleton_horse"
        Slime = 64,  // "slime"
        Sniffer = 65,  // "sniffer"
        Squid = 66,  // "squid"
        Stray = 67,  // "stray"
        Strider = 68,  // "strider"
        Tadpole = 69,  // "tadpole"
        TraderLlama = 70,  // "trader_llama"
        TropicalFish = 71,  // "tropical_fish"
        Turtle = 72,  // "turtle"
        Vex = 73,  // "vex"
        Vindicator = 74,  // "vindicator"
        WanderingTrader = 75,  // "wandering_trader"
        Warden = 76,  // "warden"
        Witch = 77,  // "witch"
        Wither = 78,  // "wither"
        WitherSkeleton = 79,  // "wither_skeleton"
        Wolf = 80,  // "wolf"
        Zoglin = 81,  // "zoglin"
        ZombieHorse = 82,  // "zombie_horse"
        ZombieNautilus = 83,  // "zombie_nautilus"
        ZombieVillager = 84,  // "zombie_villager"
        ZombifiedPiglin = 85,  // "zombified_piglin"
        CopperGolem = 86,  // "copper_golem"
        IronGolem = 87,  // "iron_golem"
        SnowGolem = 88,  // "snow_golem"
        Villager = 89,  // "villager"
        Count
    };

    struct EntityTypeInfo {
        std::string_view slug;
        float       width;
        float       height;
        // MC's default when `.eyeHeight(...)` is absent is height * 0.85,
        // already folded in here so nothing has to remember the rule.
        float       eyeHeight;
        MobCategory category;
        // clientTrackingRange, in CHUNKS. Multiply by 16 for blocks.
        int         clientTrackingRange;
        // ServerEntity.updateInterval — ticks between periodic position sends.
        int         updateInterval;
        // Eye height when this type is a baby. 0 means 'derive it'
        // (eyeHeight * 0.5); MC hardcodes an override for the mobs whose baby
        // model has a proportionally larger head.
        float       babyEyeHeight;
        // Monster's ctor sets 5; Animal returns 1 + rand(3) itself, so 0 here
        // means 'ask the entity'.
        int         xpReward;
        bool        notInPeaceful;
    };

    // LivingEntity.DEFAULT_BABY_SCALE — one value for every type.
    inline constexpr float kBabyScale = 0.5f;

    inline constexpr int kEntityTypeCount = 90;
    extern const EntityTypeInfo kEntityTypeTable[kEntityTypeCount];

    inline const EntityTypeInfo& GetEntityTypeInfo(EntityTypeId t) {
        return kEntityTypeTable[static_cast<size_t>(t)];
    }

    inline bool IsValidEntityType(uint16_t raw) {
        return raw < static_cast<uint16_t>(EntityTypeId::Count);
    }

    // Eye height for an instance, honouring the baby override.
    inline float GetEyeHeight(EntityTypeId t, bool baby) {
        const EntityTypeInfo& info = GetEntityTypeInfo(t);
        if (!baby) return info.eyeHeight;
        if (info.babyEyeHeight > 0.0f) return info.babyEyeHeight;
        return info.eyeHeight * kBabyScale;
    }

} // namespace Game
