// GENERATED by tools/gen_item_attributes.py — do not edit by hand.
//
// MC's per-weapon ATTACK_DAMAGE and ATTACK_SPEED modifiers, from Items.java
// combined with ToolMaterial.java.
//
// Both are ADD_VALUE modifiers applied while the item is in the MAIN HAND, on
// top of the player's own base attributes (ATTACK_DAMAGE 1.0, ATTACK_SPEED
// 4.0). So an iron sword's row of (5.0, -2.4) means 1 + 5 = 6 damage and
// 4 - 2.4 = 1.6 attacks/second, which is 20 / 1.6 = 12.5 ticks per full swing.
//
// A weapon's damage is deliberately NOT one number in MC: it is a per-kind
// baseline plus a per-material bonus, so every sword shares 3.0 and differs
// only by its material. The generator does that addition.
#pragma once

#include <cstdint>
#include <string_view>

namespace Game {

    // MC's player base attributes, from Player.createAttributes(). A weapon's
    // row is ADDED to these — which is why an iron sword (row +5) reads as 6
    // damage in game and swings at 4.0 - 2.4 = 1.6 per second.
    inline constexpr float kPlayerBaseAttackDamage = 1.0f;
    inline constexpr float kPlayerBaseAttackSpeed  = 4.0f;

    // What the item is, for the handful of rules that ask. MC expresses this
    // as item TAGS (ItemTags.SWORDS and friends); this port has no runtime tag
    // system, and the tag's contents are exactly what the registration form in
    // Items.java already tells us, so the kind rides along on this row.
    enum class WeaponKind : uint8_t {
        Other = 0, Sword, Axe, Pickaxe, Shovel, Hoe, Trident, Mace
    };

    struct ItemAttributeRow {
        std::string_view slug;
        float attackDamage;   // ADD_VALUE onto ATTACK_DAMAGE, main hand
        float attackSpeed;    // ADD_VALUE onto ATTACK_SPEED, main hand
        WeaponKind kind;
    };

    inline constexpr int kItemAttributeCount = 37;
    extern const ItemAttributeRow kItemAttributes[kItemAttributeCount];

    // Resolves slugs to ItemIDs once at startup, like the recipe and mob-food
    // tables. Safe to call more than once.
    void InitItemAttributes();

    // The main-hand modifiers for an item, or (0, 0) for anything that is not a
    // weapon — which is MC's answer too: a snowball adds nothing, so a player
    // holding one punches for the bare-hand 1.0.
    void GetItemAttackAttributes(uint32_t itemId, float& outDamage, float& outSpeed);

    WeaponKind GetWeaponKind(uint32_t itemId);

    // MC ItemTags.SWORDS — the sweep attack's gate (Player.isSweepAttack).
    inline bool IsSwordItem(uint32_t itemId) {
        return GetWeaponKind(itemId) == WeaponKind::Sword;
    }

} // namespace Game
