// GENERATED by tools/gen_item_attributes.py — do not edit by hand.
#include "common/entity/GeneratedItemAttributes.hpp"
#include "common/world/crafting/RecipeManager.hpp"
#include "common/core/Log.hpp"

#include <string>
#include <unordered_map>

namespace Game {

    const ItemAttributeRow kItemAttributes[kItemAttributeCount] = {
    { "copper_axe", 8.0f, -3.2f, WeaponKind::Axe },   // copper axe
    { "copper_hoe", 0.0f, -2.0f, WeaponKind::Hoe },   // copper hoe
    { "copper_pickaxe", 2.0f, -2.8f, WeaponKind::Pickaxe },   // copper pickaxe
    { "copper_shovel", 2.5f, -3.0f, WeaponKind::Shovel },   // copper shovel
    { "copper_sword", 4.0f, -2.4f, WeaponKind::Sword },   // copper sword
    { "diamond_axe", 8.0f, -3.0f, WeaponKind::Axe },   // diamond axe
    { "diamond_hoe", 0.0f, 0.0f, WeaponKind::Hoe },   // diamond hoe
    { "diamond_pickaxe", 4.0f, -2.8f, WeaponKind::Pickaxe },   // diamond pickaxe
    { "diamond_shovel", 4.5f, -3.0f, WeaponKind::Shovel },   // diamond shovel
    { "diamond_sword", 6.0f, -2.4f, WeaponKind::Sword },   // diamond sword
    { "golden_axe", 6.0f, -3.0f, WeaponKind::Axe },   // gold axe
    { "golden_hoe", 0.0f, -3.0f, WeaponKind::Hoe },   // gold hoe
    { "golden_pickaxe", 1.0f, -2.8f, WeaponKind::Pickaxe },   // gold pickaxe
    { "golden_shovel", 1.5f, -3.0f, WeaponKind::Shovel },   // gold shovel
    { "golden_sword", 3.0f, -2.4f, WeaponKind::Sword },   // gold sword
    { "iron_axe", 8.0f, -3.1f, WeaponKind::Axe },   // iron axe
    { "iron_hoe", 0.0f, -1.0f, WeaponKind::Hoe },   // iron hoe
    { "iron_pickaxe", 3.0f, -2.8f, WeaponKind::Pickaxe },   // iron pickaxe
    { "iron_shovel", 3.5f, -3.0f, WeaponKind::Shovel },   // iron shovel
    { "iron_sword", 5.0f, -2.4f, WeaponKind::Sword },   // iron sword
    { "mace", 5.0f, -3.4f, WeaponKind::Mace },   // - mace
    { "netherite_axe", 9.0f, -3.0f, WeaponKind::Axe },   // netherite axe
    { "netherite_hoe", 0.0f, 0.0f, WeaponKind::Hoe },   // netherite hoe
    { "netherite_pickaxe", 5.0f, -2.8f, WeaponKind::Pickaxe },   // netherite pickaxe
    { "netherite_shovel", 5.5f, -3.0f, WeaponKind::Shovel },   // netherite shovel
    { "netherite_sword", 7.0f, -2.4f, WeaponKind::Sword },   // netherite sword
    { "stone_axe", 8.0f, -3.2f, WeaponKind::Axe },   // stone axe
    { "stone_hoe", 0.0f, -2.0f, WeaponKind::Hoe },   // stone hoe
    { "stone_pickaxe", 2.0f, -2.8f, WeaponKind::Pickaxe },   // stone pickaxe
    { "stone_shovel", 2.5f, -3.0f, WeaponKind::Shovel },   // stone shovel
    { "stone_sword", 4.0f, -2.4f, WeaponKind::Sword },   // stone sword
    { "trident", 8.0f, -2.9f, WeaponKind::Trident },   // - trident
    { "wooden_axe", 6.0f, -3.2f, WeaponKind::Axe },   // wood axe
    { "wooden_hoe", 0.0f, -3.0f, WeaponKind::Hoe },   // wood hoe
    { "wooden_pickaxe", 1.0f, -2.8f, WeaponKind::Pickaxe },   // wood pickaxe
    { "wooden_shovel", 1.5f, -3.0f, WeaponKind::Shovel },   // wood shovel
    { "wooden_sword", 3.0f, -2.4f, WeaponKind::Sword },   // wood sword
    };

    namespace {
        std::unordered_map<uint32_t, const ItemAttributeRow*> g_byId;
        bool g_initialised = false;
    }

    void InitItemAttributes() {
        if (g_initialised) return;
        g_initialised = true;
        for (const ItemAttributeRow& row : kItemAttributes) {
            const ItemID id = RecipeManager::ItemFromSlug(std::string(row.slug));
            if (id != Items::Air) g_byId[static_cast<uint32_t>(id)] = &row;
        }

        // Boot line, because the failure is otherwise invisible: an
        // unresolved table leaves every weapon at (0, 0), which reads in
        // game as a netherite axe hitting for the bare-hand 1.0 rather
        // than as anything obviously broken. Must run AFTER
        // RecipeManager::Initialize — that owns the slug map.
        Log::Info("[ItemAttributes] %zu/%d weapons resolved",
                  g_byId.size(), kItemAttributeCount);
    }

    void GetItemAttackAttributes(uint32_t itemId, float& outDamage, float& outSpeed) {
        outDamage = 0.0f;
        outSpeed  = 0.0f;
        const auto it = g_byId.find(itemId);
        if (it == g_byId.end()) return;
        outDamage = it->second->attackDamage;
        outSpeed  = it->second->attackSpeed;
    }

    WeaponKind GetWeaponKind(uint32_t itemId) {
        const auto it = g_byId.find(itemId);
        return it == g_byId.end() ? WeaponKind::Other : it->second->kind;
    }

} // namespace Game
