#pragma once
#include <cstddef>

namespace console {
// SCreditTextItemDef: `format` is swprintf'd with the strings `first` and
// `second` (-1 none). first == -2 is a CREDIT_ICON entry and `second` the
// logo (0 Iggy, 1 Miles, 2 Dolby). size: 0 small, 1 medium, 2 large, 3 extra large.
struct ConsoleCredit {
    const char* format;
    int first,second,size;
};
// ported/ConsoleCredits.cpp is generated by tools/extract_credits.py.
const ConsoleCredit* consoleCredits(std::size_t& count);
}
