#pragma once
#include <string_view>

namespace console {
// English console strings (ported/ConsoleStrings.cpp is generated by
// tools/extract_strings.py). IDs are the PS3 IDS_* numbering from
// source_full/Minecraft.Client/PS3Media/strings.h, which app.GetString uses.
// Text keeps the {*...*} tokens; see RichText.h for expanding them.
int consoleStringCount();
const char* consoleString(int id);
const char* consoleStringName(int id);
int consoleStringId(std::string_view name);
}
