#pragma once
#include "World.h"
#include "GenerationRegion.h"
#include "PS3WorldStorage.h"
#include "WorldGenLevel.h"
#include "TutorialSchematics.h"
#include "TutorialWorldSource.h"
#include "Random.h"
#include "CombatRules.h"
#include "FoodData.h"
#include "PlayerExperience.h"
#include <set>
namespace console {
struct World::State {
    GenerationRegion region;
    std::map<std::pair<int,int>,std::unique_ptr<ChunkRecord>> records;
    // Only chunks generated by this port and never edited may receive the
    // delayed natural feature pass. Imported records are left intact.
    std::set<std::pair<int,int>> undecorated;
    // Untouched generator output for deterministic feature replay. Never use
    // live/saved chunks as inputs: player edits or prior features could alter
    // placement in a newly streamed neighbor.
    std::map<std::pair<int,int>,std::unique_ptr<ChunkStorage>> rawBase;
    std::unique_ptr<PS3WorldStorage> archive;
    std::unique_ptr<LevelData> metadata;
    std::unique_ptr<::Level> lightLevel;
    int originX=0,originZ=0;
    struct Pending {
        enum class Phase { Chunks, Base, Decorating, Evicting, Lighting } phase=Phase::Chunks;
        bool restartLighting=false;
        std::uint64_t captureRevision=0;
        std::size_t outgoingIndex=0;
        std::set<std::pair<int,int>> archivedOutgoing;
        std::vector<std::pair<int,int>> outgoing;
        int x=0,z=0;
        std::vector<std::pair<int,int>> missing;
        std::vector<std::pair<int,int>> decorationTargets;
        std::vector<std::pair<int,int>> baseMissing;
        std::size_t decorationIndex=0;
        std::set<std::pair<int,int>> undecorated;
        std::set<std::pair<int,int>> decoratedExisting;
        std::map<std::pair<int,int>,std::unique_ptr<ChunkStorage>> chunks;
        std::map<std::pair<int,int>,std::unique_ptr<ChunkRecord>> records;
    };
    std::unique_ptr<Pending> pending;
    std::unique_ptr<ChunkGenerator> generator;
    std::unique_ptr<TutorialSchematics> tutorial;
    std::unique_ptr<TutorialWorldSource> archivedTutorial;
    Random fluidRandom;
    Random entityRandom;
    std::map<std::tuple<int,int,int>,std::int64_t> fluidTicks;
    std::vector<SimulatedEntity> entities;
    std::vector<ExperienceOrbState> experienceOrbs;
    int playerXpPickupDelay=0;
    std::vector<HangingDecoration> hangingDecorations;
    Vec3 playerPosition;
    bool hasPlayerPosition=false;
    std::vector<PotionEffect> playerEffects;
    PlayerHurtState playerHurt;
    FoodData playerFood;
    PlayerExperience playerExperience;
    std::vector<DroppedItem> droppedItems;
    int playerAir=300,playerFire=0,playerPickupDelay=0;
    std::int64_t timeOfDayOverride=-1;
    bool tutorialSpawning=false;
    bool playerDeathHandled=false;
    std::optional<Vec3> savedPlayerPosition;
    Random survivalRandom{0x5eed5eed};
    void decorateNatural(int x,int z,std::map<std::pair<int,int>,std::unique_ptr<ChunkStorage>>* incoming=nullptr);
    std::unique_ptr<CompoundTag> inventory=std::make_unique<CompoundTag>();
    std::unique_ptr<CompoundTag> enderInventory=std::make_unique<CompoundTag>();
    CompoundTag* chest(int x,int y,int z)const;
    CompoundTag* furnace(int x,int y,int z)const;
    CompoundTag* brewingStand(int x,int y,int z)const;
    bool terrain=false;
    bool lightDirty=true;
    explicit State(std::int64_t seed);
    ChunkStorage& chunk(int x,int z)const{return *region.chunks.at({Mth::intFloorDiv(x-width/2,16),Mth::intFloorDiv(z-depth/2,16)});}
    void ensureLighting(std::int64_t seed);
    void configureLight(std::int64_t seed);
};
}
