#pragma once
#include "World.h"
#include "GenerationRegion.h"
#include "PS3WorldStorage.h"
#include "WorldGenLevel.h"
#include "TutorialSchematics.h"
#include "TutorialWorldSource.h"
#include "Random.h"
#include "CombatRules.h"
#include "FoodData.h"
#include "PlayerExperience.h"
#include "ScheduledTickQueue.h"
#include "TileTickHost.h"
#include <set>
namespace console {
struct World::State {
    GenerationRegion region;
    std::map<std::pair<int,int>,std::unique_ptr<ChunkRecord>> records;
    // Only chunks generated by this port and never edited may receive the
    // delayed natural feature pass. Imported records are left intact.
    std::set<std::pair<int,int>> undecorated;
    // Untouched generator output for deterministic feature replay. Never use
    // live/saved chunks as inputs: player edits or prior features could alter
    // placement in a newly streamed neighbor.
    std::map<std::pair<int,int>,std::unique_ptr<ChunkStorage>> rawBase;
    std::unique_ptr<PS3WorldStorage> archive;
    std::unique_ptr<LevelData> metadata;
    std::unique_ptr<::Level> lightLevel;
    int originX=0,originZ=0;
    struct Pending {
        enum class Phase { Chunks, Base, Decorating, Evicting, Lighting } phase=Phase::Chunks;
        bool restartLighting=false;
        std::uint64_t captureRevision=0;
        std::size_t outgoingIndex=0;
        std::set<std::pair<int,int>> archivedOutgoing;
        std::vector<std::pair<int,int>> outgoing;
        int x=0,z=0;
        std::vector<std::pair<int,int>> missing;
        std::vector<std::pair<int,int>> decorationTargets;
        std::vector<std::pair<int,int>> baseMissing;
        std::size_t decorationIndex=0;
        std::set<std::pair<int,int>> undecorated;
        std::set<std::pair<int,int>> decoratedExisting;
        std::map<std::pair<int,int>,std::unique_ptr<ChunkStorage>> chunks;
        std::map<std::pair<int,int>,std::unique_ptr<ChunkRecord>> records;
    };
    std::unique_ptr<Pending> pending;
    std::unique_ptr<ChunkGenerator> generator;
    std::unique_ptr<TutorialSchematics> tutorial;
    std::unique_ptr<TutorialWorldSource> archivedTutorial;
    Random entityRandom;
    // ServerLevel's pending tile ticks, in level coordinates, over the
    // resident region; WorldTiles.cpp.
    struct TileTickHost final:ScheduledTickHost {
        World* world=nullptr;
        State& state;
        explicit TileTickHost(State& owner):state(owner){}
        std::int64_t getTime()const override;
        void setTime(std::int64_t time)noexcept override;
        bool getInstaTick()const override{return false;}
        bool hasChunksAt(int x0,int y0,int z0,int x1,int y1,int z1)override;
        int getTile(int x,int y,int z)override;
        void tickTile(int id,int x,int y,int z)override;
    } tileTickHost{*this};
    ScheduledTickQueue tileTicks{tileTickHost};
    std::vector<FallingBlock> fallingBlocks;
    // Level's tile entities the port runs (piston pieces), in level
    // coordinates, and the ones Level::tickEntities ticks.
    std::map<std::tuple<int,int,int>,std::shared_ptr<console::sim::TileEntity>> tileEntities;
    std::vector<std::shared_ptr<console::sim::TileEntity>> tickingTileEntities;
    // ServerLevel's two tile event lists (TileEventData).
    struct TileEvent {
        int x,y,z,tile,paramA,paramB;
        bool operator==(const TileEvent&)const=default;
    };
    std::vector<TileEvent> tileEvents[2];
    int activeTileEvents=0;
    // How far pistons pushed the player, and the explosion knockback, since
    // the client last asked.
    Vec3 playerPush,playerKnockback;
    // PrimedTnt entities: centre, motion and fuse.
    struct Primed { Vec3 position,velocity;int life=80; };
    std::vector<Primed> primedTnt;
    std::vector<SimulatedEntity> entities;
    std::vector<ExperienceOrbState> experienceOrbs;
    int playerXpPickupDelay=0;
    std::vector<HangingDecoration> hangingDecorations;
    Vec3 playerPosition;
    bool hasPlayerPosition=false;
    std::vector<PotionEffect> playerEffects;
    PlayerHurtState playerHurt;
    FoodData playerFood;
    PlayerExperience playerExperience;
    std::vector<DroppedItem> droppedItems;
    int playerAir=300,playerFire=0,playerPickupDelay=0;
    std::int64_t timeOfDayOverride=-1;
    bool tutorialSpawning=false;
    bool playerDeathHandled=false;
    std::optional<Vec3> savedPlayerPosition;
    Random survivalRandom{0x5eed5eed};
    // ServerLevel's random tile ticks: the level Random, the randValue/addend
    // generator (Level constructor), the tiles the update thread chose last
    // tick and the chunks polled this tick; tickClientSideTiles' mood delay.
    Random tickRandom;
    int randValue=Random().nextInt();
    static constexpr int addend=1013904223;
    int delayUntilNextMoodSound=-1;
    std::vector<std::array<int,3>> updateTiles;
    // Level::tickWeather's rain and thunder levels (prepareWeather on load).
    bool weatherPrepared=false;
    float rainLevel=0,oRainLevel=0,thunderLevel=0,oThunderLevel=0;
    int lightningTime=0;
    void decorateNatural(int x,int z,std::map<std::pair<int,int>,std::unique_ptr<ChunkStorage>>* incoming=nullptr);
    std::unique_ptr<CompoundTag> inventory=std::make_unique<CompoundTag>();
    std::unique_ptr<CompoundTag> enderInventory=std::make_unique<CompoundTag>();
    CompoundTag* chest(int x,int y,int z)const;
    CompoundTag* furnace(int x,int y,int z)const;
    CompoundTag* brewingStand(int x,int y,int z)const;
    bool terrain=false;
    bool lightDirty=true;
    explicit State(std::int64_t seed);
    ~State();
    ChunkStorage& chunk(int x,int z)const{return *region.chunks.at({Mth::intFloorDiv(x-width/2,16),Mth::intFloorDiv(z-depth/2,16)});}
    void ensureLighting(std::int64_t seed);
    void configureLight(std::int64_t seed);
};
}
