// GENERATED by tools/gen_memory_modules.py — do not edit by hand.
//
// MC net.minecraft.world.entity.ai.memory.MemoryModuleType, as an enum plus a
// declared value kind. The comment on each row is MC's own generic parameter,
// so the mapping from `MemoryModuleType<WalkTarget>` to a variant alternative
// stays checkable by eye.
#pragma once

#include <cstdint>
#include <string_view>

namespace Game {

    // Which alternative of MemoryValue a module stores. Checked on every write:
    // a behaviour that puts the wrong type in a memory would otherwise store it
    // happily and the reader would find nothing, which looks like a brain that
    // simply does not work.
    enum class MemoryKind : uint8_t {
        Unit, Bool, Int, Long, Float, BlockPos, Vec3,
        WalkTarget, PositionTracker, Path, VisibleEntities, EntityList, Entity,
    };

    enum class MemoryModule : uint16_t {
        Home,                          // GlobalPos
        JobSite,                       // GlobalPos
        PotentialJobSite,              // GlobalPos
        MeetingPoint,                  // GlobalPos
        SecondaryJobSite,              // List<GlobalPos>
        NearestLivingEntities,         // List<LivingEntity>
        NearestVisibleLivingEntities,  // NearestVisibleLivingEntities
        VisibleVillagerBabies,         // List<LivingEntity>
        NearestPlayers,                // List<Player>
        NearestVisiblePlayer,          // Player
        NearestVisibleAttackablePlayer, // Player
        NearestVisibleAttackablePlayers, // List<Player>
        WalkTarget,                    // WalkTarget
        LookTarget,                    // PositionTracker
        AttackTarget,                  // LivingEntity
        AttackCoolingDown,             // Boolean
        InteractionTarget,             // LivingEntity
        BreedTarget,                   // AgeableMob
        RideTarget,                    // Entity
        Path,                          // Path
        InteractableDoors,             // List<GlobalPos>
        DoorsToClose,                  // Set<GlobalPos>
        NearestBed,                    // BlockPos
        HurtBy,                        // DamageSource
        HurtByEntity,                  // LivingEntity
        AvoidTarget,                   // LivingEntity
        NearestHostile,                // LivingEntity
        NearestAttackable,             // LivingEntity
        HidingPlace,                   // GlobalPos
        HeardBellTime,                 // Long
        CantReachWalkTargetSince,      // Long
        GolemDetectedRecently,         // Boolean
        DangerDetectedRecently,        // Boolean
        LastSlept,                     // Long
        LastWoken,                     // Long
        LastWorkedAtPoi,               // Long
        NearestVisibleAdult,           // LivingEntity
        NearestVisibleWantedItem,      // ItemEntity
        NearestVisibleNemesis,         // Mob
        PlayDeadTicks,                 // Integer
        TemptingPlayer,                // Player
        TemptationCooldownTicks,       // Integer
        GazeCooldownTicks,             // Integer
        IsTempted,                     // Boolean
        LongJumpCooldownTicks,         // Integer
        LongJumpMidJump,               // Boolean
        HasHuntingCooldown,            // Boolean
        RamCooldownTicks,              // Integer
        RamTarget,                     // Vec3
        IsInWater,                     // Unit
        IsPregnant,                    // Unit
        IsPanicking,                   // Boolean
        UnreachableTongueTargets,      // List<UUID>
        VisitedBlockPositions,         // Set<GlobalPos>
        UnreachableTransportBlockPositions, // Set<GlobalPos>
        TransportItemsCooldownTicks,   // Integer
        ChargeCooldownTicks,           // Integer
        AttackTargetCooldown,          // Integer
        SpearFleeingTime,              // Integer
        SpearFleeingPosition,          // Vec3
        SpearChargePosition,           // Vec3
        SpearEngageTime,               // Integer
        SpearStatus,                   // SpearAttack.SpearStatus
        AngryAt,                       // UUID
        UniversalAnger,                // Boolean
        AdmiringItem,                  // Boolean
        TimeTryingToReachAdmireItem,   // Integer
        DisableWalkToAdmireItem,       // Boolean
        AdmiringDisabled,              // Boolean
        HuntedRecently,                // Boolean
        CelebrateLocation,             // BlockPos
        Dancing,                       // Boolean
        NearestVisibleHuntableHoglin,  // Hoglin
        NearestVisibleBabyHoglin,      // Hoglin
        NearestTargetablePlayerNotWearingGold, // Player
        NearbyAdultPiglins,            // List<AbstractPiglin>
        NearestVisibleAdultPiglins,    // List<AbstractPiglin>
        NearestVisibleAdultHoglins,    // List<Hoglin>
        NearestVisibleAdultPiglin,     // AbstractPiglin
        NearestVisibleZombified,       // LivingEntity
        VisibleAdultPiglinCount,       // Integer
        VisibleAdultHoglinCount,       // Integer
        NearestPlayerHoldingWantedItem, // Player
        AteRecently,                   // Boolean
        NearestRepellent,              // BlockPos
        Pacified,                      // Boolean
        RoarTarget,                    // LivingEntity
        DisturbanceLocation,           // BlockPos
        RecentProjectile,              // Unit
        IsSniffing,                    // Unit
        IsEmerging,                    // Unit
        RoarSoundDelay,                // Unit
        DigCooldown,                   // Unit
        RoarSoundCooldown,             // Unit
        SniffCooldown,                 // Unit
        TouchCooldown,                 // Unit
        VibrationCooldown,             // Unit
        SonicBoomCooldown,             // Unit
        SonicBoomSoundCooldown,        // Unit
        SonicBoomSoundDelay,           // Unit
        LikedPlayer,                   // UUID
        LikedNoteblockPosition,        // GlobalPos
        LikedNoteblockCooldownTicks,   // Integer
        ItemPickupCooldownTicks,       // Integer
        SnifferExploredPositions,      // List<GlobalPos>
        SnifferSniffingTarget,         // BlockPos
        SnifferDigging,                // Boolean
        SnifferHappy,                  // Boolean
        BreezeJumpCooldown,            // Unit
        BreezeShoot,                   // Unit
        BreezeShootCharging,           // Unit
        BreezeShootRecovering,         // Unit
        BreezeShootCooldown,           // Unit
        BreezeJumpInhaling,            // Unit
        BreezeJumpTarget,              // BlockPos
        BreezeLeavingWater,            // Unit
        Count,
    };

    inline constexpr int kMemoryModuleCount = static_cast<int>(MemoryModule::Count);

    MemoryKind       MemoryModuleKind(MemoryModule m);
    std::string_view MemoryModuleName(MemoryModule m);

} // namespace Game
