// File: src/common/world/loot/GeneratedMobLoot.cpp
// AUTO-GENERATED by tools/gen_mob_loot.py — DO NOT EDIT BY HAND.
#include "common/world/loot/GeneratedMobLoot.hpp"
#include "common/entity/GeneratedItemList.hpp"

namespace Game {

    // bogged
    static const MobLootEntry k_bogged[] = {
        { Items::Arrow, 0, 2, Items::Air },
        { Items::Bone, 0, 2, Items::Air },
    };

    // camel_husk
    static const MobLootEntry k_camel_husk[] = {
        { Items::RottenFlesh, 2, 3, Items::Air },
    };

    // cat
    static const MobLootEntry k_cat[] = {
        { Items::String, 0, 2, Items::Air },
    };

    // cave_spider
    static const MobLootEntry k_cave_spider[] = {
        { Items::String, 0, 2, Items::Air },
    };

    // chicken
    static const MobLootEntry k_chicken[] = {
        { Items::Feather, 0, 2, Items::Air },
        { Items::Chicken, 1, 1, Items::CookedChicken },
    };

    // cod
    static const MobLootEntry k_cod[] = {
        { Items::Cod, 1, 1, Items::CookedCod },
    };

    // copper_golem
    static const MobLootEntry k_copper_golem[] = {
        { Items::CopperIngot, 1, 3, Items::Air },
    };

    // cow
    static const MobLootEntry k_cow[] = {
        { Items::Leather, 0, 2, Items::Air },
        { Items::Beef, 1, 3, Items::CookedBeef },
    };

    // creeper
    static const MobLootEntry k_creeper[] = {
        { Items::Gunpowder, 0, 2, Items::Air },
    };

    // dolphin
    static const MobLootEntry k_dolphin[] = {
        { Items::Cod, 0, 1, Items::CookedCod },
    };

    // donkey
    static const MobLootEntry k_donkey[] = {
        { Items::Leather, 0, 2, Items::Air },
    };

    // drowned
    static const MobLootEntry k_drowned[] = {
        { Items::RottenFlesh, 0, 2, Items::Air },
    };

    // elder_guardian
    static const MobLootEntry k_elder_guardian[] = {
        { Items::PrismarineShard, 0, 2, Items::Air },
        { Items::Cod, 1, 1, Items::CookedCod },
        { Items::PrismarineCrystals, 1, 1, Items::Air },
        { Items::TideArmorTrimSmithingTemplate, 1, 1, Items::Air },
    };

    // enderman
    static const MobLootEntry k_enderman[] = {
        { Items::EnderPearl, 0, 1, Items::Air },
    };

    // evoker
    static const MobLootEntry k_evoker[] = {
        { Items::TotemOfUndying, 1, 1, Items::Air },
    };

    // ghast
    static const MobLootEntry k_ghast[] = {
        { Items::GhastTear, 0, 1, Items::Air },
        { Items::Gunpowder, 0, 2, Items::Air },
    };

    // glow_squid
    static const MobLootEntry k_glow_squid[] = {
        { Items::GlowInkSac, 1, 3, Items::Air },
    };

    // guardian
    static const MobLootEntry k_guardian[] = {
        { Items::PrismarineShard, 0, 2, Items::Air },
        { Items::Cod, 1, 1, Items::CookedCod },
        { Items::PrismarineCrystals, 1, 1, Items::Air },
    };

    // hoglin
    static const MobLootEntry k_hoglin[] = {
        { Items::Porkchop, 2, 4, Items::CookedPorkchop },
        { Items::Leather, 0, 1, Items::Air },
    };

    // horse
    static const MobLootEntry k_horse[] = {
        { Items::Leather, 0, 2, Items::Air },
    };

    // husk
    static const MobLootEntry k_husk[] = {
        { Items::RottenFlesh, 0, 2, Items::Air },
    };

    // iron_golem
    static const MobLootEntry k_iron_golem[] = {
        { Items::IronIngot, 3, 5, Items::Air },
    };

    // llama
    static const MobLootEntry k_llama[] = {
        { Items::Leather, 0, 2, Items::Air },
    };

    // mooshroom
    static const MobLootEntry k_mooshroom[] = {
        { Items::Leather, 0, 2, Items::Air },
        { Items::Beef, 1, 3, Items::CookedBeef },
    };

    // mule
    static const MobLootEntry k_mule[] = {
        { Items::Leather, 0, 2, Items::Air },
    };

    // parched
    static const MobLootEntry k_parched[] = {
        { Items::Arrow, 0, 2, Items::Air },
        { Items::Bone, 0, 2, Items::Air },
    };

    // parrot
    static const MobLootEntry k_parrot[] = {
        { Items::Feather, 1, 2, Items::Air },
    };

    // pig
    static const MobLootEntry k_pig[] = {
        { Items::Porkchop, 1, 3, Items::CookedPorkchop },
    };

    // polar_bear
    static const MobLootEntry k_polar_bear[] = {
        { Items::Cod, 0, 2, Items::CookedCod },
        { Items::Salmon, 0, 2, Items::CookedSalmon },
    };

    // pufferfish
    static const MobLootEntry k_pufferfish[] = {
        { Items::Pufferfish, 1, 1, Items::Air },
    };

    // rabbit
    static const MobLootEntry k_rabbit[] = {
        { Items::RabbitHide, 0, 1, Items::Air },
        { Items::Rabbit, 1, 1, Items::CookedRabbit },
    };

    // ravager
    static const MobLootEntry k_ravager[] = {
        { Items::Saddle, 1, 1, Items::Air },
    };

    // salmon
    static const MobLootEntry k_salmon[] = {
        { Items::Salmon, 1, 1, Items::CookedSalmon },
    };

    // sheep
    static const MobLootEntry k_sheep[] = {
        { Items::Mutton, 1, 2, Items::CookedMutton },
    };

    // skeleton
    static const MobLootEntry k_skeleton[] = {
        { Items::Arrow, 0, 2, Items::Air },
        { Items::Bone, 0, 2, Items::Air },
    };

    // skeleton_horse
    static const MobLootEntry k_skeleton_horse[] = {
        { Items::Bone, 0, 2, Items::Air },
    };

    // snow_golem
    static const MobLootEntry k_snow_golem[] = {
        { Items::Snowball, 0, 15, Items::Air },
    };

    // spider
    static const MobLootEntry k_spider[] = {
        { Items::String, 0, 2, Items::Air },
    };

    // squid
    static const MobLootEntry k_squid[] = {
        { Items::InkSac, 1, 3, Items::Air },
    };

    // stray
    static const MobLootEntry k_stray[] = {
        { Items::Arrow, 0, 2, Items::Air },
        { Items::Bone, 0, 2, Items::Air },
    };

    // strider
    static const MobLootEntry k_strider[] = {
        { Items::String, 2, 5, Items::Air },
    };

    // trader_llama
    static const MobLootEntry k_trader_llama[] = {
        { Items::Leather, 0, 2, Items::Air },
    };

    // tropical_fish
    static const MobLootEntry k_tropical_fish[] = {
        { Items::TropicalFish, 1, 1, Items::Air },
    };

    // witch
    static const MobLootEntry k_witch[] = {
        { Items::GlowstoneDust, 0, 2, Items::Air },
        { Items::Sugar, 0, 2, Items::Air },
        { Items::SpiderEye, 0, 2, Items::Air },
        { Items::GlassBottle, 0, 2, Items::Air },
        { Items::Gunpowder, 0, 2, Items::Air },
        { Items::Stick, 0, 2, Items::Air },
        { Items::Redstone, 4, 8, Items::Air },
    };

    // wither_skeleton
    static const MobLootEntry k_wither_skeleton[] = {
        { Items::Coal, 0, 1, Items::Air },
        { Items::Bone, 0, 2, Items::Air },
    };

    // zoglin
    static const MobLootEntry k_zoglin[] = {
        { Items::RottenFlesh, 1, 3, Items::Air },
    };

    // zombie
    static const MobLootEntry k_zombie[] = {
        { Items::RottenFlesh, 0, 2, Items::Air },
    };

    // zombie_horse
    static const MobLootEntry k_zombie_horse[] = {
        { Items::RottenFlesh, 2, 3, Items::Air },
    };

    // zombie_villager
    static const MobLootEntry k_zombie_villager[] = {
        { Items::RottenFlesh, 0, 2, Items::Air },
    };

    // zombified_piglin
    static const MobLootEntry k_zombified_piglin[] = {
        { Items::RottenFlesh, 0, 1, Items::Air },
        { Items::GoldNugget, 0, 1, Items::Air },
    };

    const MobLootTable kMobLootTables[] = {
        { EntityTypeId::Allay, nullptr, 0 },
        { EntityTypeId::Armadillo, nullptr, 0 },
        { EntityTypeId::Axolotl, nullptr, 0 },
        { EntityTypeId::Bat, nullptr, 0 },
        { EntityTypeId::Bee, nullptr, 0 },
        { EntityTypeId::Blaze, nullptr, 0 },
        { EntityTypeId::Bogged, k_bogged, 2 },
        { EntityTypeId::Breeze, nullptr, 0 },
        { EntityTypeId::Camel, nullptr, 0 },
        { EntityTypeId::CamelHusk, k_camel_husk, 1 },
        { EntityTypeId::Cat, k_cat, 1 },
        { EntityTypeId::CaveSpider, k_cave_spider, 1 },
        { EntityTypeId::Chicken, k_chicken, 2 },
        { EntityTypeId::Cod, k_cod, 1 },
        { EntityTypeId::CopperGolem, k_copper_golem, 1 },
        { EntityTypeId::Cow, k_cow, 2 },
        { EntityTypeId::Creaking, nullptr, 0 },
        { EntityTypeId::Creeper, k_creeper, 1 },
        { EntityTypeId::Dolphin, k_dolphin, 1 },
        { EntityTypeId::Donkey, k_donkey, 1 },
        { EntityTypeId::Drowned, k_drowned, 1 },
        { EntityTypeId::ElderGuardian, k_elder_guardian, 4 },
        { EntityTypeId::EnderDragon, nullptr, 0 },
        { EntityTypeId::Enderman, k_enderman, 1 },
        { EntityTypeId::Endermite, nullptr, 0 },
        { EntityTypeId::Evoker, k_evoker, 1 },
        { EntityTypeId::Fox, nullptr, 0 },
        { EntityTypeId::Frog, nullptr, 0 },
        { EntityTypeId::Ghast, k_ghast, 2 },
        { EntityTypeId::Giant, nullptr, 0 },
        { EntityTypeId::GlowSquid, k_glow_squid, 1 },
        { EntityTypeId::Goat, nullptr, 0 },
        { EntityTypeId::Guardian, k_guardian, 3 },
        { EntityTypeId::HappyGhast, nullptr, 0 },
        { EntityTypeId::Hoglin, k_hoglin, 2 },
        { EntityTypeId::Horse, k_horse, 1 },
        { EntityTypeId::Husk, k_husk, 1 },
        { EntityTypeId::Illusioner, nullptr, 0 },
        { EntityTypeId::IronGolem, k_iron_golem, 1 },
        { EntityTypeId::Llama, k_llama, 1 },
        { EntityTypeId::MagmaCube, nullptr, 0 },
        { EntityTypeId::Mooshroom, k_mooshroom, 2 },
        { EntityTypeId::Mule, k_mule, 1 },
        { EntityTypeId::Nautilus, nullptr, 0 },
        { EntityTypeId::Ocelot, nullptr, 0 },
        { EntityTypeId::Panda, nullptr, 0 },
        { EntityTypeId::Parched, k_parched, 2 },
        { EntityTypeId::Parrot, k_parrot, 1 },
        { EntityTypeId::Phantom, nullptr, 0 },
        { EntityTypeId::Pig, k_pig, 1 },
        { EntityTypeId::Piglin, nullptr, 0 },
        { EntityTypeId::PiglinBrute, nullptr, 0 },
        { EntityTypeId::Pillager, nullptr, 0 },
        { EntityTypeId::PolarBear, k_polar_bear, 2 },
        { EntityTypeId::Pufferfish, k_pufferfish, 1 },
        { EntityTypeId::Rabbit, k_rabbit, 2 },
        { EntityTypeId::Ravager, k_ravager, 1 },
        { EntityTypeId::Salmon, k_salmon, 1 },
        { EntityTypeId::Sheep, k_sheep, 1 },
        { EntityTypeId::Shulker, nullptr, 0 },
        { EntityTypeId::Silverfish, nullptr, 0 },
        { EntityTypeId::Skeleton, k_skeleton, 2 },
        { EntityTypeId::SkeletonHorse, k_skeleton_horse, 1 },
        { EntityTypeId::Slime, nullptr, 0 },
        { EntityTypeId::Sniffer, nullptr, 0 },
        { EntityTypeId::SnowGolem, k_snow_golem, 1 },
        { EntityTypeId::Spider, k_spider, 1 },
        { EntityTypeId::Squid, k_squid, 1 },
        { EntityTypeId::Stray, k_stray, 2 },
        { EntityTypeId::Strider, k_strider, 1 },
        { EntityTypeId::Tadpole, nullptr, 0 },
        { EntityTypeId::TraderLlama, k_trader_llama, 1 },
        { EntityTypeId::TropicalFish, k_tropical_fish, 1 },
        { EntityTypeId::Turtle, nullptr, 0 },
        { EntityTypeId::Vex, nullptr, 0 },
        { EntityTypeId::Villager, nullptr, 0 },
        { EntityTypeId::Vindicator, nullptr, 0 },
        { EntityTypeId::WanderingTrader, nullptr, 0 },
        { EntityTypeId::Warden, nullptr, 0 },
        { EntityTypeId::Witch, k_witch, 7 },
        { EntityTypeId::Wither, nullptr, 0 },
        { EntityTypeId::WitherSkeleton, k_wither_skeleton, 2 },
        { EntityTypeId::Wolf, nullptr, 0 },
        { EntityTypeId::Zoglin, k_zoglin, 1 },
        { EntityTypeId::Zombie, k_zombie, 1 },
        { EntityTypeId::ZombieHorse, k_zombie_horse, 1 },
        { EntityTypeId::ZombieNautilus, nullptr, 0 },
        { EntityTypeId::ZombieVillager, k_zombie_villager, 1 },
        { EntityTypeId::ZombifiedPiglin, k_zombified_piglin, 2 },
    };

    const int kMobLootTableCount = 89;

    const MobLootTable* FindMobLootTable(EntityTypeId type) {
        for (int i = 0; i < kMobLootTableCount; ++i) {
            if (kMobLootTables[i].type == type) return &kMobLootTables[i];
        }
        return nullptr;
    }

} // namespace Game
