// File: src/common/world/loot/GeneratedMobLoot.hpp
// AUTO-GENERATED by tools/gen_mob_loot.py — DO NOT EDIT BY HAND.
//
// Death drops per mob, from data/minecraft/loot_table/entities/*.json, in
// MC's real pool structure: each pool rolls N times, and each roll picks ONE
// entry weighted by `weight` (an Items::Air row is MC's `minecraft:empty` —
// weight that drops nothing). MobManager::EvaluateLootTable, on the
// at-death drop path, is the evaluator.
#pragma once

#include "common/entity/EntityType.hpp"
#include "common/entity/Item.hpp"

namespace Game {

    struct MobLootEntry {
        ItemID item;      // Items::Air = MC's `minecraft:empty` alternative
        int    weight;    // relative pick weight within the pool (MC default 1)
        // Inclusive count range. minCount MAY BE NEGATIVE (MC's uniform(-1,1)
        // spider eye / uniform(-2,1) magma cream — "often nothing"): the
        // consumer clamps the SAMPLED value, never the range.
        int    minCount;
        int    maxCount;
        // The cooked form, dropped instead when the mob died on fire
        // (MC's furnace_smelt loot function). Air when the item has none.
        ItemID smeltedItem;
        // Slime-size gate (MC entity_properties type_specific slime), for the
        // magma cube's size>=2 cream entry. sizeMin 0 = ungated.
        int    sizeMin;
        int    sizeMax;
    };

    struct MobLootPool {
        // Roll count, inclusive (the witch's ingredient pool is uniform 1-3).
        int   minRolls;
        int   maxRolls;
        // minecraft:killed_by_player — only drops inside the mob's 100-tick
        // player-kill credit window (blaze rods, phantom membranes...).
        bool  requiresPlayerKill;
        // random_chance / random_chance_with_enchanted_bonus at looting 0.
        // 1.0f = unconditional.
        float chance;
        // Pool-level slime-size gate (the slime's size==1 slimeball pool).
        // sizeMin 0 = ungated.
        int   sizeMin;
        int   sizeMax;
        const MobLootEntry* entries;
        int   entryCount;
    };

    struct MobLootTable {
        EntityTypeId       type;
        const MobLootPool* pools;
        int                poolCount;
    };

    extern const MobLootTable kMobLootTables[];
    extern const int          kMobLootTableCount;

    const MobLootTable* FindMobLootTable(EntityTypeId type);

} // namespace Game
