// File: src/common/world/block/Blocks.hpp
#pragma once

namespace Game {

    // We'll use a uint16_t under the hood to match our palette/palette-index style.
    enum class BlockID : uint16_t {
        Air          = 0,
        Stone        = 1,
        Dirt         = 2,
        Grass        = 3,
        Sand         = 4,
        Sandstone    = 5,
        OakLog       = 6,
        Snow         = 7,
        SnowGrass    = 8,
        Ice          = 9,
        Glass        = 10,
        Bedrock      = 11,
        Water        = 12,
        OakLeaves    = 13,
        CherryLog    = 14,
        BirchLog     = 15,
        AcaciaLog    = 16,
        CherryLeaves = 17,
        CoalOre      = 18,
        RedstoneOre  = 19,
        LapisOre     = 20,
        IronOre      = 21,
        GoldOre      = 22,
        EmeraldOre   = 23,
        DiamondOre   = 24,
        Gravel       = 25,
        Mycelium     = 26,
        Deepslate    = 27,
        Lava         = 28,
        Diorite      = 29,
        Andesite     = 30,
        Granite      = 31,
        CopperOre    = 32,
        DeepslateLapisOre = 33,
        DeepslateIronOre = 34,
        DeepslateGoldOre = 35,
        DeepslateDiamondOre = 36,
        DeepslateCopperOre = 37,
        Tuff         = 38,
        ChiseledTuffBricks = 39,
        TuffBricks   = 40,
        WaxedCutCopper = 41,
        waxed_chiseled_copper = 42,
        Spawner      = 43,
        Cobblestone  = 44,
        MossyCobblestone = 45,
        polished_tuff = 46,
        waxed_oxidized_chiseled_copper = 47,
        deepslate_coal_ore = 48,
        BirchLeaves    = 49,
        SpruceLog      = 50,
        Clay           = 51,
        SmoothBasalt   = 52,
        AmethystBlock  = 53,
        MagmaBlock     = 54,
        RawIronBlock   = 55,
        Obsidian       = 56,
        OakPlanks      = 57,
        Pumpkin        = 58,
        WaxedCopperBulb = 59,
        WaxedOxidizedCopper = 60,
        WaxedOxidizedCutCopper = 61,
        WaxedCopperBlock = 62,
        WaxedExposedCopperBulb = 63,
        WaxedWeatheredCopperBulb = 64,
        WaxedOxidizedCopperBulb = 65,
        BeeNest        = 66,
        MossBlock      = 67,
        SpruceLeaves   = 68,
        DeepslateRedstoneOre = 69,
        JungleLog      = 70,
        DarkOakLog     = 71,
        JungleLeaves   = 72,
        DarkOakLeaves  = 73,
        AcaciaLeaves   = 74,
        DeepslateEmeraldOre = 75,
        PackedIce      = 76,
        RedMushroom    = 77,
        BrownMushroom  = 78,

        Count // Always keep this as the last entry.
    };

} // namespace Game