// GENERATED by tools/gen_block_hardness.py — DO NOT EDIT BY HAND.
//
// Per-block mining and blast data, transcribed from MC's Blocks.java rather
// than guessed from the block's name.
//
// This table replaced `ClassifyByName` + `ApplyExplicitHardnessOverrides` in
// BlockRegistry.cpp, which inferred hardness from substrings of a model name
// ("anything containing 'stone' is 1.5"). That was right often enough to look
// correct and wrong often enough to matter, and it had no answer at all for
// explosion resistance — which is the number an explosion's ray march spends.
//
// Keyed on the vanilla registry SLUG (column 2 of BlockDefs.inc), not the
// BlockID, so adding a block to BlockDefs.inc picks its real values up for
// free and reordering the enum cannot silently shuffle the table.
#pragma once

#include "common/entity/MiningTier.hpp"

#include <cstddef>
#include <cstdint>
#include <string_view>

namespace Game {

    struct GeneratedBlockHardnessRow {
        std::string_view slug;
        // MC Properties.destroyTime — seconds at base mining speed.
        // -1 is unbreakable (bedrock, barrier, the portal frames).
        float       destroyTime;
        // MC Properties.explosionResistance. `strength(a)` sets this to `a` as
        // well, so for most of the registry it equals destroyTime; the
        // exceptions are the blast-proof set (obsidian and the anvils at 1200,
        // bedrock at 3600000) and stone-family blocks, which are 1.5 to mine
        // and 6.0 to blow up.
        float       explosionResistance;
        bool        requiresCorrectTool;
        // 0xRRGGBB. MC's map colour, carried because ConcretePowderBlock and
        // AnvilBlock derive their FALLING DUST colour from it
        // (getDustColor -> state.getMapColor(...).col).
        uint32_t    mapColor;
        // MC Properties.ignitedByLava. The data half of fire spread, which
        // does not exist yet — carried now so that when FireBlock's tick lands
        // it does not also need a new generator run.
        bool        ignitedByLava;
        // From data/minecraft/tags/block/mineable/*.json — NOT from Blocks.java,
        // which does not know about tools at all.
        ToolType    preferredTool;
        // From data/minecraft/tags/block/needs_*_tool.json.
        MiningTier  minTier;
    };

    extern const GeneratedBlockHardnessRow kBlockHardnessTable[];
    extern const size_t                    kBlockHardnessCount;

    // Row for a registry slug, or null when the block is not in vanilla's
    // Blocks.java (this engine carries a handful that are not, and promoted
    // state variants share their base block's slug).
    const GeneratedBlockHardnessRow* FindBlockHardness(std::string_view slug);

} // namespace Game
