#pragma once
// Original eMinecraftColour enum extracted from Minecraft.Client/Common/App_enums.h.
enum eMinecraftColour
{
	eMinecraftColour_NOT_SET,

	eMinecraftColour_Foliage_Evergreen,
	eMinecraftColour_Foliage_Birch,
	eMinecraftColour_Foliage_Default,
	eMinecraftColour_Foliage_Common,
	eMinecraftColour_Foliage_Ocean,
	eMinecraftColour_Foliage_Plains,
	eMinecraftColour_Foliage_Desert,
	eMinecraftColour_Foliage_ExtremeHills,
	eMinecraftColour_Foliage_Forest,
	eMinecraftColour_Foliage_Taiga,
	eMinecraftColour_Foliage_Swampland,
	eMinecraftColour_Foliage_River,
	eMinecraftColour_Foliage_Hell,
	eMinecraftColour_Foliage_Sky,
	eMinecraftColour_Foliage_FrozenOcean,
	eMinecraftColour_Foliage_FrozenRiver,
	eMinecraftColour_Foliage_IcePlains,
	eMinecraftColour_Foliage_IceMountains,
	eMinecraftColour_Foliage_MushroomIsland,
	eMinecraftColour_Foliage_MushroomIslandShore,
	eMinecraftColour_Foliage_Beach,
	eMinecraftColour_Foliage_DesertHills,
	eMinecraftColour_Foliage_ForestHills,
	eMinecraftColour_Foliage_TaigaHills,
	eMinecraftColour_Foliage_ExtremeHillsEdge,
	eMinecraftColour_Foliage_Jungle,
	eMinecraftColour_Foliage_JungleHills,
	
	eMinecraftColour_Grass_Common,
	eMinecraftColour_Grass_Ocean,
	eMinecraftColour_Grass_Plains,
	eMinecraftColour_Grass_Desert,
	eMinecraftColour_Grass_ExtremeHills,
	eMinecraftColour_Grass_Forest,
	eMinecraftColour_Grass_Taiga,
	eMinecraftColour_Grass_Swampland,
	eMinecraftColour_Grass_River,
	eMinecraftColour_Grass_Hell,
	eMinecraftColour_Grass_Sky,
	eMinecraftColour_Grass_FrozenOcean,
	eMinecraftColour_Grass_FrozenRiver,
	eMinecraftColour_Grass_IcePlains,
	eMinecraftColour_Grass_IceMountains,
	eMinecraftColour_Grass_MushroomIsland,
	eMinecraftColour_Grass_MushroomIslandShore,
	eMinecraftColour_Grass_Beach,
	eMinecraftColour_Grass_DesertHills,
	eMinecraftColour_Grass_ForestHills,
	eMinecraftColour_Grass_TaigaHills,
	eMinecraftColour_Grass_ExtremeHillsEdge,
	eMinecraftColour_Grass_Jungle,
	eMinecraftColour_Grass_JungleHills,

	eMinecraftColour_Water_Ocean,
	eMinecraftColour_Water_Plains,
	eMinecraftColour_Water_Desert,
	eMinecraftColour_Water_ExtremeHills,
	eMinecraftColour_Water_Forest,
	eMinecraftColour_Water_Taiga,
	eMinecraftColour_Water_Swampland,
	eMinecraftColour_Water_River,
	eMinecraftColour_Water_Hell,
	eMinecraftColour_Water_Sky,
	eMinecraftColour_Water_FrozenOcean,
	eMinecraftColour_Water_FrozenRiver,
	eMinecraftColour_Water_IcePlains,
	eMinecraftColour_Water_IceMountains,
	eMinecraftColour_Water_MushroomIsland,
	eMinecraftColour_Water_MushroomIslandShore,
	eMinecraftColour_Water_Beach,
	eMinecraftColour_Water_DesertHills,
	eMinecraftColour_Water_ForestHills,
	eMinecraftColour_Water_TaigaHills,
	eMinecraftColour_Water_ExtremeHillsEdge,
	eMinecraftColour_Water_Jungle,
	eMinecraftColour_Water_JungleHills,

	eMinecraftColour_Sky_Ocean,
	eMinecraftColour_Sky_Plains,
	eMinecraftColour_Sky_Desert,
	eMinecraftColour_Sky_ExtremeHills,
	eMinecraftColour_Sky_Forest,
	eMinecraftColour_Sky_Taiga,
	eMinecraftColour_Sky_Swampland,
	eMinecraftColour_Sky_River,
	eMinecraftColour_Sky_Hell,
	eMinecraftColour_Sky_Sky,
	eMinecraftColour_Sky_FrozenOcean,
	eMinecraftColour_Sky_FrozenRiver,
	eMinecraftColour_Sky_IcePlains,
	eMinecraftColour_Sky_IceMountains,
	eMinecraftColour_Sky_MushroomIsland,
	eMinecraftColour_Sky_MushroomIslandShore,
	eMinecraftColour_Sky_Beach,
	eMinecraftColour_Sky_DesertHills,
	eMinecraftColour_Sky_ForestHills,
	eMinecraftColour_Sky_TaigaHills,
	eMinecraftColour_Sky_ExtremeHillsEdge,
	eMinecraftColour_Sky_Jungle,
	eMinecraftColour_Sky_JungleHills,

	eMinecraftColour_Tile_RedstoneDust,
	eMinecraftColour_Tile_RedstoneDustUnlit,
	eMinecraftColour_Tile_RedstoneDustLitMin,
	eMinecraftColour_Tile_RedstoneDustLitMax,
	eMinecraftColour_Tile_StemMin,
	eMinecraftColour_Tile_StemMax,
	eMinecraftColour_Tile_WaterLily,

	eMinecraftColour_Sky_Dawn_Dark,
	eMinecraftColour_Sky_Dawn_Bright,

	eMinecraftColour_Material_None,
	eMinecraftColour_Material_Grass,
	eMinecraftColour_Material_Sand,
	eMinecraftColour_Material_Cloth,
	eMinecraftColour_Material_Fire,
	eMinecraftColour_Material_Ice,
	eMinecraftColour_Material_Metal,
	eMinecraftColour_Material_Plant,
	eMinecraftColour_Material_Snow,
	eMinecraftColour_Material_Clay,
	eMinecraftColour_Material_Dirt,
	eMinecraftColour_Material_Stone,
	eMinecraftColour_Material_Water,
	eMinecraftColour_Material_Wood,
	eMinecraftColour_Material_Emerald,

	eMinecraftColour_Particle_Note_00,
	eMinecraftColour_Particle_Note_01,
	eMinecraftColour_Particle_Note_02,
	eMinecraftColour_Particle_Note_03,
	eMinecraftColour_Particle_Note_04,
	eMinecraftColour_Particle_Note_05,
	eMinecraftColour_Particle_Note_06,
	eMinecraftColour_Particle_Note_07,
	eMinecraftColour_Particle_Note_08,
	eMinecraftColour_Particle_Note_09,
	eMinecraftColour_Particle_Note_10,
	eMinecraftColour_Particle_Note_11,
	eMinecraftColour_Particle_Note_12,
	eMinecraftColour_Particle_Note_13,
	eMinecraftColour_Particle_Note_14,
	eMinecraftColour_Particle_Note_15,
	eMinecraftColour_Particle_Note_16,
	eMinecraftColour_Particle_Note_17,
	eMinecraftColour_Particle_Note_18,
	eMinecraftColour_Particle_Note_19,
	eMinecraftColour_Particle_Note_20,
	eMinecraftColour_Particle_Note_21,
	eMinecraftColour_Particle_Note_22,
	eMinecraftColour_Particle_Note_23,
	eMinecraftColour_Particle_Note_24,

	eMinecraftColour_Particle_NetherPortal,
	eMinecraftColour_Particle_EnderPortal,
	eMinecraftColour_Particle_Smoke,
	eMinecraftColour_Particle_Ender,
	eMinecraftColour_Particle_Explode,
	eMinecraftColour_Particle_HugeExplosion,
	eMinecraftColour_Particle_DripWater,
	eMinecraftColour_Particle_DripLavaStart,
	eMinecraftColour_Particle_DripLavaEnd,
	eMinecraftColour_Particle_EnchantmentTable,
	eMinecraftColour_Particle_DragonBreathMin,
	eMinecraftColour_Particle_DragonBreathMax,
	eMinecraftColour_Particle_Suspend,
	eMinecraftColour_Particle_CritStart,
	eMinecraftColour_Particle_CritEnd,

	eMinecraftColour_Effect_MovementSpeed,
	eMinecraftColour_Effect_MovementSlowDown,
	eMinecraftColour_Effect_DigSpeed,
	eMinecraftColour_Effect_DigSlowdown,
	eMinecraftColour_Effect_DamageBoost,
	eMinecraftColour_Effect_Heal,
	eMinecraftColour_Effect_Harm,
	eMinecraftColour_Effect_Jump,
	eMinecraftColour_Effect_Confusion,
	eMinecraftColour_Effect_Regeneration,
	eMinecraftColour_Effect_DamageResistance,
	eMinecraftColour_Effect_FireResistance,
	eMinecraftColour_Effect_WaterBreathing,
	eMinecraftColour_Effect_Invisiblity,
	eMinecraftColour_Effect_Blindness,
	eMinecraftColour_Effect_NightVision,
	eMinecraftColour_Effect_Hunger,
	eMinecraftColour_Effect_Weakness,
	eMinecraftColour_Effect_Poison,

	eMinecraftColour_Potion_BaseColour,

	eMinecraftColour_Mob_Creeper_Colour1,
	eMinecraftColour_Mob_Creeper_Colour2,
	eMinecraftColour_Mob_Skeleton_Colour1,
	eMinecraftColour_Mob_Skeleton_Colour2,
	eMinecraftColour_Mob_Spider_Colour1,
	eMinecraftColour_Mob_Spider_Colour2,
	eMinecraftColour_Mob_Zombie_Colour1,
	eMinecraftColour_Mob_Zombie_Colour2,
	eMinecraftColour_Mob_Slime_Colour1,
	eMinecraftColour_Mob_Slime_Colour2,
	eMinecraftColour_Mob_Ghast_Colour1,
	eMinecraftColour_Mob_Ghast_Colour2,
	eMinecraftColour_Mob_PigZombie_Colour1,
	eMinecraftColour_Mob_PigZombie_Colour2,
	eMinecraftColour_Mob_Enderman_Colour1,
	eMinecraftColour_Mob_Enderman_Colour2,
	eMinecraftColour_Mob_CaveSpider_Colour1,
	eMinecraftColour_Mob_CaveSpider_Colour2,
	eMinecraftColour_Mob_Silverfish_Colour1,
	eMinecraftColour_Mob_Silverfish_Colour2,
	eMinecraftColour_Mob_Blaze_Colour1,
	eMinecraftColour_Mob_Blaze_Colour2,
	eMinecraftColour_Mob_LavaSlime_Colour1,
	eMinecraftColour_Mob_LavaSlime_Colour2,
	eMinecraftColour_Mob_Pig_Colour1,
	eMinecraftColour_Mob_Pig_Colour2,
	eMinecraftColour_Mob_Sheep_Colour1,
	eMinecraftColour_Mob_Sheep_Colour2,
	eMinecraftColour_Mob_Cow_Colour1,
	eMinecraftColour_Mob_Cow_Colour2,
	eMinecraftColour_Mob_Chicken_Colour1,
	eMinecraftColour_Mob_Chicken_Colour2,
	eMinecraftColour_Mob_Squid_Colour1,
	eMinecraftColour_Mob_Squid_Colour2,
	eMinecraftColour_Mob_Wolf_Colour1,
	eMinecraftColour_Mob_Wolf_Colour2,
	eMinecraftColour_Mob_MushroomCow_Colour1,
	eMinecraftColour_Mob_MushroomCow_Colour2,
	eMinecraftColour_Mob_Ocelot_Colour1,
	eMinecraftColour_Mob_Ocelot_Colour2,
	eMinecraftColour_Mob_Villager_Colour1,
	eMinecraftColour_Mob_Villager_Colour2,

	eMinecraftColour_Armour_Default_Leather_Colour,

	eMinecraftColour_Under_Water_Clear_Colour,
	eMinecraftColour_Under_Lava_Clear_Colour,
	eMinecraftColour_In_Cloud_Base_Colour,

	eMinecraftColour_Under_Water_Fog_Colour,
	eMinecraftColour_Under_Lava_Fog_Colour,
	eMinecraftColour_In_Cloud_Fog_Colour,

	eMinecraftColour_Default_Fog_Colour,
	eMinecraftColour_Nether_Fog_Colour,
	eMinecraftColour_End_Fog_Colour,

	eMinecraftColour_Sign_Text,
	eMinecraftColour_Map_Text,

	eHTMLColor_0,
	eHTMLColor_1,
	eHTMLColor_2,
	eHTMLColor_3,
	eHTMLColor_4,
	eHTMLColor_5,
	eHTMLColor_6,
	eHTMLColor_7,
	eHTMLColor_8,
	eHTMLColor_9,
	eHTMLColor_a,
	eHTMLColor_b,
	eHTMLColor_c,
	eHTMLColor_d,
	eHTMLColor_e,
	eHTMLColor_f,
	eHTMLColor_0_dark,
	eHTMLColor_1_dark,
	eHTMLColor_2_dark,
	eHTMLColor_3_dark,
	eHTMLColor_4_dark,
	eHTMLColor_5_dark,
	eHTMLColor_6_dark,
	eHTMLColor_7_dark,
	eHTMLColor_8_dark,
	eHTMLColor_9_dark,
	eHTMLColor_a_dark,
	eHTMLColor_b_dark,
	eHTMLColor_c_dark,
	eHTMLColor_d_dark,
	eHTMLColor_e_dark,
	eHTMLColor_f_dark,
	eHTMLColor_T1,
	eHTMLColor_T2,
	eHTMLColor_T3,
	eHTMLColor_Black,
	eHTMLColor_White,

	eTextColor_Enchant,
	eTextColor_EnchantFocus,
	eTextColor_EnchantDisabled,
	eTextColor_RenamedItemTitle,

	//eHTMLColor_0 = 0x000000, //r:0 , g: 0, b: 0, i: 0
	//eHTMLColor_1 = 0x0000aa, //r:0 , g: 0, b: aa, i: 1
	//eHTMLColor_2 = 0x109e10, // Changed by request of Dave //0x00aa00, //r:0 , g: aa, b: 0, i: 2
	//eHTMLColor_3 = 0x109e9e, // Changed by request of Dave //0x00aaaa, //r:0 , g: aa, b: aa, i: 3
	//eHTMLColor_4 = 0xaa0000, //r:aa , g: 0, b: 0, i: 4
	//eHTMLColor_5 = 0xaa00aa, //r:aa , g: 0, b: aa, i: 5
	//eHTMLColor_6 = 0xffaa00, //r:ff , g: aa, b: 0, i: 6
	//eHTMLColor_7 = 0xaaaaaa, //r:aa , g: aa, b: aa, i: 7
	//eHTMLColor_8 = 0x555555, //r:55 , g: 55, b: 55, i: 8
	//eHTMLColor_9 = 0x5555ff, //r:55 , g: 55, b: ff, i: 9
	//eHTMLColor_a = 0x55ff55, //r:55 , g: ff, b: 55, i: a
	//eHTMLColor_b = 0x55ffff, //r:55 , g: ff, b: ff, i: b
	//eHTMLColor_c = 0xff5555, //r:ff , g: 55, b: 55, i: c
	//eHTMLColor_d = 0xff55ff, //r:ff , g: 55, b: ff, i: d
	//eHTMLColor_e = 0xffff55, //r:ff , g: ff, b: 55, i: e
	//eHTMLColor_f = 0xffffff, //r:ff , g: ff, b: ff, i: f
	//eHTMLColor_0_dark = 0x000000, //r:0 , g: 0, b: 0, i: 10
	//eHTMLColor_1_dark = 0x00002a, //r:0 , g: 0, b: 2a, i: 11
	//eHTMLColor_2_dark = 0x002a00, //r:0 , g: 2a, b: 0, i: 12
	//eHTMLColor_3_dark = 0x002a2a, //r:0 , g: 2a, b: 2a, i: 13
	//eHTMLColor_4_dark = 0x2a0000, //r:2a , g: 0, b: 0, i: 14
	//eHTMLColor_5_dark = 0x2a002a, //r:2a , g: 0, b: 2a, i: 15
	//eHTMLColor_6_dark = 0x2a2a00, //r:2a , g: 2a, b: 0, i: 16
	//eHTMLColor_7_dark = 0x2a2a2a, //r:2a , g: 2a, b: 2a, i: 17
	//eHTMLColor_8_dark = 0x151515, //r:15 , g: 15, b: 15, i: 18
	//eHTMLColor_9_dark = 0x15153f, //r:15 , g: 15, b: 3f, i: 19
	//eHTMLColor_a_dark = 0x153f15, //r:15 , g: 3f, b: 15, i: 1a
	//eHTMLColor_b_dark = 0x153f3f, //r:15 , g: 3f, b: 3f, i: 1b
	//eHTMLColor_c_dark = 0x3f1515, //r:3f , g: 15, b: 15, i: 1c
	//eHTMLColor_d_dark = 0x3f153f, //r:3f , g: 15, b: 3f, i: 1d
	//eHTMLColor_e_dark = 0x3f3f15, //r:3f , g: 3f, b: 15, i: 1e
	//eHTMLColor_f_dark = 0x3f3f3f, //r:3f , g: 3f, b: 3f, i: 1f

	eMinecraftColour_COUNT,
};
