// GENERATED by tools/gen_entity_animations.py — do not edit by hand.
//
// MC's AnimationDefinitions, flattened. See the generator's docstring for why
// these exist at all: modern mobs animate from keyframes, not from setupAnim's
// limb swing, so without them a frog or a camel simply stands still while it
// walks.
//
// The vectors are already in MC's STORED form — posVec has negated Y, degreeVec
// is radians, scaleVec is the delta from 1 — exactly as KeyframeAnimations
// produces them, so the runtime adds them straight onto the part.
#pragma once

#include <string_view>

namespace Render {

    enum class AnimTarget : uint8_t { Position, Rotation, Scale };
    enum class AnimInterp : uint8_t { Linear, CatmullRom };

    struct GenAnimKey {
        float t;              // timestamp, seconds
        float x, y, z;
        AnimInterp interp;
    };

    struct GenAnimChannel {
        std::string_view part;
        AnimTarget target;
        int firstKey, keyCount;
    };

    struct GenAnim {
        std::string_view name;   // e.g. "FrogAnimation.FROG_WALK"
        float length;            // seconds
        bool  looping;
        int   firstChannel, channelCount;
    };

    inline constexpr int kGenAnimCount = 51;
    extern const GenAnim        kGenAnims[kGenAnimCount];
    extern const GenAnimChannel kGenAnimChannels[];
    extern const GenAnimKey     kGenAnimKeys[];

    const GenAnim* FindGenAnim(std::string_view name);

} // namespace Render
