// GENERATED by tools/gen_entity_models.py — do not edit by hand.
//
// Mesh data for every mob without a hand-written model class: the part
// hierarchy, each part's rest pose, and its cubes, straight out of MC's
// `createBodyLayer`. Coordinates are MC MODEL SPACE — pixels, Y DOWN — so they
// match the decompile line for line and Render::ModelPart consumes them as-is.
//
// setupAnim is deliberately NOT here; see the generator's docstring.
#pragma once

#include <cstdint>
#include <string_view>

namespace Render {

    struct GenCube {
        float ox, oy, oz;      // origin, pixels
        float sx, sy, sz;      // size, pixels
        float tu, tv;          // texOffs
        float grow;            // CubeDeformation
        bool  mirror;
    };

    struct GenPart {
        std::string_view name;
        int   parent;          // index into the model's part span, -1 = root
        float x, y, z;         // PartPose offset, pixels
        float xRot, yRot, zRot;
        int   firstCube, cubeCount;
        bool  visible;         // false = MC hides it in the default state
    };

    // A boolean on the render state that gates a clip. Only five conditions
    // appear across all of MC's animated models, so this is a closed enum
    // rather than a compiled expression — an unrecognised one fails the build.
    enum class AnimGuard : uint8_t { None, IsInWater, IsSearching, CanMove, IsResting, IsHoldingItem };

    // One KeyframeAnimation application from a model's setupAnim.
    struct GenClip {
        std::string_view anim;      // row in kGenAnims
        bool  isWalk;               // applyWalk (distance-driven) vs apply (timed)

        // applyWalk: MC's speed/scale factors, plus NautilusModel's two
        // argument tweaks (every other model passes the raw walk values).
        float speedFactor, scaleFactor;
        float posAgeScale, speedBias;

        // apply(AnimationState): which Game::MobAnim timer drives it. The
        // ordinal is Game::MobAnim's; the client stores the timers on the mob.
        uint8_t animSlot;

        AnimGuard guard;
        bool      guardNegate;
    };

    // MC `this.<part>.visible = state.<X>AnimationState.isStarted()` — the
    // frog's croaking throat sac. The part only exists while the clip runs.
    struct GenClipVisibility {
        std::string_view part;
        uint8_t          animSlot;
    };

    struct GenModel {
        std::string_view slug;
        float texWidth, texHeight;

        // The part MC's setupAnim turns with the look direction, or "" when it
        // turns none. Not always literally "head".
        std::string_view headPart;
        // BatModel turns its head only while resting; everything else is
        // unconditional.
        AnimGuard headGuard;
        bool      headGuardNegate;

        int   firstPart, partCount;
        int   firstClip, clipCount;
        int   firstVis,  visCount;
    };

    inline constexpr int kGenModelCount = 81;
    extern const GenModel kGenModels[kGenModelCount];
    extern const GenPart  kGenParts[];
    extern const GenCube  kGenCubes[];
    extern const GenClip  kGenClips[];
    extern const GenClipVisibility kGenClipVis[];

    // Mesh for a mob slug, or nullptr when it has a hand-written model class
    // (or none at all). Linear over ~81 entries, called once per type.
    const GenModel* FindGenModel(std::string_view slug);

} // namespace Render
