// File: src/common/world/crafting/GeneratedRecipeList.hpp
// AUTO-GENERATED by tools/gen_recipes.py — DO NOT EDIT BY HAND.
// Source: data/minecraft/recipe/*.json + data/minecraft/tags/item/*.json
// (the vendored vanilla data pack). Re-run the generator after bumping the MC
// snapshot; see CLAUDE.md, "Updating to a Newer Minecraft Version".
#pragma once

#include <cstddef>
#include <cstdint>

namespace Game {

    // One ingredient = the set of item slugs that satisfy it, stored as a
    // [begin, count) window into kRecipeIngredientSlugs. Tag references
    // (#minecraft:planks) are already flattened, and identical sets are
    // interned, so the 12-slug "planks" set exists exactly once.
    struct RecipeIngredientRow {
        uint32_t begin;
        uint16_t count;
    };

    // Recipe kinds, matching the vanilla `type` field.
    enum class RecipeKind : uint8_t {
        Shaped    = 0,   // width x height grid of cells; -1 cell = must be empty
        Shapeless = 1,   // unordered ingredient list
        // input + material; the result copies the INPUT stack's components
        // (ingredient 0 is the donor). Vanilla bundle / shulker-box dyeing.
        Transmute = 2,
    };

    struct RecipeRow {
        const char* id;            // "minecraft:stick" — identity for logs
        const char* resultSlug;
        uint8_t     resultCount;
        uint8_t     kind;          // RecipeKind
        uint8_t     width;         // 0 for the unordered kinds
        uint8_t     height;        // 0 for the unordered kinds
        uint32_t    cellBegin;     // window into kRecipeCells
        uint8_t     cellCount;     // width*height (shaped) or ingredient count
    };

    // Ingredient index per cell; -1 means "this cell must be empty" (shaped
    // patterns only — the unordered kinds never store one).
    extern const int32_t             kRecipeCells[];
    extern const char* const         kRecipeIngredientSlugs[];
    extern const RecipeIngredientRow kRecipeIngredients[];
    extern const size_t              kRecipeIngredientCount;
    extern const RecipeRow           kRecipeTable[];
    extern const size_t              kRecipeTableSize;

} // namespace Game
