#!/usr/bin/env python3
"""Adapt the console piston facing rule used by TreeTile::setPlacedBy."""
from pathlib import Path
import sys
r=Path(__file__).resolve().parents[1]
def body(file,signature):
 s=(r/'original/reference-only'/file).read_text();a=s.index('{',s.index(signature));b=a+1;depth=1
 while depth:
  depth+=(s[b]=='{')-(s[b]=='}');b+=1
 return s[a:b]
facing=body('PistonBaseTile.cpp','int PistonBaseTile::getNewFacing(')
log=body('TreeTile.cpp','void TreeTile::setPlacedBy(').replace('level->getData(x, y, z)','data').replace('int dir = PistonBaseTile::getNewFacing(level, x, y, z, dynamic_pointer_cast<Player>(by));','').replace('level->setData(x, y, z, type | facing);','return type | facing;')
out='''// Generated by tools/extract_block_placement.py from original placement bodies.
#include "BlockPlacement.h"
#include "Mth.h"
#include "Facing.h"
#include <cmath>
#include <stdexcept>
namespace console {
namespace {
struct PlacementPlayer {double x,y,z;float heightOffset,yRot;};
int originalFacing(int x,int y,int z,const PlacementPlayer* player)
'''+facing+'''
}
int consoleLogPlacementData(int data,int dir){
 if(data<0 || data>15 || dir<0 || dir>5)throw std::invalid_argument("Invalid log placement metadata or facing");
 constexpr int MASK_TYPE=3,FACING_Y=0,FACING_X=4,FACING_Z=8;
'''+log[1:]+'''
int consolePlacementFacing(int x,int y,int z,Vec3 feet,double yaw){
 if(!std::isfinite(feet.x) || !std::isfinite(feet.y) || !std::isfinite(feet.z) ||
    !std::isfinite(yaw) || std::abs(feet.x)>30000000 || std::abs(feet.z)>30000000 || std::abs(feet.y)>30000000 ||
    x<-30000000 || x>30000000 || z<-30000000 || z>30000000 || y<-30000000 || y>30000000)
  throw std::invalid_argument("Invalid placement coordinates");
 constexpr double pi=3.14159265358979323846;
 // Native camera faces -Z at zero; the original player faces +Z at zero.
 const float degrees=static_cast<float>(std::remainder(yaw,2*pi)*180/pi+180);
 constexpr float heightOffset=1.62f;
 PlacementPlayer player{feet.x,feet.y+heightOffset,feet.z,heightOffset,degrees};
 return originalFacing(x,y,z,&player);
}
}
'''
Path(sys.argv[1]).write_text(out)
