#!/usr/bin/env python3
"""Adapt original tile texture selectors and resolve original atlas registrations."""
from pathlib import Path
import re,sys
root=Path(__file__).resolve().parents[1]
ref=root/'original/reference-only'
atlas=dict((name,int(x)+16*int(y)) for name,x,y in re.findall(r'new SimpleIcon\(L"([^"]+)",slotSize\*(\d+),slotSize\*(\d+),',(ref/'PreStitchedTextureMap.cpp').read_text()))
def tiles(names):return '{'+','.join(str(atlas[n]) for n in names)+'}'
def names(file,array):return re.findall(r'L"([^"]+)"',re.search(array+r'\[\]\s*=\s*\{([^}]+)',(ref/file).read_text())[1])
def body(cls):
 s=(ref/(cls+'.cpp')).read_text();a=s.index('{',s.index('Icon *'+cls+'::getTexture(int face, int data)'));depth=1;b=a+1
 while depth:
  depth+=(s[b]=='{')-(s[b]=='}');b+=1
 return s[a:b]
out='''// Generated by tools/extract_block_textures.py from original getTexture methods.
#include "World.h"
#include <stdexcept>
namespace console {
namespace {
// Host mesh face order, mapped to original named directions.
struct Facing {enum {UP=0,DOWN=1,WEST=2,EAST=3,NORTH=4,SOUTH=5};};
'''
configs=[('TreeTile','constexpr int MASK_FACING=12,MASK_TYPE=3,FACING_Y=0,FACING_X=4,FACING_Z=8;\nconstexpr int iconTop='+str(atlas['tree_top'])+';\nconstexpr int icons[]='+tiles(names('TreeTile.cpp','TREE_TEXTURES'))+';'),('WoodTile','constexpr int WOOD_NAMES_LENGTH=4;\nconstexpr int icons[]='+tiles(names('WoodTile.cpp','TEXTURE_NAMES'))+';'),('SandStoneTile','constexpr int TYPE_HEIROGLYPHS=1,TYPE_SMOOTHSIDE=2,SANDSTONE_TILE_TEXTURE_COUNT=3;\nconstexpr int iconTop='+str(atlas['sandstone_top'])+',iconBottom='+str(atlas['sandstone_bottom'])+';\nconstexpr int icons[]='+tiles(names('SandStoneTile.cpp','TEXTURE_NAMES'))+';'),('ClothTile','constexpr int icons[]='+tiles(['cloth_'+str(i) for i in range(16)])+';'),('LeafTile','constexpr int LEAF_TYPE_MASK=3,EVERGREEN_LEAF=1,JUNGLE_LEAF=3,fancyTextureSet=0;\nconstexpr int icons[2][4]={'+tiles(['leaves','leaves_spruce','leaves','leaves_jungle'])+','+tiles(['leaves_opaque','leaves_spruce_opaque','leaves_opaque','leaves_jungle_opaque'])+'};')]
configs.append(('SmoothStoneBrickTile','constexpr int SMOOTH_STONE_BRICK_NAMES_LENGTH=4;\nconstexpr int icons[]='+tiles(names('SmoothStoneBrickTile.cpp','TEXTURE_NAMES'))+';'))
for cls,constants in configs:out+='int '+cls+'Texture(int face,int data) {\n'+constants+'\n'+body(cls)[1:]+'\n'
out+='''}
int variantTextureTile(Block block,int face,int data){
 if(face<0 || face>5 || data<0 || data>15)throw std::invalid_argument("Invalid block texture face or metadata");
 switch(block){
 case static_cast<Block>(98):return SmoothStoneBrickTileTexture(face,data);
 case Log:return TreeTileTexture(face,data);
 case Planks:return WoodTileTexture(face,data);
 case Leaves:return LeafTileTexture(face,data);
 case Sandstone:return SandStoneTileTexture(face,data);
 case Wool:return ClothTileTexture(face,data);
 default:return -1;
 }
}
}
'''
Path(sys.argv[1]).write_text(out)
