#!/usr/bin/env python3
"""Extract original StairTile shape bodies with a read-only level adapter."""
from pathlib import Path
import sys
root=Path(__file__).resolve().parents[1]
source=(root/'original/reference-only/StairTile.cpp').read_text()
def body(signature):
    start=source.index('{',source.index(signature)); end=start+1; depth=1
    while depth:
        depth+=(source[end]=='{')-(source[end]=='}'); end+=1
    return source[start:end]
out='''// Generated by tools/extract_stair_shape.py from StairTile.cpp.
#include "BlockShape.h"
#include "DoorShape.h"
#include "LadderShape.h"
#include "FenceShape.h"
namespace console {
bool consoleIsStair(int id) {
    // Original Tile::staticCtor stair registrations, replacing RTTI registry lookup.
    switch(id){case 53:case 67:case 108:case 109:case 114:case 128:
        case 134:case 135:case 136:case 156:return true;default:return false;}
}
namespace {
using LevelSource=const BlockShapeAccess;
struct StairTile {
    static constexpr int UPSIDEDOWN_BIT=4,DIR_EAST=0,DIR_WEST=1,DIR_SOUTH=2,DIR_NORTH=3;
    BlockBox box{};
    void setShape(double x0,double y0,double z0,double x1,double y1,double z1){box={x0,y0,z0,x1,y1,z1};}
    static bool isStairs(int id){return consoleIsStair(id);}
    void setBaseShape(LevelSource*,int,int,int);
    bool isLockAttached(LevelSource*,int,int,int,int);
    bool setStepShape(LevelSource*,int,int,int);
    bool setInnerPieceShape(LevelSource*,int,int,int);
};
'''
for signature in ['void StairTile::setBaseShape(LevelSource *level, int x, int y, int z)',
                  'bool StairTile::isLockAttached(LevelSource *level, int x, int y, int z, int data)',
                  'bool StairTile::setStepShape(LevelSource *level, int x, int y, int z)',
                  'bool StairTile::setInnerPieceShape(LevelSource *level, int x, int y, int z)']:
    out+=signature+'\n'+body(signature)+'\n'
out+='''}
BlockShape consoleStairShape(const BlockShapeAccess& level,int x,int y,int z){
    StairTile stair;BlockShape result;
    // StairTile::addAABBs order, without pooled mutable AABB ownership.
    stair.setBaseShape(&level,x,y,z);result.boxes[result.count++]=stair.box;
    bool checkInner=stair.setStepShape(&level,x,y,z);result.boxes[result.count++]=stair.box;
    if(checkInner && stair.setInnerPieceShape(&level,x,y,z))result.boxes[result.count++]=stair.box;
    return result;
}
}
'''
# HalfSlabTile::updateShape, replacing mutable tile shape storage with a box.
slab=(root/'original/reference-only/HalfSlabTile.cpp').read_text()
a=slab.index('{',slab.index('void HalfSlabTile::updateShape('));b=a+1;depth=1
while depth:
    depth+=(slab[b]=='{')-(slab[b]=='}');b+=1
shape=slab[a:b].replace('setShape(', 'setBox(')
out=out[:-2]+'''
bool consoleIsPartialBlock(int id){return consoleIsStair(id) || id==44 || id==64 || id==71 || id==65 || id==54 || consoleIsFenceLike(id);}
BlockShape consoleCollisionShape(const BlockShapeAccess& access,int x,int y,int z){
 if(consoleIsFenceLike(access.getTile(x,y,z)))return consoleFenceCollisionShape(access,x,y,z);
 if(access.getTile(x,y,z)==65)return consoleLadderShape(access.getData(x,y,z));
 if(access.getTile(x,y,z)==64 || access.getTile(x,y,z)==71)return consoleDoorShape(access,x,y,z);
 if(consoleIsStair(access.getTile(x,y,z)))return consoleStairShape(access,x,y,z);
 BlockShape result;result.count=1;
 auto setBox=[&](double x0,double y0,double z0,double x1,double y1,double z1){result.boxes[0]={x0,y0,z0,x1,y1,z1};};
 const bool fullSize=access.getTile(x,y,z)!=44;
 constexpr int TOP_SLOT_BIT=8;
 const auto* level=&access;
'''+shape+'''
 return result;
}
BlockShape consoleRenderShape(const BlockShapeAccess& access,int x,int y,int z){
 if(consoleIsFenceLike(access.getTile(x,y,z)))return consoleFenceRenderShape(access,x,y,z);
 return consoleCollisionShape(access,x,y,z);
}
}
'''
chest=(root/'original/reference-only/ChestTile.cpp').read_text()
a=chest.index('{',chest.index('void ChestTile::updateShape('));b=a+1;depth=1
while depth:
 depth+=(chest[b]=='{')-(chest[b]=='}');b+=1
chest_body=chest[a:b]
helper='''
BlockShape chestShape(const BlockShapeAccess& access,int x,int y,int z){
 const auto* level=&access;constexpr int id=54;BlockShape result;result.count=1;
 auto setShape=[&](double x0,double y0,double z0,double x1,double y1,double z1){result.boxes[0]={x0,y0,z0,x1,y1,z1};};
'''+chest_body+'''
 return result;
}
'''
out=out.replace('bool consoleIsPartialBlock(int id)',helper+'bool consoleIsPartialBlock(int id)')
out=out.replace(' if(access.getTile(x,y,z)==65)', ' if(access.getTile(x,y,z)==54)return chestShape(access,x,y,z);\n if(access.getTile(x,y,z)==65)')
Path(sys.argv[1]).write_text(out)
