#!/usr/bin/env python3
"""Generate the console string table from the PS3 string IDs and strings.resx.

* IDs: source_full/Minecraft.Client/PS3Media/strings.h (#define IDS_NAME n), the
  numbering app.GetString(IDS_...) indexes on PS3.
* Text: original/reference-only/strings.resx (English), exactly as stored,
  including the {*...*} formatting tokens that CMinecraftApp::FormatHTMLString
  and the tutorial popup expand at display time.

A handful of IDs are 4J platform-library strings that are not in strings.resx
(OK, Cancel, Yes, No, Back, the seed label). SUPPLEMENT lists the plain English
word shown for them; every other ID absent from strings.resx stays empty.
"""
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
IDS = ROOT / 'source_full/Minecraft.Client/PS3Media/strings.h'
RESX = ROOT / 'original/reference-only/strings.resx'

SUPPLEMENT = {
    'IDS_OK': 'OK',
    'IDS_CANCEL': 'Cancel',
    'IDS_YES': 'Yes',
    'IDS_NO': 'No',
    'IDS_BACK': 'Back',
    'IDS_GAMEOPTION_SEED': 'Seed',
}

ids = {m[1]: int(m[2]) for m in re.finditer(r'#define\s+(IDS_\w+)\s+(\d+)', IDS.read_text())}
count = max(ids.values()) + 1
if sorted(ids.values()) != list(range(count)):
    raise SystemExit('PS3 string IDs are not dense')
text = {}
for data in ET.parse(RESX).getroot().findall('data'):
    value = data.find('value')
    if value is not None:
        text[data.attrib['name']] = ''.join(value.itertext())
for name, value in SUPPLEMENT.items():
    if name in text:
        raise SystemExit(f'{name} is in strings.resx; drop it from SUPPLEMENT')
    text[name] = value


def literal(s: str) -> str:
    out = ['"']
    for ch in s.encode('utf-8'):
        c = chr(ch)
        if c == '"' or c == '\\':
            out.append('\\' + c)
        elif c == '\n':
            out.append('\\n')
        elif c == '\r':
            out.append('\\r')
        elif c == '\t':
            out.append('\\t')
        elif 32 <= ch < 127:
            out.append(c)
        else:
            # Octal escapes cannot swallow following hex digits.
            out.append('\\%03o' % ch)
    out.append('"')
    return ''.join(out)


by_id = sorted(ids.items(), key=lambda item: item[1])
missing = [name for name, _ in by_id if name not in text]
out = ['// Generated by tools/extract_strings.py from PS3Media/strings.h and strings.resx.',
       '// Do not edit by hand.',
       '#include "ConsoleStrings.h"',
       '#include <algorithm>',
       '#include <cstring>',
       'namespace console {',
       'namespace {',
       f'constexpr int kCount={count};',
       'struct Entry{const char* name;const char* text;};',
       'constexpr Entry kStrings[kCount]{']
for name, index in by_id:
    out.append(f' {{"{name}",{literal(text.get(name, ""))}}}, // {index}')
out += ['};',
        '}',
        'int consoleStringCount(){return kCount;}',
        'const char* consoleString(int id){return id>=0 && id<kCount?kStrings[id].text:"";}',
        'const char* consoleStringName(int id){return id>=0 && id<kCount?kStrings[id].name:"";}',
        'int consoleStringId(std::string_view name){',
        ' for(int i=0;i<kCount;++i)if(name==kStrings[i].name)return i;',
        ' return -1;',
        '}',
        '}',
        '']
args = [a for a in sys.argv[1:] if a != '--check']
target = Path(args[0]) if args else ROOT / 'ported/ConsoleStrings.cpp'
if '--check' in sys.argv:
    if not target.exists() or target.read_text() != '\n'.join(out):
        raise SystemExit(f'{target} is stale; rerun {Path(__file__).name}')
else:
    target.write_text('\n'.join(out))
print(f'{count} strings, {len(missing)} without text')
