#!/usr/bin/env python3
"""Extract TileRenderer::tesselateFireInWorld: ported/FireRender.cpp.

Copies the method unchanged from source_full/Minecraft.Client/TileRenderer.cpp
into a file that compiles against src/FireRender.h (namespace
console::fire_render), whose Tesselator collects the quads for the terrain
mesh.

Run with --check to fail when the generated file differs from the source.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'source_full/Minecraft.Client/TileRenderer.cpp'
OUT = ROOT / 'ported/FireRender.cpp'


def method(text, name):
    matches = list(re.finditer(re.escape(name) + r'\s*\(', text))
    if len(matches) != 1:
        raise SystemExit(f'{name}: {len(matches)} definitions')
    start = text.rindex('\n', 0, matches[0].start()) + 1
    opening = text.index('{', matches[0].end())
    depth, end = 0, opening
    while True:
        depth += (text[end] == '{') - (text[end] == '}')
        end += 1
        if depth == 0:
            return text[start:end]


def expected():
    text = SRC.read_text(encoding='utf-8-sig', errors='strict').replace('\r\n', '\n')
    return ('// Generated by tools/extract_fire_render.py: TileRenderer::tesselateFireInWorld,\n'
            '// copied unchanged from source_full/Minecraft.Client/TileRenderer.cpp. Do not edit by hand.\n'
            '#include "FireRender.h"\n\nnamespace console::fire_render {\n\n'
            + method(text, 'TileRenderer::tesselateFireInWorld') + '\n\n}\n')


def main():
    text = expected()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit('ported/FireRender.cpp is out of date: run tools/extract_fire_render.py')
        print('ported/FireRender.cpp matches the source')
    else:
        OUT.write_text(text)
        print('extracted ported/FireRender.cpp')


if __name__ == '__main__':
    main()
