#!/usr/bin/env python3
"""Extract the original random tile tick rules: ported/tick/TileTickRules.cpp.

Also the useOn of the farming items (hoes, seeds, bone meal, cocoa beans).

Copies each listed method unchanged from source_full/Minecraft.World into one
file that compiles against ported/tick/TileTickHost.h (namespace console::sim),
and writes the Tile::*_Id constants to ported/tick/TileIds.inc.

Run with --check to fail when the generated files differ from the source.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'source_full/Minecraft.World'
OUT = ROOT / 'ported/tick'
FILES = {p.name.lower(): p for p in SRC.iterdir()}

# (class, method) in the order they are written. A method may carry its full
# parameter list where the class overloads it.
METHODS = [
    ('Tile', 'mayPlace(Level *level, int x, int y, int z)'),
    ('Bush', 'mayPlaceOn'), ('Bush', 'tick'), ('Bush', 'checkAlive'), ('Bush', 'canSurvive'),
    ('DeadBushTile', 'mayPlaceOn'),
    ('WaterlilyTile', 'mayPlaceOn'), ('WaterlilyTile', 'canSurvive'),
    ('Sapling', 'tick'), ('Sapling', 'isSapling'),
    ('CropTile', 'mayPlaceOn'), ('CropTile', 'tick'), ('CropTile', 'getGrowthSpeed'),
    ('StemTile', 'mayPlaceOn'), ('StemTile', 'tick'), ('StemTile', 'getGrowthSpeed'),
    ('Mushroom', 'tick'), ('Mushroom', 'mayPlaceOn'), ('Mushroom', 'canSurvive'),
    ('NetherStalkTile', 'mayPlaceOn'), ('NetherStalkTile', 'canSurvive'), ('NetherStalkTile', 'tick'),
    ('GrassTile', 'tick'), ('GrassTile', 'shouldTileTick'),
    ('MycelTile', 'tick'),
    ('FarmTile', 'tick'), ('FarmTile', 'isUnderCrops'), ('FarmTile', 'isNearWater'),
    ('ReedTile', 'tick'), ('ReedTile', 'mayPlace'), ('ReedTile', 'canSurvive'), ('ReedTile', 'shouldTileTick'),
    ('CactusTile', 'tick'), ('CactusTile', 'canSurvive'), ('CactusTile', 'shouldTileTick'),
    ('DirectionalTile', 'getDirection'),
    ('CocoaTile', 'canSurvive'), ('CocoaTile', 'tick'), ('CocoaTile', 'getAge'),
    ('TreeTile', 'onRemove'), ('TreeTile', 'getWoodType'),
    ('LeafTile', 'onRemove'), ('LeafTile', 'tick'), ('LeafTile', 'die'), ('LeafTile', 'shouldTileTick'),
    ('VineTile', 'tick'), ('VineTile', 'isAcceptableNeighbor'),
    ('IceTile', 'tick'), ('IceTile', 'shouldTileTick'),
    ('TopSnowTile', 'tick'), ('TopSnowTile', 'shouldTileTick'),
    ('SnowTile', 'tick'), ('SnowTile', 'shouldTileTick'),
    ('RedStoneOreTile', 'tick'), ('RedStoneOreTile', 'shouldTileTick'),
    ('CauldronTile', 'handleRain'),
    ('CropTile', 'growCropsToMax'), ('StemTile', 'growCropsToMax'),
    ('CocoaTile', 'getPlacedOnFaceDataValue'),
    ('HoeItem', 'useOn'), ('SeedItem', 'useOn'), ('SeedFoodItem', 'useOn'), ('DyePowderItem', 'useOn'),
]
# The class's source file where it differs from the class name.
SOURCE_FILE = {'WaterlilyTile': 'WaterLilyTile.cpp'}


def source(cls):
    path = FILES[SOURCE_FILE.get(cls, cls + '.cpp').lower()]
    return path.read_text(encoding='utf-8-sig', errors='strict').replace('\r\n', '\n')


def method(cls, name):
    text = source(cls)
    pattern = re.escape(f'{cls}::{name}') + ('' if '(' in name else r'\s*\(')
    matches = [m for m in re.finditer(pattern, text)]
    if len(matches) != 1:
        raise SystemExit(f'{cls}::{name}: {len(matches)} definitions')
    start = text.rindex('\n', 0, matches[0].start()) + 1
    opening = text.index('{', matches[0].end())
    depth, end = 0, opening
    while True:
        depth += (text[end] == '{') - (text[end] == '}')
        end += 1
        if depth == 0:
            return text[start:end]


def expected():
    out = ['// Generated by tools/extract_tile_ticks.py: original tile tick methods,',
           '// copied unchanged from source_full/Minecraft.World. Do not edit by hand.',
           '#include "TileTickHost.h"', '', 'namespace console::sim {', '']
    for cls, name in METHODS:
        out.append(f'// {SOURCE_FILE.get(cls, cls + ".cpp")}')
        out.append(method(cls, name))
        out.append('')
    out.append('}')
    rules = '\n'.join(out) + '\n'
    tile_h = re.sub(r'//[^\n]*', '', FILES['tile.h'].read_text(encoding='utf-8-sig'))
    ids = ''.join(f'static const int {m[1]}_Id = {m[2]};\n'
                  for m in re.finditer(r'static const int (\w+)_Id\s*=\s*(\d+)', tile_h))
    return {'TileTickRules.cpp': rules, 'TileIds.inc': ids}


def main():
    stale = []
    for name, text in expected().items():
        target = OUT / name
        if '--check' in sys.argv:
            if not target.exists() or target.read_text() != text:
                stale.append(name)
        else:
            target.write_text(text)
    if stale:
        sys.exit('ported/tick is out of date (' + ', '.join(stale) + '): run tools/extract_tile_ticks.py')
    print('ported/tick matches the source' if '--check' in sys.argv else 'extracted ported/tick')


if __name__ == '__main__':
    main()
