#!/usr/bin/env python3
"""Generate the credits roll from UIScene_Credits::gs_aCreditDefs (PS3 build).

Each entry is kept as written: the swprintf format, up to two IDS_* strings it
substitutes, the text size, or a CREDIT_ICON entry naming the logo. The
#ifdef/#elif/#else blocks are resolved for __PS3__ (not _XBOX, __ORBIS__,
_DURANGO, __PSVITA__, _WIN64).
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'source_full/Minecraft.Client/Common/UI/UIScene_Credits.cpp'
STRINGS = ROOT / 'source_full/Minecraft.Client/PS3Media/strings.h'
DEFINED = {'__PS3__'}

string_ids = {m[1]: int(m[2]) for m in re.finditer(r'#define\s+(IDS_\w+)\s+(\d+)', STRINGS.read_text())}
text = SOURCE.read_text(encoding='utf-8-sig')
start = text.index('gs_aCreditDefs[MAX_CREDIT_STRINGS] =')
body = text[text.index('{', start) + 1:text.index('\n};', start)]


def condition(expr):
    expr = expr.strip()
    names = re.findall(r'defined\s*\(?\s*(\w+)\s*\)?', expr)
    if expr.startswith('!'):
        return not condition(expr[1:])
    if names:
        return any(n in DEFINED for n in names)
    return expr in DEFINED


# (active, taken) per nesting level.
stack = []
kept = []
for line in body.splitlines():
    s = line.strip()
    if s.startswith('#ifdef'):
        c = s[6:].strip() in DEFINED
        stack.append([c, c])
    elif s.startswith('#ifndef'):
        c = s[7:].strip() not in DEFINED
        stack.append([c, c])
    elif s.startswith('#if'):
        c = condition(s[3:])
        stack.append([c, c])
    elif s.startswith('#elif'):
        c = not stack[-1][1] and condition(s[5:])
        stack[-1] = [c, stack[-1][1] or c]
    elif s.startswith('#else'):
        stack[-1] = [not stack[-1][1], True]
    elif s.startswith('#endif'):
        stack.pop()
    elif all(active for active, _ in stack):
        kept.append(re.sub(r'//.*', '', line))

entries = re.findall(r'\{\s*L"((?:[^"\\]|\\.)*)"\s*,\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\}', '\n'.join(kept))
SIZES = {'eSmallText': 0, 'eMediumText': 1, 'eLargeText': 2, 'eExtraLargeText': 3}
ICONS = {'eCreditIcon_Iggy': 0, 'eCreditIcon_Miles': 1, 'eCreditIcon_Dolby': 2}


def ref(token):
    if token == 'NO_TRANSLATED_STRING':
        return -1
    if token == 'CREDIT_ICON':
        return -2
    if token in ICONS:
        return ICONS[token]
    if token not in string_ids:
        raise SystemExit(f'unknown credit string {token}')
    return string_ids[token]


out = ['// Generated by tools/extract_credits.py from UIScene_Credits::gs_aCreditDefs (__PS3__).',
       '// Do not edit by hand.',
       '#include "ConsoleCredits.h"',
       'namespace console {',
       'namespace {',
       'constexpr ConsoleCredit kCredits[]{']
for literal, first, second, size in entries:
    literal = literal.replace('\\"', '"')
    escaped = literal.replace('\\', '\\\\').replace('"', '\\"')
    out.append(f' {{"{escaped}",{ref(first)},{ref(second)},{SIZES[size]}}},')
out += ['};',
        '}',
        'const ConsoleCredit* consoleCredits(std::size_t& count){count=sizeof(kCredits)/sizeof(kCredits[0]);return kCredits;}',
        '}',
        '']
args = [a for a in sys.argv[1:] if a != '--check']
target = Path(args[0]) if args else ROOT / 'ported/ConsoleCredits.cpp'
if '--check' in sys.argv:
    if not target.exists() or target.read_text() != '\n'.join(out):
        raise SystemExit(f'{target} is stale; rerun {Path(__file__).name}')
else:
    target.write_text('\n'.join(out))
print(f'{len(entries)} credit lines')
