// Generated by tools/extract_block_placement.py from original placement bodies.
#include "BlockPlacement.h"
#include "Mth.h"
#include "Facing.h"
#include <cmath>
#include <stdexcept>
namespace console {
namespace {
struct PlacementPlayer {double x,y,z;float heightOffset,yRot;};
int originalFacing(int x,int y,int z,const PlacementPlayer* player)
{
    if (Mth::abs((float) player->x - x) < 2 && Mth::abs((float) player->z - z) < 2) 
	{
        // If the player is above the block, the slot is on the top
        double py = player->y + 1.82 - player->heightOffset;
        if (py - y > 2)
		{
            return Facing::UP;
        }
        // If the player is below the block, the slot is on the bottom
        if (y - py > 0)
		{
            return Facing::DOWN;
        }
    }
    // The slot is on the side
    int i = Mth::floor(player->yRot * 4.0f / 360.0f + 0.5) & 0x3;
    if (i == 0) return Facing::NORTH;
    if (i == 1) return Facing::EAST;
    if (i == 2) return Facing::SOUTH;
    if (i == 3) return Facing::WEST;
    return 0;
}
}
int consoleLogPlacementData(int data,int dir){
 if(data<0 || data>15 || dir<0 || dir>5)throw std::invalid_argument("Invalid log placement metadata or facing");
 constexpr int MASK_TYPE=3,FACING_Y=0,FACING_X=4,FACING_Z=8;

	int type = data & MASK_TYPE;
	
	int facing = 0;

	switch (dir)
	{
	case Facing::NORTH:
	case Facing::SOUTH:
		facing = FACING_Z;
		break;
	case Facing::EAST:
	case Facing::WEST:
		facing = FACING_X;
		break;
	case Facing::UP:
	case Facing::DOWN:
		facing = FACING_Y;
		break;
	}

	return type | facing;
}
int consolePlacementFacing(int x,int y,int z,Vec3 feet,double yaw){
 if(!std::isfinite(feet.x) || !std::isfinite(feet.y) || !std::isfinite(feet.z) ||
    !std::isfinite(yaw) || std::abs(feet.x)>30000000 || std::abs(feet.z)>30000000 || std::abs(feet.y)>30000000 ||
    x<-30000000 || x>30000000 || z<-30000000 || z>30000000 || y<-30000000 || y>30000000)
  throw std::invalid_argument("Invalid placement coordinates");
 constexpr double pi=3.14159265358979323846;
 // Native camera faces -Z at zero; the original player faces +Z at zero.
 const float degrees=static_cast<float>(std::remainder(yaw,2*pi)*180/pi+180);
 constexpr float heightOffset=1.62f;
 PlacementPlayer player{feet.x,feet.y+heightOffset,feet.z,heightOffset,degrees};
 return originalFacing(x,y,z,&player);
}
}
