execute_process(COMMAND "${REFERENCE}" RESULT_VARIABLE reference_status OUTPUT_VARIABLE reference_output ERROR_VARIABLE reference_error)
execute_process(COMMAND "${PORTED}" RESULT_VARIABLE ported_status OUTPUT_VARIABLE ported_output ERROR_VARIABLE ported_error)
if(NOT reference_status EQUAL 0 OR NOT ported_status EQUAL 0)
  message(FATAL_ERROR "Source parity executable failed: reference=${reference_status}, port=${ported_status}\n${reference_error}\n${ported_error}")
endif()
if(NOT reference_output STREQUAL ported_output)
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/reference-output.txt" "${reference_output}")
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/ported-output.txt" "${ported_output}")
  message(FATAL_ERROR "Ported samples differ from the archived source: ${PORTED}")
endif()
message(STATUS "Ported samples exactly match the untouched source")
