// Generated by tools/gen_metal_shaders.py from shaders/beam_volume_vk.frag.spv — do not edit.
// spirv-sha256: f2b2dd0a8100cf7dac494679f64a779a1da4aa970cd7ce380a2da7762250766f
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
};

struct beam_volume_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct beam_volume_vk_frag_in
{
    float3 vRenderPos [[user(locn0)]];
};

static inline __attribute__((always_inline))
bool coneInterval(thread const float3& CA, thread const float3& R, thread const float3& D, thread const float& r0, thread const float& k, thread const float& sEnd, thread float2& seg)
{
    seg = float2(0.0);
    float sc = dot(CA, D);
    float rd = dot(R, D);
    float rc = r0 + (k * sc);
    float a = 1.0 - (((1.0 + (k * k)) * rd) * rd);
    float b = dot(CA, R) - (rd * (sc + (k * rc)));
    float c = (dot(CA, CA) - (sc * sc)) - (rc * rc);
    float s0;
    float s1;
    if (abs(rd) > 9.9999999747524270787835121154785e-07)
    {
        float ta = (-sc) / rd;
        float tb = (sEnd - sc) / rd;
        s0 = fast::min(ta, tb);
        s1 = fast::max(ta, tb);
    }
    else
    {
        if ((sc < 0.0) || (sc > sEnd))
        {
            return false;
        }
        s0 = -1000000000.0;
        s1 = 1000000000.0;
    }
    float t0 = -1000000000.0;
    float t1 = 1000000000.0;
    float disc = (b * b) - (a * c);
    if (abs(a) > 9.9999999747524270787835121154785e-07)
    {
        if (disc >= 0.0)
        {
            float sq = sqrt(disc);
            float ra = ((-b) - sq) / a;
            float rb = ((-b) + sq) / a;
            float lo = fast::min(ra, rb);
            float hi = fast::max(ra, rb);
            if (a > 0.0)
            {
                t0 = lo;
                t1 = hi;
            }
            else
            {
                float2 i1 = float2(s0, fast::min(s1, lo));
                float2 i2 = float2(fast::max(s0, hi), s1);
                seg = select(i2, i1, bool2((i1.y - i1.x) >= (i2.y - i2.x)));
                return seg.y > seg.x;
            }
        }
        else
        {
            if (a > 0.0)
            {
                return false;
            }
        }
    }
    else
    {
        if (abs(b) > 9.9999999747524270787835121154785e-07)
        {
            float tr = (-c) / (2.0 * b);
            if (b > 0.0)
            {
                t1 = tr;
            }
            else
            {
                t0 = tr;
            }
        }
        else
        {
            if (c > 0.0)
            {
                return false;
            }
        }
    }
    seg = float2(fast::max(t0, s0), fast::min(t1, s1));
    return seg.y > seg.x;
}

static inline __attribute__((always_inline))
float linearFog(thread const float& d, thread const float& s, thread const float& e)
{
    if (d <= s)
    {
        return 0.0;
    }
    if (d >= e)
    {
        return 1.0;
    }
    return (d - s) / (e - s);
}

static inline __attribute__((always_inline))
float fogAt(thread const float3& d, constant Common& U)
{
    float sph = length(d);
    float cyl = fast::max(length(d.xz), abs(d.y));
    float param = sph;
    float param_1 = U.uFogEnv_.x;
    float param_2 = U.uFogEnv_.y;
    float param_3 = cyl;
    float param_4 = U.uFogEnv_.z;
    float param_5 = U.uFogEnv_.w;
    return (fast::max(linearFog(param, param_1, param_2), linearFog(param_3, param_4, param_5)) * U.uFogColor_.w) * U.uTint_.x;
}

static inline __attribute__((always_inline))
float ign(thread const float2& c)
{
    return fract(52.98291778564453125 * fract(dot(c, float2(0.067110560834407806396484375, 0.005837149918079376220703125))));
}

static inline __attribute__((always_inline))
float3 beamLight(thread const float3& q, thread float& s, constant Common& U)
{
    s = dot(q, U.uColorDark_.xyz);
    float L = U.uPortalColor_.w;
    float k = (U.uColorHot_.w - U.uColorDark_.w) / L;
    float rs = fast::max(U.uColorDark_.w + (k * fast::max(s, 0.0)), 0.001000000047497451305389404296875);
    float rho2 = fast::max(dot(q, q) - (s * s), 0.0) / (rs * rs);
    bool _173 = rho2 >= 1.0;
    bool _179;
    if (!_173)
    {
        _179 = s <= 0.0;
    }
    else
    {
        _179 = _173;
    }
    if (_179)
    {
        return float3(0.0);
    }
    float window = 1.0 - rho2;
    window *= window;
    float3 radial = ((U.uColorHot_.xyz * exp((-14.0) * rho2)) + (U.uKeyDir_.xyz * exp((-3.0) * rho2))) * window;
    float fadeIn = smoothstep(0.0, fast::max(U.uScalarsB_.z, 0.001000000047497451305389404296875), s);
    float spread = 1.0 / (1.0 + ((s * s) / (U.uScalarsB_.w * U.uScalarsB_.w)));
    float endFade = 1.0 - smoothstep(U.uTint_.y * L, L, s);
    float ext = exp((-U.uScalarsB_.y) * s);
    return radial * (((fadeIn * spread) * endFade) * ext);
}

static inline __attribute__((always_inline))
float phase(thread const float& mu, thread const float& g)
{
    float g2 = g * g;
    float den = fast::max((1.0 + g2) - ((2.0 * g) * mu), 0.001000000047497451305389404296875);
    return 0.300000011920928955078125 + (0.699999988079071044921875 * powr((1.0 + g2) / den, 1.5));
}

static inline __attribute__((always_inline))
float valueNoise3(thread const float3& x, texture2d<float> uNoiseTex, sampler uNoiseTexSmplr)
{
    float3 p = floor(x);
    float3 f = fract(x);
    f = (f * f) * (float3(3.0) - (f * 2.0));
    float2 uv = (p.xy + (float2(37.0, 17.0) * p.z)) + f.xy;
    float2 rg = uNoiseTex.sample(uNoiseTexSmplr, ((uv + float2(0.5)) / float2(64.0)), level(0.0)).yx;
    return mix(rg.x, rg.y, f.z);
}

static inline __attribute__((always_inline))
float mistAt(thread const float3& q, constant Common& U, texture2d<float> uNoiseTex, sampler uNoiseTexSmplr)
{
    float3 w = q + (float3(17.1299991607666015625, 5.71000003814697265625, 11.36999988555908203125) * U.uScalarsA_.y);
    float t = U.uScalarsA_.x;
    float3 param = (w + (float3(0.5, 0.0625, 0.25) * t)) * 0.125;
    float n1 = valueNoise3(param, uNoiseTex, uNoiseTexSmplr);
    float3 param_1 = (w + (float3(-0.75, 0.125, 0.5) * t)) * 0.5;
    float n2 = valueNoise3(param_1, uNoiseTex, uNoiseTexSmplr);
    float n = (0.62000000476837158203125 * n1) + (0.37999999523162841796875 * n2);
    return mix(1.0, 0.1500000059604644775390625 + (1.89999997615814208984375 * smoothstep(0.2199999988079071044921875, 0.7799999713897705078125, n)), U.uScalarsA_.z);
}

fragment beam_volume_vk_frag_out beam_volume_vk_frag(beam_volume_vk_frag_in in [[stage_in]], constant Common& U [[buffer(1)]], texture2d<float> uNoiseTex [[texture(0)]], sampler uNoiseTexSmplr [[sampler(0)]], float4 gl_FragCoord [[position]])
{
    beam_volume_vk_frag_out out = {};
    float3 eye = U.uCamPosBright_.xyz;
    float3 R = fast::normalize(in.vRenderPos - eye);
    float3 A = U.uPortalColor_.xyz;
    float3 D = U.uColorDark_.xyz;
    float L = U.uPortalColor_.w;
    float clipEnd = fast::min(U.uTint_.w, L);
    float k = (U.uColorHot_.w - U.uColorDark_.w) / L;
    float tShift = fast::max(dot((A + (D * (0.5 * clipEnd))) - eye, R), 0.0);
    float3 param = (eye + (R * tShift)) - A;
    float3 param_1 = R;
    float3 param_2 = D;
    float param_3 = U.uColorDark_.w;
    float param_4 = k;
    float param_5 = clipEnd;
    float2 param_6;
    bool _689 = coneInterval(param, param_1, param_2, param_3, param_4, param_5, param_6);
    float2 seg = param_6;
    if (!_689)
    {
        discard_fragment();
    }
    float tNear = fast::max(seg.x + tShift, 0.0);
    float tFar = seg.y + tShift;
    if (tFar <= (tNear + 0.001000000047497451305389404296875))
    {
        discard_fragment();
    }
    float3 param_7 = R * tNear;
    if ((1.0 - fogAt(param_7, U)) <= 0.00200000009499490261077880859375)
    {
        discard_fragment();
    }
    float len = tFar - tNear;
    int steps = int(fast::clamp(ceil(len / 3.0), 3.0, 6.0));
    float dt = len / float(steps);
    float2 param_8 = gl_FragCoord.xy;
    float jitter = ign(param_8);
    float g = U.uScalarsA_.w;
    float3 acc = float3(0.0);
    float param_10;
    for (int i = 0; i < 6; i++)
    {
        if (i >= steps)
        {
            break;
        }
        float t = tNear + ((float(i) + jitter) * dt);
        float3 q = (eye + (R * t)) - A;
        float3 param_9 = q;
        float3 _789 = beamLight(param_9, param_10, U);
        float s = param_10;
        float3 light = _789;
        float clipFade = 1.0 - smoothstep(clipEnd - 1.75, clipEnd, s);
        float mu = (-dot(q, R)) * rsqrt(fast::max(dot(q, q), 9.9999997473787516355514526367188e-05));
        float3 param_11 = (q + A) - eye;
        float T = 1.0 - fogAt(param_11, U);
        float param_12 = mu;
        float param_13 = g;
        float3 param_14 = q;
        acc += (light * (((clipFade * phase(param_12, param_13)) * mistAt(param_14, U, uNoiseTex, uNoiseTexSmplr)) * T));
    }
    acc *= ((dt * U.uScalarsB_.x) * U.uKeyDir_.w);
    out.FragColor = float4(float3(1.0) - exp(-acc), 0.0);
    return out;
}

