// Generated by tools/gen_metal_shaders.py from shaders/beam_sprite_vk.vert.spv — do not edit.
// spirv-sha256: d7e07e4524d81b8271ceb9e06c670701e61f905638ae9a1e5adcc64d082aa495
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uLocalRow0;
    float4 uLocalRow1;
    float4 uLocalRow2;
};

struct beam_sprite_vk_vert_out
{
    float3 vLocal [[user(locn0)]];
    float3 vRenderPos [[user(locn1)]];
    float4 gl_Position [[position]];
};

struct beam_sprite_vk_vert_in
{
    float3 aPos [[attribute(0)]];
};

vertex beam_sprite_vk_vert_out beam_sprite_vk_vert(beam_sprite_vk_vert_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]])
{
    beam_sprite_vk_vert_out out = {};
    float4 p = float4(in.aPos, 1.0);
    out.gl_Position = pc.uMVP * p;
    out.vLocal = in.aPos;
    out.vRenderPos = float3(dot(pc.uLocalRow0, p), dot(pc.uLocalRow1, p), dot(pc.uLocalRow2, p));
    return out;
}

