// Generated by tools/gen_metal_shaders.py from shaders/beam_pool_vk.frag.spv — do not edit.
// spirv-sha256: 8aa45c1a793486d4c7ec5f5c0314f0faf7b0c1776d928a7a5049f84695f39b15
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
};

struct beam_pool_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct beam_pool_vk_frag_in
{
    float3 vRenderPos [[user(locn1)]];
};

static inline __attribute__((always_inline))
float3 beamLight(thread const float3& q, thread float& s, constant Common& U)
{
    s = dot(q, U.uColorDark_.xyz);
    float L = U.uPortalColor_.w;
    float k = (U.uColorHot_.w - U.uColorDark_.w) / L;
    float rs = fast::max(U.uColorDark_.w + (k * fast::max(s, 0.0)), 0.001000000047497451305389404296875);
    float rho2 = fast::max(dot(q, q) - (s * s), 0.0) / (rs * rs);
    bool _147 = rho2 >= 1.0;
    bool _153;
    if (!_147)
    {
        _153 = s <= 0.0;
    }
    else
    {
        _153 = _147;
    }
    if (_153)
    {
        return float3(0.0);
    }
    float window = 1.0 - rho2;
    window *= window;
    float3 radial = ((U.uColorHot_.xyz * exp((-14.0) * rho2)) + (U.uKeyDir_.xyz * exp((-3.0) * rho2))) * window;
    float fadeIn = smoothstep(0.0, fast::max(U.uScalarsB_.z, 0.001000000047497451305389404296875), s);
    float spread = 1.0 / (1.0 + ((s * s) / (U.uScalarsB_.w * U.uScalarsB_.w)));
    float endFade = 1.0 - smoothstep(U.uTint_.y * L, L, s);
    float ext = exp((-U.uScalarsB_.y) * s);
    return radial * (((fadeIn * spread) * endFade) * ext);
}

static inline __attribute__((always_inline))
float linearFog(thread const float& d, thread const float& s, thread const float& e)
{
    if (d <= s)
    {
        return 0.0;
    }
    if (d >= e)
    {
        return 1.0;
    }
    return (d - s) / (e - s);
}

static inline __attribute__((always_inline))
float fogAt(thread const float3& d, constant Common& U)
{
    float sph = length(d);
    float cyl = fast::max(length(d.xz), abs(d.y));
    float param = sph;
    float param_1 = U.uFogEnv_.x;
    float param_2 = U.uFogEnv_.y;
    float param_3 = cyl;
    float param_4 = U.uFogEnv_.z;
    float param_5 = U.uFogEnv_.w;
    return (fast::max(linearFog(param, param_1, param_2), linearFog(param_3, param_4, param_5)) * U.uFogColor_.w) * U.uTint_.x;
}

fragment beam_pool_vk_frag_out beam_pool_vk_frag(beam_pool_vk_frag_in in [[stage_in]], constant Common& U [[buffer(1)]])
{
    beam_pool_vk_frag_out out = {};
    float3 eye = U.uCamPosBright_.xyz;
    float3 q = in.vRenderPos;
    float3 n = float3(U.uScalarsA_.x, U.uScalarsA_.y, U.uScalarsA_.z);
    bool outside = false;
    if (outside)
    {
        discard_fragment();
    }
    float3 rel = q - U.uPortalColor_.xyz;
    float3 param = rel;
    float param_1;
    float3 _267 = beamLight(param, param_1, U);
    float s = param_1;
    float3 light = _267;
    float lambert = fast::max(dot(n, -fast::normalize(rel)), 0.0);
    float3 param_2 = q - eye;
    float T = 1.0 - fogAt(param_2, U);
    float3 relight = light * (((lambert * T) * U.uScalarsA_.w) * U.uKeyDir_.w);
    out.FragColor = float4(fast::min(relight, float3(1.0)), 0.0);
    return out;
}

