// Generated by tools/gen_metal_shaders.py from shaders/beam_volume_vk.vert.spv — do not edit.
// spirv-sha256: 1ecd3b5b5965e4cd754796f96b9e5865fedcd8d56adf14e1b58106a84a123b4d
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
};

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
};

struct beam_volume_vk_vert_out
{
    float3 vRenderPos [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct beam_volume_vk_vert_in
{
    float3 aPos [[attribute(0)]];
};

vertex beam_volume_vk_vert_out beam_volume_vk_vert(beam_volume_vk_vert_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], constant Common& U [[buffer(1)]])
{
    beam_volume_vk_vert_out out = {};
    float3 A = U.uPortalColor_.xyz;
    float3 D = U.uColorDark_.xyz;
    float L = U.uPortalColor_.w;
    float sEnd = fast::min(U.uTint_.w, L);
    float3 helper = select(float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), bool3(abs(D.y) < 0.9900000095367431640625));
    float3 U1 = fast::normalize(cross(D, helper));
    float3 W1 = cross(D, U1);
    float s = mix(-0.07999999821186065673828125, sEnd + 0.07999999821186065673828125, in.aPos.x);
    float r = ((U.uColorDark_.w + (((U.uColorHot_.w - U.uColorDark_.w) * fast::clamp(s, 0.0, L)) / L)) * 1.0299999713897705078125) + 0.07999999821186065673828125;
    float3 pos = (A + (D * s)) + (((U1 * in.aPos.y) + (W1 * in.aPos.z)) * r);
    out.vRenderPos = pos;
    out.gl_Position = pc.uMVP * float4(pos, 1.0);
    return out;
}

