// Generated by tools/gen_metal_shaders.py from shaders/block_break_overlay_vk.frag.spv — do not edit.
// spirv-sha256: 335dc9ad97d9422b04288139881ef423aa6c324cd16ae1d2aa7a2f032a4fd52d
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct block_break_overlay_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct block_break_overlay_vk_frag_in
{
    float2 vUV [[user(locn0)]];
};

fragment block_break_overlay_vk_frag_out block_break_overlay_vk_frag(block_break_overlay_vk_frag_in in [[stage_in]], texture2d<float> uAtlas [[texture(0)]], sampler uAtlasSmplr [[sampler(0)]])
{
    block_break_overlay_vk_frag_out out = {};
    float4 t = uAtlas.sample(uAtlasSmplr, in.vUV);
    if (t.w < 0.0500000007450580596923828125)
    {
        discard_fragment();
    }
    out.FragColor = float4(t.xyz, 1.0);
    return out;
}

