// Generated by tools/gen_metal_shaders.py from shaders/block_instanced_vk.vert.spv — do not edit.
// spirv-sha256: ada3ccc7b75c54ea8182d90ee2b07af4e357e7bdbafad41e9022f7bfa6e3d7d4
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uPortalClipPlane;
};

constant spvUnsafeArray<int, 24> _176 = spvUnsafeArray<int, 24>({ 4, 5, 2, 3, 5, 4, 2, 3, 1, 0, 5, 4, 4, 5, 0, 1, 1, 0, 2, 3, 0, 1, 2, 3 });

struct block_instanced_vk_vert_out
{
    float2 fragTexCoord [[user(locn0)]];
    float3 fragWorldPos [[user(locn1)]];
    float4 fragColor [[user(locn2)]];
    float4 gl_Position [[position]];
    float gl_ClipDistance [[clip_distance]] [1];
    float gl_ClipDistance_0 [[user(clip0)]];
};

struct block_instanced_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float2 aTexCoord [[attribute(1)]];
    float4 aColor [[attribute(2)]];
    float4 aInstance [[attribute(3)]];
    uint4 aCells0 [[attribute(4)]];
    uint4 aCells1 [[attribute(5)]];
    uint4 aCells2 [[attribute(6)]];
    uint2 aCells3 [[attribute(7)]];
};

static inline __attribute__((always_inline))
int3 dirStep(thread const int& d)
{
    if (d == 0)
    {
        return int3(0, -1, 0);
    }
    if (d == 1)
    {
        return int3(0, 1, 0);
    }
    if (d == 2)
    {
        return int3(0, 0, -1);
    }
    if (d == 3)
    {
        return int3(0, 0, 1);
    }
    if (d == 4)
    {
        return int3(-1, 0, 0);
    }
    return int3(1, 0, 0);
}

static inline __attribute__((always_inline))
int cornerDir(thread const int& d, thread const int& i)
{
    return _176[(d * 4) + i];
}

static inline __attribute__((always_inline))
int2 cellLight(thread const int3& off, thread spvUnsafeArray<uint, 14>& g_cells)
{
    int i = (((off.x + 1) * 9) + ((off.y + 1) * 3)) + (off.z + 1);
    uint v = g_cells[i >> 1];
    uint _113;
    if ((i & 1) != 0)
    {
        _113 = v >> 8u;
    }
    else
    {
        _113 = v & 255u;
    }
    uint b = _113;
    return int2(int(b & 15u), int(b >> 4u));
}

static inline __attribute__((always_inline))
int2 smoothBlend(thread int2& n1, thread int2& n2, thread int2& n3, thread const int2& c)
{
    bool _225 = c.y > 2;
    bool _232;
    if (!_225)
    {
        _232 = c.x > 2;
    }
    else
    {
        _232 = _225;
    }
    if (_232)
    {
        if (all(n1 == int2(0)))
        {
            n1 = c;
        }
        else
        {
            if (n1.y == 0)
            {
                n1.y = c.y;
            }
        }
        if (all(n2 == int2(0)))
        {
            n2 = c;
        }
        else
        {
            if (n2.y == 0)
            {
                n2.y = c.y;
            }
        }
        if (all(n3 == int2(0)))
        {
            n3 = c;
        }
        else
        {
            if (n3.y == 0)
            {
                n3.y = c.y;
            }
        }
    }
    return (((n1 + n2) + n3) + c) * int2(4);
}

static inline __attribute__((always_inline))
float cornerWeight(thread const int& d, thread const float3& p)
{
    int _188;
    if (d >= 4)
    {
        _188 = 0;
    }
    else
    {
        _188 = (d <= 1) ? 1 : 2;
    }
    int axis = _188;
    bool positive = ((d == 1) || (d == 3)) || (d == 5);
    float c = fast::clamp(p[axis], 0.0, 1.0);
    float _213;
    if (positive)
    {
        _213 = c;
    }
    else
    {
        _213 = 1.0 - c;
    }
    return _213;
}

static inline __attribute__((always_inline))
float2 smoothLight(thread const int& d, thread const bool& cubic, thread const float3& p, thread spvUnsafeArray<uint, 14>& g_cells)
{
    int param = d;
    int3 face = dirStep(param);
    int3 base = select(int3(0), face, bool3(cubic));
    int param_1 = d;
    int param_2 = 0;
    int param_3 = cornerDir(param_1, param_2);
    int3 c0 = dirStep(param_3);
    int param_4 = d;
    int param_5 = 1;
    int param_6 = cornerDir(param_4, param_5);
    int3 c1 = dirStep(param_6);
    int param_7 = d;
    int param_8 = 2;
    int param_9 = cornerDir(param_7, param_8);
    int3 c2 = dirStep(param_9);
    int param_10 = d;
    int param_11 = 3;
    int param_12 = cornerDir(param_10, param_11);
    int3 c3 = dirStep(param_12);
    int3 param_13 = base + c0;
    int2 l0 = cellLight(param_13, g_cells);
    int3 param_14 = base + c1;
    int2 l1 = cellLight(param_14, g_cells);
    int3 param_15 = base + c2;
    int2 l2 = cellLight(param_15, g_cells);
    int3 param_16 = base + c3;
    int2 l3 = cellLight(param_16, g_cells);
    int3 param_17 = face;
    int2 center = cellLight(param_17, g_cells);
    int3 param_18 = (base + c0) + c3;
    int2 param_19 = l3;
    int2 param_20 = l0;
    int2 param_21 = cellLight(param_18, g_cells);
    int2 param_22 = center;
    int2 _375 = smoothBlend(param_19, param_20, param_21, param_22);
    int2 tc0 = _375;
    int3 param_23 = (base + c0) + c2;
    int2 param_24 = l2;
    int2 param_25 = l0;
    int2 param_26 = cellLight(param_23, g_cells);
    int2 param_27 = center;
    int2 _391 = smoothBlend(param_24, param_25, param_26, param_27);
    int2 tc1 = _391;
    int3 param_28 = (base + c1) + c2;
    int2 param_29 = l2;
    int2 param_30 = l1;
    int2 param_31 = cellLight(param_28, g_cells);
    int2 param_32 = center;
    int2 _407 = smoothBlend(param_29, param_30, param_31, param_32);
    int2 tc2 = _407;
    int3 param_33 = (base + c1) + c3;
    int2 param_34 = l3;
    int2 param_35 = l1;
    int2 param_36 = cellLight(param_33, g_cells);
    int2 param_37 = center;
    int2 _423 = smoothBlend(param_34, param_35, param_36, param_37);
    int2 tc3 = _423;
    int param_38 = d;
    int param_39 = 3;
    int param_40 = cornerDir(param_38, param_39);
    float3 param_41 = p;
    int param_42 = d;
    int param_43 = 0;
    int param_44 = cornerDir(param_42, param_43);
    float3 param_45 = p;
    float w0 = cornerWeight(param_40, param_41) * cornerWeight(param_44, param_45);
    int param_46 = d;
    int param_47 = 2;
    int param_48 = cornerDir(param_46, param_47);
    float3 param_49 = p;
    int param_50 = d;
    int param_51 = 0;
    int param_52 = cornerDir(param_50, param_51);
    float3 param_53 = p;
    float w1 = cornerWeight(param_48, param_49) * cornerWeight(param_52, param_53);
    int param_54 = d;
    int param_55 = 2;
    int param_56 = cornerDir(param_54, param_55);
    float3 param_57 = p;
    int param_58 = d;
    int param_59 = 1;
    int param_60 = cornerDir(param_58, param_59);
    float3 param_61 = p;
    float w2 = cornerWeight(param_56, param_57) * cornerWeight(param_60, param_61);
    int param_62 = d;
    int param_63 = 3;
    int param_64 = cornerDir(param_62, param_63);
    float3 param_65 = p;
    int param_66 = d;
    int param_67 = 1;
    int param_68 = cornerDir(param_66, param_67);
    float3 param_69 = p;
    float w3 = cornerWeight(param_64, param_65) * cornerWeight(param_68, param_69);
    int sky = int((((float(tc0.y) * w0) + (float(tc1.y) * w1)) + (float(tc2.y) * w2)) + (float(tc3.y) * w3));
    int block = int((((float(tc0.x) * w0) + (float(tc1.x) * w1)) + (float(tc2.x) * w2)) + (float(tc3.x) * w3));
    return float2(float(block & 255), float(sky & 255));
}

static inline __attribute__((always_inline))
float3 sampleLightmap(thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr)
{
    return uLightmap.sample(uLightmapSmplr, fast::clamp((uv / float2(256.0)) + float2(0.03125), float2(0.03125), float2(0.96875)), level(0.0)).xyz;
}

vertex block_instanced_vk_vert_out block_instanced_vk_vert(block_instanced_vk_vert_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], texture2d<float> uLightmap [[texture(3)]], sampler uLightmapSmplr [[sampler(3)]])
{
    block_instanced_vk_vert_out out = {};
    float4 worldPos = float4(in.aInstance.xyz + (in.aPos * in.aInstance.w), 1.0);
    out.gl_Position = pc.uMVP * worldPos;
    out.fragTexCoord = in.aTexCoord;
    out.fragWorldPos = worldPos.xyz;
    spvUnsafeArray<uint, 14> g_cells;
    g_cells[0] = in.aCells0.x;
    g_cells[1] = in.aCells0.y;
    g_cells[2] = in.aCells0.z;
    g_cells[3] = in.aCells0.w;
    g_cells[4] = in.aCells1.x;
    g_cells[5] = in.aCells1.y;
    g_cells[6] = in.aCells1.z;
    g_cells[7] = in.aCells1.w;
    g_cells[8] = in.aCells2.x;
    g_cells[9] = in.aCells2.y;
    g_cells[10] = in.aCells2.z;
    g_cells[11] = in.aCells2.w;
    g_cells[12] = in.aCells3.x;
    g_cells[13] = in.aCells3.y;
    bool preLit = ((g_cells[13] >> 8u) & 1u) != 0u;
    float3 light = float3(1.0);
    if (!preLit)
    {
        int recipe = int((in.aColor.w * 255.0) + 0.5);
        float2 coords;
        if ((recipe != 255) && (recipe >= 128))
        {
            int param = recipe & 7;
            bool param_1 = (recipe & 8) != 0;
            float3 param_2 = in.aPos;
            coords = smoothLight(param, param_1, param_2, g_cells);
        }
        else
        {
            int _701;
            if (recipe == 255)
            {
                _701 = 6;
            }
            else
            {
                _701 = recipe & 7;
            }
            int n = _701;
            int3 _711;
            if (n == 6)
            {
                _711 = int3(0);
            }
            else
            {
                int param_3 = n;
                _711 = dirStep(param_3);
            }
            int3 param_4 = _711;
            int2 l = cellLight(param_4, g_cells);
            coords = float2(l * int2(16));
        }
        float2 param_5 = coords;
        light = sampleLightmap(param_5, uLightmap, uLightmapSmplr);
    }
    out.fragColor = float4(in.aColor.xyz * light, 1.0);
    out.gl_ClipDistance[0] = dot(worldPos.xyz, pc.uPortalClipPlane.xyz) + pc.uPortalClipPlane.w;
    out.gl_ClipDistance_0 = out.gl_ClipDistance[0];
    return out;
}

