// Generated by tools/gen_metal_shaders.py from shaders/clouds_oit_db_vk.frag.spv — do not edit.
// spirv-sha256: e21c0a61610b2153c129cffafb5423e745a5692c900d7045f803b6c993cd68b5
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct OitParams
{
    float4 OitProjParams;
};

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uColor;
};

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
};

struct clouds_oit_db_vk_frag_out
{
    float4 oitDepthBoundsOut [[color(0)]];
};

struct clouds_oit_db_vk_frag_in
{
    float4 vColor [[user(locn0)]];
};

static inline __attribute__((always_inline))
float deviceToLinearDepth(thread const float& deviceDepth, constant OitParams& _30)
{
    float ndc = (deviceDepth - 0.5) * 2.0;
    return _30.OitProjParams.y / (ndc + _30.OitProjParams.x);
}

static inline __attribute__((always_inline))
void calculateDepthBounds(thread const float& fragmentDeviceDepth, thread const float& alpha, constant OitParams& _30, thread float4& oitDepthBoundsOut)
{
    float param = fragmentDeviceDepth;
    float fragmentLinearDepth = deviceToLinearDepth(param, _30);
    float nearness = 1.0 - fragmentDeviceDepth;
    float opaqueNearness = (alpha > 0.9900000095367431640625) ? nearness : 0.0;
    oitDepthBoundsOut = float4(-fragmentLinearDepth, fragmentLinearDepth, nearness, opaqueNearness);
}

static inline __attribute__((always_inline))
void executeAlphaOnlyPhase(thread const float& deviceDepth, thread const float& alpha, constant OitParams& _30, thread float4& oitDepthBoundsOut)
{
    if (alpha < 0.00999999977648258209228515625)
    {
        discard_fragment();
    }
    float param = deviceDepth;
    float param_1 = alpha;
    calculateDepthBounds(param, param_1, _30, oitDepthBoundsOut);
}

fragment clouds_oit_db_vk_frag_out clouds_oit_db_vk_frag(clouds_oit_db_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], constant OitParams& _30 [[buffer(4)]], float4 gl_FragCoord [[position]])
{
    clouds_oit_db_vk_frag_out out = {};
    float4 color = in.vColor * pc.uColor;
    if (color.w <= 0.0)
    {
        discard_fragment();
    }
    float param = gl_FragCoord.z;
    float param_1 = color.w;
    executeAlphaOnlyPhase(param, param_1, _30, out.oitDepthBoundsOut);
    return out;
}

