// Generated by tools/gen_metal_shaders.py from shaders/clouds_vk.vert.spv — do not edit.
// spirv-sha256: 9300a8ff3ccad0fa37a52cec16722516f1f16da11c87360f636f3f05a04f7a17
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uColor;
};

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
};

struct clouds_vk_vert_out
{
    float4 vColor [[user(locn0)]];
    float vDist [[user(locn1)]];
    float4 gl_Position [[position]];
};

struct clouds_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float4 aColor [[attribute(2)]];
};

vertex clouds_vk_vert_out clouds_vk_vert(clouds_vk_vert_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], constant Common& U [[buffer(1)]])
{
    clouds_vk_vert_out out = {};
    out.gl_Position = pc.uMVP * float4(in.aPos, 1.0);
    out.vColor = in.aColor;
    out.vDist = length((U.uModel_ * float4(in.aPos, 1.0)).xyz);
    return out;
}

