// Generated by tools/gen_metal_shaders.py from shaders/clouds_oit_tr_vk.frag.spv — do not edit.
// spirv-sha256: 1e51511d105ce0ede20fb13d502965f9a35a2a022ec330d43f2c4540a69e8016
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct OitParams
{
    float4 OitProjParams;
};

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uColor;
};

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
};

struct clouds_oit_tr_vk_frag_out
{
    float4 oitCoeffOut_0 [[color(0)]];
    float4 oitCoeffOut_1 [[color(1)]];
};

struct clouds_oit_tr_vk_frag_in
{
    float4 vColor [[user(locn0)]];
    float vDist [[user(locn1)]];
};

static inline __attribute__((always_inline))
float linearFog(thread const float& d, thread const float& s, thread const float& e)
{
    if (d <= s)
    {
        return 0.0;
    }
    if (d >= e)
    {
        return 1.0;
    }
    return (d - s) / (e - s);
}

static inline __attribute__((always_inline))
float toAbsorbance(thread const float& transmittance)
{
    return fast::clamp(-log(fast::max(transmittance, 9.9999997473787516355514526367188e-05)), 0.0, 4.0);
}

static inline __attribute__((always_inline))
float deviceToLinearDepth(thread const float& deviceDepth, constant OitParams& _42)
{
    float ndc = (deviceDepth - 0.5) * 2.0;
    return _42.OitProjParams.y / (ndc + _42.OitProjParams.x);
}

static inline __attribute__((always_inline))
float normalizeDepth(thread const float& fragmentDeviceDepth, constant OitParams& _42, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord)
{
    float4 depthBoundsSample = DepthBoundsSampler.read(uint2(int2(gl_FragCoord.xy)), 0);
    float closestBoundLinearDepthNegated = depthBoundsSample.x;
    float closestBoundLinearDepth = -closestBoundLinearDepthNegated;
    float furthestBoundLinearDepth = depthBoundsSample.y;
    float param = fragmentDeviceDepth;
    float fragmentLinearDepth = deviceToLinearDepth(param, _42);
    float range = fast::max(furthestBoundLinearDepth - closestBoundLinearDepth, 9.9999997473787516355514526367188e-05);
    float depthWithinBounds = fast::clamp(fragmentLinearDepth - closestBoundLinearDepth, 0.0, range);
    float depthWithHighPrecision = 0.75 * range;
    if (depthWithHighPrecision <= 10.0)
    {
        return depthWithinBounds / range;
    }
    else
    {
        if (depthWithinBounds <= 10.0)
        {
            return (depthWithinBounds / 10.0) * 0.75;
        }
        else
        {
            return 0.75 + (((depthWithinBounds - 10.0) / (range - 10.0)) * 0.25);
        }
    }
}

static inline __attribute__((always_inline))
void addTransmittance(thread const float& transmittance, constant OitParams& _42, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord, thread spvUnsafeArray<float4, 2>& oitCoeffOut)
{
    spvUnsafeArray<float, 8> coefficients;
    for (int i = 0; i < 8; i++)
    {
        coefficients[i] = 0.0;
    }
    float param = transmittance;
    float absorbance = toAbsorbance(param);
    float param_1 = gl_FragCoord.z;
    float originalDepth = normalizeDepth(param_1, _42, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord);
    float depth = (originalDepth * 7.0) / 8.0;
    float averageAbsorbance = absorbance * (1.0 - depth);
    coefficients[0] = averageAbsorbance;
    int depthBinIndex = int(floor(originalDepth * 7.0));
    int treeIndex = depthBinIndex + 8;
    for (int waveletLevel = 0; waveletLevel <= 2; waveletLevel++)
    {
        int power = 2 - waveletLevel;
        int parentIndex = treeIndex >> 1;
        float indexAtParentLevel = float(parentIndex & ((1 << power) - 1));
        int isRightHalf = treeIndex & 1;
        int waveletSign = 1 - (isRightHalf << 1);
        float waveletWidth = exp2(-float(power));
        float waveletHeightScale = exp2(float(power) * 0.5);
        float depthOffsetRelativeToWavelet = depth - (waveletWidth * indexAtParentLevel);
        float distanceFromWaveletEdge = (float(isRightHalf) * waveletWidth) + (float(waveletSign) * depthOffsetRelativeToWavelet);
        float differenceCoefficient = (distanceFromWaveletEdge * waveletHeightScale) * absorbance;
        coefficients[parentIndex] = differenceCoefficient;
        treeIndex = parentIndex;
    }
    for (int attachmentIndex = 0; attachmentIndex < 2; attachmentIndex++)
    {
        oitCoeffOut[attachmentIndex] = float4(coefficients[(attachmentIndex * 4) + 0], coefficients[(attachmentIndex * 4) + 1], coefficients[(attachmentIndex * 4) + 2], coefficients[(attachmentIndex * 4) + 3]);
    }
}

static inline __attribute__((always_inline))
void executeAlphaOnlyPhase(thread const float& deviceDepth, thread const float& alpha, constant OitParams& _42, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord, thread spvUnsafeArray<float4, 2>& oitCoeffOut)
{
    float param = 1.0 - alpha;
    addTransmittance(param, _42, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord, oitCoeffOut);
}

fragment clouds_oit_tr_vk_frag_out clouds_oit_tr_vk_frag(clouds_oit_tr_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], constant Common& U [[buffer(1)]], constant OitParams& _42 [[buffer(4)]], texture2d<float> DepthBoundsSampler [[texture(4)]], sampler DepthBoundsSamplerSmplr [[sampler(4)]], float4 gl_FragCoord [[position]])
{
    clouds_oit_tr_vk_frag_out out = {};
    spvUnsafeArray<float4, 2> oitCoeffOut = {};
    float4 color = in.vColor * pc.uColor;
    float param = in.vDist;
    float param_1 = U.uFogEnv_.x;
    float param_2 = U.uFogEnv_.y;
    color.w *= (1.0 - linearFog(param, param_1, param_2));
    if (color.w <= 0.0)
    {
        discard_fragment();
    }
    float param_3 = gl_FragCoord.z;
    float param_4 = color.w;
    executeAlphaOnlyPhase(param_3, param_4, _42, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord, oitCoeffOut);
    out.oitCoeffOut_0 = oitCoeffOut[0];
    out.oitCoeffOut_1 = oitCoeffOut[1];
    return out;
}

