// Generated by tools/gen_metal_shaders.py from shaders/end_portal_vk.frag.spv — do not edit.
// spirv-sha256: 1628c7e07fb6a4eb01d12c6cfe9b3525a1573354847f08e202cb9044520d0b6c
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

// Implementation of the GLSL radians() function
template<typename T>
inline T radians(T d)
{
    return d * T(0.01745329251);
}

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
};

constant spvUnsafeArray<float3, 16> _247 = spvUnsafeArray<float3, 16>({ float3(0.022087000310420989990234375, 0.09839899837970733642578125, 0.1108179986476898193359375), float3(0.01189200021326541900634765625, 0.095923997461795806884765625, 0.089484997093677520751953125), float3(0.02763600088655948638916015625, 0.101689003407955169677734375, 0.100326001644134521484375), float3(0.0465640015900135040283203125, 0.109883002936840057373046875, 0.114837996661663055419921875), float3(0.064901001751422882080078125, 0.11769600212574005126953125, 0.097189001739025115966796875), float3(0.063761003315448760986328125, 0.086894996464252471923828125, 0.123645998537540435791015625), float3(0.084816999733448028564453125, 0.1119939982891082763671875, 0.16638000309467315673828125), float3(0.09748899936676025390625, 0.1541199982166290283203125, 0.091063998639583587646484375), float3(0.106151998043060302734375, 0.13114400207996368408203125, 0.1951909959316253662109375), float3(0.097721002995967864990234375, 0.110187999904155731201171875, 0.18722899258136749267578125), float3(0.13351599872112274169921875, 0.13827799260616302490234375, 0.14858199656009674072265625), float3(0.07000599801540374755859375, 0.2433319985866546630859375, 0.23579199612140655517578125), float3(0.19676600396633148193359375, 0.1428990066051483154296875, 0.21469600498676300048828125), float3(0.0472810007631778717041015625, 0.3153379857540130615234375, 0.3219699859619140625), float3(0.20467500388622283935546875, 0.39000999927520751953125, 0.3020659983158111572265625), float3(0.0809549987316131591796875, 0.3148210048675537109375, 0.661490976810455322265625) });

struct end_portal_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct end_portal_vk_frag_in
{
    float4 vTexProj [[user(locn0)]];
    float3 vWorldPos [[user(locn1)]];
};

static inline __attribute__((always_inline))
float2x2 mat2_rotate_z(thread const float& _radians)
{
    return float2x2(float2(cos(_radians), -sin(_radians)), float2(sin(_radians), cos(_radians)));
}

static inline __attribute__((always_inline))
float4x4 end_portal_layer(thread const float& layer, constant Common& U)
{
    float4x4 translate = float4x4(float4(1.0, 0.0, 0.0, 17.0 / layer), float4(0.0, 1.0, 0.0, (2.0 + (layer / 1.5)) * (U.uScalarsA_.x * 1.5)), float4(0.0, 0.0, 1.0, 0.0), float4(0.0, 0.0, 0.0, 1.0));
    float param = radians((((layer * layer) * 4321.0) + (layer * 9.0)) * 2.0);
    float2x2 rotate = mat2_rotate_z(param);
    float _90 = (4.5 - (layer / 4.0)) * 2.0;
    float2x2 scale = float2x2(float2(_90, 0.0), float2(0.0, _90));
    float2x2 _96 = scale * rotate;
    return (float4x4(float4(_96[0].x, _96[0].y, 0.0, 0.0), float4(_96[1].x, _96[1].y, 0.0, 0.0), float4(0.0, 0.0, 1.0, 0.0), float4(0.0, 0.0, 0.0, 1.0)) * translate) * float4x4(float4(0.5, 0.0, 0.0, 0.25), float4(0.0, 0.5, 0.0, 0.25), float4(0.0, 0.0, 1.0, 0.0), float4(0.0, 0.0, 0.0, 1.0));
}

static inline __attribute__((always_inline))
float linearFog(thread const float& d, thread const float& s, thread const float& e)
{
    if (d <= s)
    {
        return 0.0;
    }
    if (d >= e)
    {
        return 1.0;
    }
    return (d - s) / (e - s);
}

fragment end_portal_vk_frag_out end_portal_vk_frag(end_portal_vk_frag_in in [[stage_in]], constant Common& U [[buffer(1)]], texture2d<float> uSky [[texture(0)]], texture2d<float> uPortal [[texture(1)]], sampler uSkySmplr [[sampler(0)]], sampler uPortalSmplr [[sampler(1)]])
{
    end_portal_vk_frag_out out = {};
    float4 _150 = in.vTexProj;
    _150.z = _150.w;
    float3 color = uSky.sample(uSkySmplr, _150.xy / _150.z).xyz * float3(0.022087000310420989990234375, 0.09839899837970733642578125, 0.1108179986476898193359375);
    for (int i = 0; i < 15; i++)
    {
        float param = float(i + 1);
        float4 _180 = in.vTexProj * end_portal_layer(param, U);
        _180.z = _180.w;
        color += (uPortal.sample(uPortalSmplr, _180.xy / _180.z).xyz * _247[i]);
    }
    float3 fogDelta = in.vWorldPos - U.uCamPosBright_.xyz;
    float sph = length(fogDelta);
    float cyl = fast::max(length(fogDelta.xz), abs(fogDelta.y));
    float param_1 = sph;
    float param_2 = U.uFogEnv_.x;
    float param_3 = U.uFogEnv_.y;
    float param_4 = cyl;
    float param_5 = U.uFogEnv_.z;
    float param_6 = U.uFogEnv_.w;
    float fogValue = fast::max(linearFog(param_1, param_2, param_3), linearFog(param_4, param_5, param_6));
    color = mix(color, U.uFogColor_.xyz, float3(fogValue * U.uFogColor_.w));
    out.FragColor = float4(color, 1.0);
    return out;
}

