// Generated by tools/gen_metal_shaders.py from shaders/entity_outline_blur_vk.frag.spv — do not edit.
// spirv-sha256: 0bf5b7e22d8cef433d572e69720737978c5d5d6c934730916d19e958faf7ee2b
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uMVP;
    float2 uInSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uColor;
    float2 uBlurDir;
};

struct entity_outline_blur_vk_frag_out
{
    float4 fragColor [[color(0)]];
};

struct entity_outline_blur_vk_frag_in
{
    float2 texCoord [[user(locn0)]];
};

fragment entity_outline_blur_vk_frag_out entity_outline_blur_vk_frag(entity_outline_blur_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], texture2d<float> uTex [[texture(0)]], sampler uTexSmplr [[sampler(0)]])
{
    entity_outline_blur_vk_frag_out out = {};
    float2 oneTexel = float2(1.0) / pc.uInSize;
    float2 sampleStep = oneTexel * pc.uBlurDir;
    float4 blurred = float4(0.0);
    float radius = 2.0;
    float _40 = (-radius) + 0.5;
    for (float a = _40; a <= radius; a += 2.0)
    {
        blurred += uTex.sample(uTexSmplr, (in.texCoord + (sampleStep * a)));
    }
    blurred += (uTex.sample(uTexSmplr, (in.texCoord + (sampleStep * radius))) / float4(2.0));
    out.fragColor = float4((blurred / float4(radius + 0.5)).xyz, blurred.w);
    return out;
}

