// Generated by tools/gen_metal_shaders.py from shaders/entity_outline_blit_vk.frag.spv — do not edit.
// spirv-sha256: bb0deac89c91b8757f879fd59866bf8b054b0357f09b5a71e73b6bcd76012943
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct entity_outline_blit_vk_frag_out
{
    float4 fragColor [[color(0)]];
};

struct entity_outline_blit_vk_frag_in
{
    float2 texCoord [[user(locn0)]];
};

fragment entity_outline_blit_vk_frag_out entity_outline_blit_vk_frag(entity_outline_blit_vk_frag_in in [[stage_in]], texture2d<float> uTex [[texture(0)]], sampler uTexSmplr [[sampler(0)]])
{
    entity_outline_blit_vk_frag_out out = {};
    out.fragColor = uTex.sample(uTexSmplr, in.texCoord);
    return out;
}

