// Generated by tools/gen_metal_shaders.py from shaders/entity_outline_vk.frag.spv — do not edit.
// spirv-sha256: d5297dff4b7b79c6908472c5c3b7893e0e337c4a7e0d8a5fe26e536a69260d41
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uColor;
};

struct entity_outline_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct entity_outline_vk_frag_in
{
    float2 vUV [[user(locn0)]];
};

fragment entity_outline_vk_frag_out entity_outline_vk_frag(entity_outline_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], texture2d<float> uTex [[texture(0)]], sampler uTexSmplr [[sampler(0)]])
{
    entity_outline_vk_frag_out out = {};
    if (uTex.sample(uTexSmplr, in.vUV).w == 0.0)
    {
        discard_fragment();
    }
    out.FragColor = float4(pc.uColor.xyz, 1.0);
    return out;
}

