// Generated by tools/gen_metal_shaders.py from shaders/entity_vk.vert.spv — do not edit.
// spirv-sha256: dd972df1be7a4b105915296376a5dc7c7a71f239a4346a72560a0fd67904b5bc
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uColor;
    float4 uUVRange;
    float4 uScalars;
};

struct entity_vk_vert_out
{
    float2 vUV [[user(locn0)]];
    float4 vColor [[user(locn1)]];
    float3 vRenderPos [[user(locn2)]];
    float4 gl_Position [[position]];
    float gl_ClipDistance [[clip_distance]] [1];
    float gl_ClipDistance_0 [[user(clip0)]];
};

struct entity_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float2 aUV [[attribute(1)]];
    float4 aColor [[attribute(2)]];
};

vertex entity_vk_vert_out entity_vk_vert(entity_vk_vert_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]])
{
    entity_vk_vert_out out = {};
    out.vUV = in.aUV;
    out.vColor = in.aColor;
    out.vRenderPos = in.aPos;
    out.gl_Position = pc.uMVP * float4(in.aPos, 1.0);
    float _61;
    if (any(pc.uUVRange.xyz != float3(0.0)))
    {
        _61 = dot(pc.uUVRange.xyz, in.aPos) + pc.uUVRange.w;
    }
    else
    {
        _61 = 1.0;
    }
    out.gl_ClipDistance[0] = _61;
    out.gl_ClipDistance_0 = out.gl_ClipDistance[0];
    return out;
}

