// Generated by tools/gen_metal_shaders.py from shaders/entity_outline_post_vk.vert.spv — do not edit.
// spirv-sha256: 0809466fce105584ffb4ea9133d01fc008d4b430cc699ef9ee583a7eccae2230
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct entity_outline_post_vk_vert_out
{
    float2 texCoord [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct entity_outline_post_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float2 aUV [[attribute(1)]];
};

vertex entity_outline_post_vk_vert_out entity_outline_post_vk_vert(entity_outline_post_vk_vert_in in [[stage_in]])
{
    entity_outline_post_vk_vert_out out = {};
    out.gl_Position = float4(in.aPos.xy, 0.0, 1.0);
    out.texCoord = float2(in.aUV.x, 1.0 - in.aUV.y);
    return out;
}

