// Generated by tools/gen_metal_shaders.py from shaders/gui_color_vk.frag.spv — do not edit.
// spirv-sha256: cd86f090af73de25113a1fd889910cab9933c3d9ace740c090def6f26d350e78
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
};

struct gui_color_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct gui_color_vk_frag_in
{
    float4 vColor [[user(locn1)]];
};

fragment gui_color_vk_frag_out gui_color_vk_frag(gui_color_vk_frag_in in [[stage_in]])
{
    gui_color_vk_frag_out out = {};
    out.FragColor = in.vColor;
    return out;
}

