// Generated by tools/gen_metal_shaders.py from shaders/highlight_vk.vert.spv — do not edit.
// spirv-sha256: abc79d5c1834685a79301658fb6f5a44745128648a3666700166115cc6f97173
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

// Implementation of signed integer mod accurate to SPIR-V specification
template<typename Tx, typename Ty>
inline Tx spvSMod(Tx x, Ty y)
{
    Tx remainder = x - y * (x / y);
    return select(Tx(remainder + y), remainder, remainder == 0 || (x >= 0) == (y >= 0));
}

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
};

struct highlight_vk_vert_out
{
    float4 fragColor [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct highlight_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float2 aUV [[attribute(1)]];
    float4 aColor [[attribute(2)]];
};

vertex highlight_vk_vert_out highlight_vk_vert(highlight_vk_vert_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], uint gl_VertexIndex [[vertex_id]])
{
    highlight_vk_vert_out out = {};
    int axis = int(in.aUV.x + 0.5);
    float3 edgeDir = float3(0.0);
    if (axis == 0)
    {
        edgeDir.x = 1.0;
    }
    else
    {
        if (axis == 1)
        {
            edgeDir.y = 1.0;
        }
        else
        {
            edgeDir.z = 1.0;
        }
    }
    float4 linePosStart = pc.uMVP * float4(in.aPos, 1.0);
    float4 linePosEnd = pc.uMVP * float4(in.aPos + edgeDir, 1.0);
    float3 ndc1 = linePosStart.xyz / float3(linePosStart.w);
    float3 ndc2 = linePosEnd.xyz / float3(linePosEnd.w);
    float2 lineScreenDirection = fast::normalize((ndc2.xy - ndc1.xy) * pc.uScreenSize);
    float2 lineOffset = (float2(-lineScreenDirection.y, lineScreenDirection.x) * pc.uLineWidth) / pc.uScreenSize;
    if (lineOffset.x < 0.0)
    {
        lineOffset *= (-1.0);
    }
    if (spvSMod(int(gl_VertexIndex), 2) == 0)
    {
        out.gl_Position = float4((ndc1 + float3(lineOffset, 0.0)) * linePosStart.w, linePosStart.w);
    }
    else
    {
        out.gl_Position = float4((ndc1 - float3(lineOffset, 0.0)) * linePosStart.w, linePosStart.w);
    }
    out.fragColor = in.aColor;
    return out;
}

