// Generated by tools/gen_metal_shaders.py from shaders/highlight_vk.frag.spv — do not edit.
// spirv-sha256: 83e34996a7174c4b659376ebe4bc1046543911667b507ac67b133583f7ee3c9c
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct highlight_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct highlight_vk_frag_in
{
    float4 fragColor [[user(locn0)]];
};

fragment highlight_vk_frag_out highlight_vk_frag(highlight_vk_frag_in in [[stage_in]])
{
    highlight_vk_frag_out out = {};
    out.FragColor = in.fragColor;
    return out;
}

