// Generated by tools/gen_metal_shaders.py from shaders/mob_particle_vk.vert.spv — do not edit.
// spirv-sha256: 9007dadfab8a128cc8f56e76afe2e0c5f8f022f2435bd00f3d20d6b24a5cf434
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PC
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uColor;
    float4 uUVRange;
    float4 uScalars;
};

struct mob_particle_vk_vert_out
{
    float2 vUV [[user(locn0)]];
    float4 vColor [[user(locn1)]];
    float3 vRenderPos [[user(locn2)]];
    float4 gl_Position [[position]];
    float gl_ClipDistance [[clip_distance]] [1];
    float gl_ClipDistance_0 [[user(clip0)]];
};

struct mob_particle_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float2 aUV [[attribute(1)]];
    float4 aColor [[attribute(2)]];
};

vertex mob_particle_vk_vert_out mob_particle_vk_vert(mob_particle_vk_vert_in in [[stage_in]], constant PC& pc [[buffer(0)]])
{
    mob_particle_vk_vert_out out = {};
    out.gl_Position = pc.uMVP * float4(in.aPos, 1.0);
    out.vUV = in.aUV;
    out.vColor = in.aColor;
    out.vRenderPos = in.aPos;
    float _61;
    if (any(pc.uUVRange.xyz != float3(0.0)))
    {
        _61 = dot(pc.uUVRange.xyz, in.aPos) + pc.uUVRange.w;
    }
    else
    {
        _61 = 1.0;
    }
    out.gl_ClipDistance[0] = _61;
    out.gl_ClipDistance_0 = out.gl_ClipDistance[0];
    return out;
}

