// Generated by tools/gen_metal_shaders.py from shaders/oit_blit_depth_vk.frag.spv — do not edit.
// spirv-sha256: cacf2ec5c2ff14a481c2d2b28d0787cf19f60200bcbc7d8b9ac601f8fc267239
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct oit_blit_depth_vk_frag_out
{
    float gl_FragDepth [[depth(any)]];
};

fragment oit_blit_depth_vk_frag_out oit_blit_depth_vk_frag(texture2d<float> Sampler0 [[texture(0)]], sampler Sampler0Smplr [[sampler(0)]], float4 gl_FragCoord [[position]])
{
    oit_blit_depth_vk_frag_out out = {};
    out.gl_FragDepth = Sampler0.read(uint2(int2(gl_FragCoord.xy)), 0).x;
    return out;
}

