// Generated by tools/gen_metal_shaders.py from shaders/oit_blit_vk.frag.spv — do not edit.
// spirv-sha256: 150526eab6e24b92e7a908853c6a9e6674f6e3f349197aba9abe1ac6c7898c54
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct oit_blit_vk_frag_out
{
    float4 fragColor [[color(0)]];
};

fragment oit_blit_vk_frag_out oit_blit_vk_frag(texture2d<float> Sampler0 [[texture(0)]], sampler Sampler0Smplr [[sampler(0)]], float4 gl_FragCoord [[position]])
{
    oit_blit_vk_frag_out out = {};
    out.fragColor = Sampler0.read(uint2(int2(gl_FragCoord.xy)), 0);
    return out;
}

