// Generated by tools/gen_metal_shaders.py from shaders/player_billboard_vk.frag.spv — do not edit.
// spirv-sha256: d86b0f63e6daa9c830e45e0f366fe85593ba9a1a2b0fb9eac043432bfdd49ce3
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uClipPlane;
};

struct player_billboard_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct player_billboard_vk_frag_in
{
    float4 vColor [[user(locn0)]];
    float3 vWorldPos [[user(locn1)]];
};

fragment player_billboard_vk_frag_out player_billboard_vk_frag(player_billboard_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]])
{
    player_billboard_vk_frag_out out = {};
    bool _25 = any(pc.uClipPlane.xyz != float3(0.0));
    bool _42;
    if (_25)
    {
        _42 = (dot(in.vWorldPos, pc.uClipPlane.xyz) + pc.uClipPlane.w) < 0.0;
    }
    else
    {
        _42 = _25;
    }
    if (_42)
    {
        discard_fragment();
    }
    out.FragColor = in.vColor;
    return out;
}

