// Generated by tools/gen_metal_shaders.py from shaders/player_billboard_vk.vert.spv — do not edit.
// spirv-sha256: 4ec5f4a41ba68a395e1bf81071dcef12a01c7f591140661903593fbfcbf705dc
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uClipPlane;
};

struct player_billboard_vk_vert_out
{
    float4 vColor [[user(locn0)]];
    float3 vWorldPos [[user(locn1)]];
    float4 gl_Position [[position]];
};

struct player_billboard_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float4 aColor [[attribute(2)]];
};

vertex player_billboard_vk_vert_out player_billboard_vk_vert(player_billboard_vk_vert_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]])
{
    player_billboard_vk_vert_out out = {};
    out.gl_Position = pc.uMVP * float4(in.aPos, 1.0);
    out.vColor = in.aColor;
    out.vWorldPos = in.aPos;
    return out;
}

