// Generated by tools/gen_metal_shaders.py from shaders/portal_vk.vert.spv — do not edit.
// spirv-sha256: 2fdf396d006a611e37dd559f4ebf17511558c8e89b37206d4db72fa995822efd
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
};

struct portal_vk_vert_out
{
    float2 vUV [[user(locn0)]];
    float4 vNoiseUV [[user(locn1)]];
    float3 vWorldPos [[user(locn2)]];
    float4 gl_Position [[position]];
    float gl_ClipDistance [[clip_distance]] [1];
    float gl_ClipDistance_0 [[user(clip0)]];
};

struct portal_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float2 aUV [[attribute(1)]];
};

vertex portal_vk_vert_out portal_vk_vert(portal_vk_vert_in in [[stage_in]], constant Common& c [[buffer(1)]])
{
    portal_vk_vert_out out = {};
    float3 pos = float3(in.aPos.x * c.uPortalColor_.w, in.aPos.y * c.uPortalColor_.w, in.aPos.z);
    out.gl_Position = c.uMVP_ * float4(pos, 1.0);
    out.vWorldPos = (c.uModel_ * float4(pos, 1.0)).xyz;
    float _81;
    if (any(c.uTint_.xyz != float3(0.0)))
    {
        _81 = dot(c.uTint_.xyz, out.vWorldPos) + c.uTint_.w;
    }
    else
    {
        _81 = 1.0;
    }
    out.gl_ClipDistance[0] = _81;
    out.vUV = (in.aUV * 1.0750000476837158203125) - float2(0.037500001490116119384765625);
    float openAmtVS = fast::clamp(c.uColorHot_.w + 0.001000000047497451305389404296875, 0.0, 1.0);
    float scroll = c.uScalarsA_.y * 0.0274999998509883880615234375;
    float2 noiseBase = ((in.aUV - float2(0.5)) / float2(openAmtVS)) + float2(0.5);
    float2 _136 = (noiseBase * 0.300000011920928955078125) + float2(scroll, 0.0);
    out.vNoiseUV.x = _136.x;
    out.vNoiseUV.y = _136.y;
    float2 _145 = (noiseBase * 0.300000011920928955078125) - float2(scroll, 0.0);
    out.vNoiseUV.z = _145.x;
    out.vNoiseUV.w = _145.y;
    out.gl_ClipDistance_0 = out.gl_ClipDistance[0];
    return out;
}

