// Generated by tools/gen_metal_shaders.py from shaders/portal_vk.frag.spv — do not edit.
// spirv-sha256: 284e429a1a7f7197e0e555a72359c57f039e9a6cfb85897a757956cb4dc4ab05
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
};

struct portal_vk_frag_out
{
    float4 FragColor [[color(0)]];
    float gl_FragDepth [[depth(any)]];
};

struct portal_vk_frag_in
{
    float2 vUV [[user(locn0)]];
    float4 vNoiseUV [[user(locn1)]];
    float3 vWorldPos [[user(locn2)]];
};

static inline __attribute__((always_inline))
float fogLinearstep(thread const float& d, thread const float& s, thread const float& e)
{
    return fast::clamp((d - s) / fast::max(e - s, 0.001000000047497451305389404296875), 0.0, 1.0);
}

static inline __attribute__((always_inline))
float surfaceFogValue(thread float3& vWorldPos, constant Common& U)
{
    float3 delta = vWorldPos - U.uCamPosBright_.xyz;
    float sph = length(delta);
    float cyl = fast::max(length(delta.xz), abs(delta.y));
    float param = sph;
    float param_1 = U.uFogEnv_.x;
    float param_2 = U.uFogEnv_.y;
    float param_3 = cyl;
    float param_4 = U.uFogEnv_.z;
    float param_5 = U.uFogEnv_.w;
    return fast::max(fogLinearstep(param, param_1, param_2), fogLinearstep(param_3, param_4, param_5));
}

static inline __attribute__((always_inline))
float linearstep(thread const float& a, thread const float& b, thread const float& v)
{
    return fast::clamp((v - a) / (b - a), 0.0, 1.0);
}

static inline __attribute__((always_inline))
float4 PortalRefract(thread const bool& _41, constant Common& U, thread float2& vUV, texture2d<float> uPortalNoiseTex, sampler uPortalNoiseTexSmplr, thread float4& vNoiseUV, texture2d<float> uPortalColorTex, sampler uPortalColorTexSmplr)
{
    float openAmt = smoothstep(0.0, 1.0, fast::clamp(U.uColorDark_.w, 0.0, 1.0));
    float openAmtSq = openAmt * openAmt;
    float2 stretchVec = (vUV * 2.0) - float2(1.0);
    float distFromCenter = length(stretchVec);
    if (distFromCenter > 1.0750000476837158203125)
    {
        discard_fragment();
    }
    float stencilCutout = step(distFromCenter, openAmtSq);
    float param = openAmtSq;
    float param_1 = openAmtSq + 0.07500000298023223876953125;
    float param_2 = distFromCenter;
    float outerMask = (1.0 - linearstep(param, param_1, param_2)) * (1.0 - stencilCutout);
    float param_3 = openAmtSq - 0.300000011920928955078125;
    float param_4 = openAmtSq;
    float param_5 = distFromCenter;
    float innerMask = linearstep(param_3, param_4, param_5) * stencilCutout;
    float portalActive = fast::clamp(U.uScalarsB_.x, 0.0, 1.0);
    float effectFadeIn = fast::max(fast::clamp(openAmt * 2.5, 0.0, 1.0), 1.0 - portalActive);
    float effectMask = (innerMask + outerMask) * effectFadeIn;
    float4 _noise1 = uPortalNoiseTex.sample(uPortalNoiseTexSmplr, vNoiseUV.xy);
    float4 _noise2 = uPortalNoiseTex.sample(uPortalNoiseTexSmplr, (vNoiseUV.wz - (_noise1.xy * 0.0199999995529651641845703125)));
    _noise1 = uPortalNoiseTex.sample(uPortalNoiseTexSmplr, (vNoiseUV.xy - (_noise2.xy * 0.0199999995529651641845703125)));
    float noiseVal = (_noise1.y + _noise2.y) * 0.5;
    float portalActiveWithNoise = smoothstep(0.0, noiseVal, portalActive);
    float borderMaskNoise = 1.0 - smoothstep(effectMask - 0.875, effectMask + 0.875, noiseVal);
    noiseVal = borderMaskNoise;
    effectMask *= borderMaskNoise;
    float transparency = fast::clamp(effectMask + (stencilCutout * (1.0 - portalActiveWithNoise)), 0.0, 1.0) * 1.5;
    float btShift = (powr(abs(1.0 - vUV.y), 1.5) * 0.800000011920928955078125) + 0.20000000298023223876953125;
    float rampU = fast::clamp((powr(noiseVal, 0.5) * btShift) * transparency, 0.0, 1.0);
    float3 flameColor = uPortalColorTex.sample(uPortalColorTexSmplr, float2(rampU, 0.5)).xyz;
    flameColor *= U.uScalarsA_.w;
    if (U.uScalarsB_.w > 0.001000000047497451305389404296875)
    {
        float3 hot = uPortalColorTex.sample(uPortalColorTexSmplr, float2(0.949999988079071044921875, 0.5)).xyz * U.uScalarsA_.w;
        flameColor = mix(flameColor, hot * 1.39999997615814208984375, float3(U.uScalarsB_.w * 0.75));
    }
    return float4(flameColor, fast::clamp(transparency, 0.0, 1.0));
}

static inline __attribute__((always_inline))
float hash21(thread float2& p)
{
    p = fract(p * float2(123.339996337890625, 456.209991455078125));
    p += float2(dot(p, p + float2(45.31999969482421875)));
    return fract(p.x * p.y);
}

static inline __attribute__((always_inline))
float valueNoise(thread const float2& p)
{
    float2 i = floor(p);
    float2 f = fract(p);
    f = (f * f) * (float2(3.0) - (f * 2.0));
    float2 param = i + float2(0.0);
    float _168 = hash21(param);
    float a = _168;
    float2 param_1 = i + float2(1.0, 0.0);
    float _174 = hash21(param_1);
    float b = _174;
    float2 param_2 = i + float2(0.0, 1.0);
    float _180 = hash21(param_2);
    float c2 = _180;
    float2 param_3 = i + float2(1.0);
    float _186 = hash21(param_3);
    float d = _186;
    return mix(mix(a, b, f.x), mix(c2, d, f.x), f.y);
}

static inline __attribute__((always_inline))
float fbm(thread float2& p)
{
    float v = 0.0;
    float a = 0.5;
    for (int i = 0; i < 5; i++)
    {
        float2 param = p;
        v += (a * valueNoise(param));
        p *= 2.0;
        a *= 0.5;
    }
    return v;
}

static inline __attribute__((always_inline))
float4 PortalFlame(thread const bool& transparentCenter, constant Common& U, thread float2& vUV)
{
    float2 cv = vUV - float2(0.5);
    float radial = length(cv) / 0.5;
    if (radial > 1.0)
    {
        discard_fragment();
    }
    float angle = precise::atan2(cv.y, cv.x);
    float t = U.uScalarsA_.x;
    float2 ringCW = float2(cos(angle + (t * 0.12999999523162841796875)), sin(angle + (t * 0.12999999523162841796875)));
    float2 ringCCW = float2(cos(angle - (t * 0.07999999821186065673828125)), sin(angle - (t * 0.07999999821186065673828125)));
    float2 param = (ringCW * 1.7000000476837158203125) + float2(t * 0.180000007152557373046875, 0.0);
    float _294 = fbm(param);
    float2 param_1 = (ringCW * 1.7000000476837158203125) + float2(0.0, (t * 0.180000007152557373046875) + 31.3999996185302734375);
    float _304 = fbm(param_1);
    float2 warp = float2(_294, _304) * 0.300000011920928955078125;
    float2 param_2 = ((ringCW + warp) * 2.400000095367431640625) + float2(t * 0.449999988079071044921875, 0.0);
    float _320 = fbm(param_2);
    float n1 = _320;
    float2 param_3 = (ringCCW * 5.0) + float2(t * 0.800000011920928955078125, 7.30000019073486328125);
    float _332 = fbm(param_3);
    float n2 = _332;
    float2 param_4 = (ringCW * 11.0) + float2(t * 1.2000000476837158203125, 13.1000003814697265625);
    float _344 = fbm(param_4);
    float n3 = _344;
    float flame = ((n1 * 0.550000011920928955078125) + (n2 * 0.300000011920928955078125)) + (n3 * 0.1500000059604644775390625);
    flame = smoothstep(0.300000011920928955078125, 0.75, flame);
    float baseIntensity = smoothstep(0.699999988079071044921875, 1.0, radial);
    baseIntensity = powr(baseIntensity, 1.4500000476837158203125);
    float brightnessMod = mix(0.7799999713897705078125, 1.0, flame);
    float intensity = baseIntensity * brightnessMod;
    float2 lineRing = float2(cos(angle), sin(angle)) * 4.5;
    float2 param_5 = lineRing + float2(t * 0.550000011920928955078125, 0.0);
    float lineNoise = valueNoise(param_5);
    float lineMask = smoothstep(0.7200000286102294921875, 0.920000016689300537109375, lineNoise);
    float lineRadialFade = smoothstep(0.449999988079071044921875, 0.819999992847442626953125, radial) * (1.0 - smoothstep(0.920000016689300537109375, 1.0, radial));
    intensity += ((lineMask * lineRadialFade) * 0.180000007152557373046875);
    float crestArg = (radial - 0.930000007152557373046875) / 0.02500000037252902984619140625;
    float crest = exp((-crestArg) * crestArg);
    float3 col;
    if (intensity < 0.3499999940395355224609375)
    {
        col = mix(U.uColorDark_.xyz, U.uPortalColor_.xyz, float3(intensity / 0.3499999940395355224609375));
    }
    else
    {
        if (intensity < 0.75)
        {
            col = mix(U.uPortalColor_.xyz, U.uColorHot_.xyz, float3((intensity - 0.3499999940395355224609375) / 0.4000000059604644775390625));
        }
        else
        {
            col = U.uColorHot_.xyz;
        }
    }
    col = mix(col, U.uColorHot_.xyz * 1.17999994754791259765625, float3(crest * 0.64999997615814208984375));
    float brightnessPulse = 0.949999988079071044921875 + (0.0500000007450580596923828125 * sin(t * 1.2000000476837158203125));
    col *= brightnessPulse;
    if (U.uScalarsB_.w > 0.001000000047497451305389404296875)
    {
        col = mix(col, U.uColorHot_.xyz * 1.60000002384185791015625, float3(U.uScalarsB_.w * 0.85000002384185791015625));
    }
    if (transparentCenter)
    {
        float a = intensity * U.uColorDark_.w;
        if (U.uScalarsA_.z > 0.001000000047497451305389404296875)
        {
            float spiral1 = sin(((angle * 3.0) + (radial * 8.0)) + (t * 0.550000011920928955078125));
            float spiral2 = sin(((angle * 5.0) - (radial * 6.0)) - (t * 0.4000000059604644775390625));
            float vortex = ((spiral1 + spiral2) * 0.25) + 0.5;
            float radialFade = smoothstep(0.0, 0.3499999940395355224609375, radial);
            vortex = mix(0.4000000059604644775390625, 1.0, vortex * radialFade);
            float3 staticCol = U.uColorDark_.xyz * mix(0.119999997317790985107421875, 0.4199999868869781494140625, vortex);
            return float4(mix(col, staticCol, float3(1.0 - a)) * (a + U.uScalarsA_.z), fast::max(a, U.uScalarsA_.z));
        }
        return float4(col, a);
    }
    else
    {
        float spiral1_1 = sin(((angle * 3.0) + (radial * 8.0)) + (t * 0.550000011920928955078125));
        float spiral2_1 = sin(((angle * 5.0) - (radial * 6.0)) - (t * 0.4000000059604644775390625));
        float vortex_1 = ((spiral1_1 + spiral2_1) * 0.25) + 0.5;
        float radialFade_1 = smoothstep(0.0, 0.3499999940395355224609375, radial);
        vortex_1 = mix(0.4000000059604644775390625, 1.0, vortex_1 * radialFade_1);
        float3 centerCol = U.uColorDark_.xyz * mix(0.119999997317790985107421875, 0.4199999868869781494140625, vortex_1);
        float3 finalCol = mix(centerCol, col, float3(intensity * U.uColorDark_.w));
        return float4(finalCol, 1.0);
    }
}

fragment portal_vk_frag_out portal_vk_frag(portal_vk_frag_in in [[stage_in]], constant Common& U [[buffer(1)]], texture2d<float> uPortalNoiseTex [[texture(0)]], texture2d<float> uPortalColorTex [[texture(1)]], sampler uPortalNoiseTexSmplr [[sampler(0)]], sampler uPortalColorTexSmplr [[sampler(1)]], float4 gl_FragCoord [[position]])
{
    portal_vk_frag_out out = {};
    if (U.uScalarsB_.y > 0.5)
    {
        out.gl_FragDepth = 1.0;
    }
    else
    {
        out.gl_FragDepth = gl_FragCoord.z;
    }
    if (U.uScalarsB_.z > 2.5)
    {
        out.FragColor = float4(U.uFogColor_.xyz, surfaceFogValue(in.vWorldPos, U) * U.uFogColor_.w);
        return out;
    }
    if (U.uScalarsB_.z > 1.5)
    {
        float4 _877;
        if (U.uScalarsD_.z > 0.5)
        {
            bool param = false;
            float4 _882 = PortalRefract(param, U, in.vUV, uPortalNoiseTex, uPortalNoiseTexSmplr, in.vNoiseUV, uPortalColorTex, uPortalColorTexSmplr);
            _877 = _882;
        }
        else
        {
            bool param_1 = false;
            float4 _885 = PortalFlame(param_1, U, in.vUV);
            _877 = _885;
        }
        out.FragColor = _877;
    }
    else
    {
        if (U.uScalarsB_.z > 0.5)
        {
            float4 _896;
            if (U.uScalarsD_.z > 0.5)
            {
                bool param_2 = true;
                float4 _901 = PortalRefract(param_2, U, in.vUV, uPortalNoiseTex, uPortalNoiseTexSmplr, in.vNoiseUV, uPortalColorTex, uPortalColorTexSmplr);
                _896 = _901;
            }
            else
            {
                bool param_3 = true;
                float4 _904 = PortalFlame(param_3, U, in.vUV);
                _896 = _904;
            }
            out.FragColor = _896;
        }
        else
        {
            float2 c = in.vUV - float2(0.5);
            float dist = length(c) * 2.0;
            float solidOpen = smoothstep(0.0, 1.0, fast::clamp(U.uColorDark_.w, 0.0, 1.0));
            float solidOpenSq = solidOpen * solidOpen;
            if (dist > solidOpenSq)
            {
                discard_fragment();
            }
            out.FragColor = float4(U.uPortalColor_.xyz, 1.0);
        }
    }
    return out;
}

