// Generated by tools/gen_metal_shaders.py from shaders/post_color_convolve_vk.frag.spv — do not edit.
// spirv-sha256: cf0d6c3e19e5505b59f5955bd045f67f71d42b499ab1ade9eff201d88c384102
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uPostParams;
    float2 uInSize;
    float uInBilinear;
    float uAuxBilinear;
    float2 uAuxSize;
    float2 _pad0;
    float2 _pad1;
    float2 uOutSize;
    float4 uScalars;
};

struct post_color_convolve_vk_frag_out
{
    float4 fragColor [[color(0)]];
};

struct post_color_convolve_vk_frag_in
{
    float2 texCoord [[user(locn0)]];
};

static inline __attribute__((always_inline))
float4 SampleIn(thread float2& uv, constant PushConstants& pc, texture2d<float> uInSampler, sampler uInSamplerSmplr)
{
    if (pc.uInBilinear < 0.5)
    {
        uv = (floor(uv * pc.uInSize) + float2(0.5)) / pc.uInSize;
    }
    return uInSampler.sample(uInSamplerSmplr, float2(uv.x, 1.0 - uv.y));
}

fragment post_color_convolve_vk_frag_out post_color_convolve_vk_frag(post_color_convolve_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], texture2d<float> uInSampler [[texture(0)]], sampler uInSamplerSmplr [[sampler(0)]])
{
    post_color_convolve_vk_frag_out out = {};
    float2 param = in.texCoord;
    float4 _65 = SampleIn(param, pc, uInSampler, uInSamplerSmplr);
    float4 InTexel = _65;
    float RedValue = dot(InTexel.xyz, pc.uPostParams[0].xyz);
    float GreenValue = dot(InTexel.xyz, pc.uPostParams[1].xyz);
    float BlueValue = dot(InTexel.xyz, pc.uPostParams[2].xyz);
    float3 OutColor = float3(RedValue, GreenValue, BlueValue);
    float Luma = dot(OutColor, float3(0.300000011920928955078125, 0.589999973773956298828125, 0.10999999940395355224609375));
    float3 Chroma = OutColor - float3(Luma);
    OutColor = (Chroma * 1.7999999523162841796875) + float3(Luma);
    out.fragColor = float4(OutColor, 1.0);
    return out;
}

