// Generated by tools/gen_metal_shaders.py from shaders/post_box_blur_vk.frag.spv — do not edit.
// spirv-sha256: 979f621115e6f82f4df9f92bdbb06b01c78f48bfa360136b6efd8d702bb1d345
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uPostParams;
    float2 uInSize;
    float uInBilinear;
    float uAuxBilinear;
    float2 uAuxSize;
    float2 _pad0;
    float2 _pad1;
    float2 uOutSize;
    float4 uScalars;
};

struct post_box_blur_vk_frag_out
{
    float4 fragColor [[color(0)]];
};

struct post_box_blur_vk_frag_in
{
    float2 texCoord [[user(locn0)]];
};

static inline __attribute__((always_inline))
float4 SampleIn(thread float2& uv, constant PushConstants& pc, texture2d<float> uInSampler, sampler uInSamplerSmplr)
{
    if (pc.uInBilinear < 0.5)
    {
        uv = (floor(uv * pc.uInSize) + float2(0.5)) / pc.uInSize;
    }
    return uInSampler.sample(uInSamplerSmplr, float2(uv.x, 1.0 - uv.y));
}

fragment post_box_blur_vk_frag_out post_box_blur_vk_frag(post_box_blur_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], texture2d<float> uInSampler [[texture(0)]], sampler uInSamplerSmplr [[sampler(0)]])
{
    post_box_blur_vk_frag_out out = {};
    float2 BlurDir = pc.uPostParams[0].xy;
    float Radius = pc.uPostParams[0].z;
    float2 oneTexel = float2(1.0) / pc.uInSize;
    float2 sampleStep = oneTexel * BlurDir;
    float4 blurred = float4(0.0);
    float _85;
    if (Radius >= 0.5)
    {
        _85 = round(Radius);
    }
    else
    {
        _85 = pc.uScalars.x;
    }
    float actualRadius = _85;
    float _98 = (-actualRadius) + 0.5;
    for (float a = _98; a <= actualRadius; a += 2.0)
    {
        float2 param = in.texCoord + (sampleStep * a);
        float4 _115 = SampleIn(param, pc, uInSampler, uInSamplerSmplr);
        blurred += _115;
    }
    float2 param_1 = in.texCoord + (sampleStep * actualRadius);
    float4 _127 = SampleIn(param_1, pc, uInSampler, uInSamplerSmplr);
    blurred += (_127 / float4(2.0));
    out.fragColor = blurred / float4(actualRadius + 0.5);
    return out;
}

