// Generated by tools/gen_metal_shaders.py from shaders/post_screenquad_vk.vert.spv — do not edit.
// spirv-sha256: 371c9d6b9ed0e00003cb32719cb8796265ef7ffee5a2f6d4b07d35435404c1ca
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct post_screenquad_vk_vert_out
{
    float2 texCoord [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct post_screenquad_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float2 aUV [[attribute(1)]];
};

vertex post_screenquad_vk_vert_out post_screenquad_vk_vert(post_screenquad_vk_vert_in in [[stage_in]])
{
    post_screenquad_vk_vert_out out = {};
    out.gl_Position = float4(in.aPos.xy, 0.0, 1.0);
    out.texCoord = in.aUV;
    return out;
}

