// Generated by tools/gen_metal_shaders.py from shaders/post_rotscale_vk.vert.spv — do not edit.
// spirv-sha256: 3b01da763554a6e80b244439498c8c341fe6f12646470e7faadba0850ba04b27
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uPostParams;
};

struct post_rotscale_vk_vert_out
{
    float2 texCoord [[user(locn0)]];
    float2 scaledCoord [[user(locn1)]];
    float4 gl_Position [[position]];
};

struct post_rotscale_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float2 aUV [[attribute(1)]];
};

vertex post_rotscale_vk_vert_out post_rotscale_vk_vert(post_rotscale_vk_vert_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]])
{
    post_rotscale_vk_vert_out out = {};
    out.gl_Position = float4(in.aPos.xy, 0.0, 1.0);
    out.texCoord = in.aUV;
    float2 InScale = pc.uPostParams[0].xy;
    float2 InOffset = pc.uPostParams[0].zw;
    float InRotation = pc.uPostParams[1].x;
    float Deg2Rad = 0.01745329238474369049072265625;
    float InRadians = InRotation * Deg2Rad;
    float Cosine = cos(InRadians);
    float Sine = sin(InRadians);
    float RotU = (out.texCoord.x * Cosine) - (out.texCoord.y * Sine);
    float RotV = (out.texCoord.y * Cosine) + (out.texCoord.x * Sine);
    out.scaledCoord = (float2(RotU, RotV) * InScale) + InOffset;
    return out;
}

