// Generated by tools/gen_metal_shaders.py from shaders/scene_upscale_vk.frag.spv — do not edit.
// spirv-sha256: a0f0f3db8e16627fb3b2d9a47e69b22c85a3c248c71b10641d10478111b53dfc
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct scene_upscale_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct scene_upscale_vk_frag_in
{
    float2 vUV [[user(locn0)]];
};

fragment scene_upscale_vk_frag_out scene_upscale_vk_frag(scene_upscale_vk_frag_in in [[stage_in]], texture2d<float> uScene [[texture(0)]], sampler uSceneSmplr [[sampler(0)]])
{
    scene_upscale_vk_frag_out out = {};
    out.FragColor = uScene.sample(uSceneSmplr, in.vUV);
    return out;
}

