// Generated by tools/gen_metal_shaders.py from shaders/scene_upscale_vk.vert.spv — do not edit.
// spirv-sha256: 162e805c6356c73bee7ee18a0ea73df03b49f7b5ae1b920e844d6455fb18b6d0
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct scene_upscale_vk_vert_out
{
    float2 vUV [[user(locn0)]];
    float4 gl_Position [[position]];
};

vertex scene_upscale_vk_vert_out scene_upscale_vk_vert(uint gl_VertexIndex [[vertex_id]])
{
    scene_upscale_vk_vert_out out = {};
    float2 p = float2(float((int(gl_VertexIndex) << 1) & 2), float(int(gl_VertexIndex) & 2));
    out.vUV = p;
    out.gl_Position = float4((p * 2.0) - float2(1.0), 0.0, 1.0);
    return out;
}

