// Generated by tools/gen_metal_shaders.py from shaders/sky_block_vk.frag.spv — do not edit.
// spirv-sha256: 6dece845601b1e83d113e5c757988611bdc41066193ba43d997afa0c830dec2c
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct sky_block_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

fragment sky_block_vk_frag_out sky_block_vk_frag()
{
    sky_block_vk_frag_out out = {};
    out.FragColor = float4(0.0);
    return out;
}

