// Generated by tools/gen_metal_shaders.py from shaders/sky_vk.frag.spv — do not edit.
// spirv-sha256: 14446aacd8d9b0cf198b75501620e55ec9a2c9766f533bf53f959a3b93277104
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uColor;
};

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
};

struct sky_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct sky_vk_frag_in
{
    float2 vUV [[user(locn0)]];
    float4 vColor [[user(locn1)]];
    float vSph [[user(locn2)]];
    float vCyl [[user(locn3)]];
};

static inline __attribute__((always_inline))
float linearFog(thread const float& d, thread const float& s, thread const float& e)
{
    if (d <= s)
    {
        return 0.0;
    }
    if (d >= e)
    {
        return 1.0;
    }
    return (d - s) / (e - s);
}

fragment sky_vk_frag_out sky_vk_frag(sky_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], constant Common& U [[buffer(1)]], texture2d<float> uTexture [[texture(0)]], sampler uTextureSmplr [[sampler(0)]])
{
    sky_vk_frag_out out = {};
    float4 color = (uTexture.sample(uTextureSmplr, in.vUV) * in.vColor) * pc.uColor;
    if (color.w == 0.0)
    {
        discard_fragment();
    }
    float param = in.vSph;
    float param_1 = U.uFogEnv_.x;
    float param_2 = U.uFogEnv_.y;
    float param_3 = in.vCyl;
    float param_4 = U.uFogEnv_.z;
    float param_5 = U.uFogEnv_.w;
    float fogValue = fast::max(linearFog(param, param_1, param_2), linearFog(param_3, param_4, param_5));
    out.FragColor = float4(mix(color.xyz, U.uFogColor_.xyz, float3(fogValue * U.uFogColor_.w)), color.w);
    return out;
}

