// Generated by tools/gen_metal_shaders.py from shaders/terrain_solid_oit_tr_vk.frag.spv — do not edit.
// spirv-sha256: fee09984676c2236bcf6ccfa06b567f9e16a5c52cf54e230d88258d125f9f537
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct FaceRecord
{
    float3 color;
    int aoCodes;
    int sprite;
    int texel;
};

struct OitParams
{
    float4 OitProjParams;
};

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 uSpriteArray_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
    float4 uOverlayColor_;
};

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
};

struct terrain_solid_oit_tr_vk_frag_out
{
    float4 oitCoeffOut_0 [[color(0)]];
    float4 oitCoeffOut_1 [[color(1)]];
};

struct terrain_solid_oit_tr_vk_frag_in
{
    float2 fragTexCoord [[user(locn0)]];
    float4 fragColor [[user(locn2)]];
    int fragSprite [[user(locn3)]];
    int fragRecord [[user(locn4)]];
    int fragAux [[user(locn5)]];
};

static inline __attribute__((always_inline))
FaceRecord fetchFaceRecord(thread const float2& uv, thread int& fragSprite, thread int& fragRecord, texture_buffer<uint> uFaceMap)
{
    int w = fragSprite & 31;
    int h = (fragSprite >> 5) & 31;
    int tv0 = (fragSprite >> 10) & 15;
    int tu0 = (fragSprite >> 14) & 15;
    int2 cell = clamp(int2(floor(uv)) - int2(tu0, tv0), int2(0), int2(w - 1, h - 1));
    int texel = fragRecord + (2 * (cell.x + (cell.y * w)));
    int4 t = int4(uFaceMap.read(uint(texel)));
    FaceRecord r;
    r.color = float3(int3(t.x & 255, t.x >> 8, t.y & 255)) * 0.0039215688593685626983642578125;
    r.aoCodes = t.y >> 8;
    r.sprite = t.z;
    r.texel = texel;
    return r;
}

static inline __attribute__((always_inline))
float4 sampleTerrainAtlas(thread const int& sprite, thread const float2& uv, thread int& fragSprite, constant Common& U, texture2d_array<float> uSpriteArray, sampler uSpriteArraySmplr, texture2d_array<float> uSpriteArray2, sampler uSpriteArray2Smplr, texture2d<float> uSpriteTable, sampler uSpriteTableSmplr, texture2d<float> uTextureAtlas, sampler uTextureAtlasSmplr)
{
    float2 texDx = dfdx(uv);
    float2 texDy = dfdy(uv);
    if (fragSprite >= 0)
    {
        if (sprite < int(U.uSpriteArray_.x))
        {
            int cap = int(U.uSpriteArray_.y);
            if (sprite < cap)
            {
                float3 _468 = float3(uv, float(sprite));
                return uSpriteArray.sample(uSpriteArraySmplr, _468.xy, uint(rint(_468.z)));
            }
            float3 _480 = float3(uv, float(sprite - cap));
            return uSpriteArray2.sample(uSpriteArray2Smplr, _480.xy, uint(rint(_480.z)));
        }
        float4 rect = uSpriteTable.read(uint2(int2(sprite & 255, sprite >> 8)), 0);
        float2 atlasUV = rect.xy + (fract(uv) * rect.zw);
        return uTextureAtlas.sample(uTextureAtlasSmplr, atlasUV, gradient2d(texDx * rect.zw, texDy * rect.zw));
    }
    return uTextureAtlas.sample(uTextureAtlasSmplr, uv);
}

static inline __attribute__((always_inline))
float3 sampleLightmap(thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr)
{
    return uLightmap.sample(uLightmapSmplr, ((uv * 0.00390625) + float2(0.03125))).xyz;
}

static inline __attribute__((always_inline))
float4 shadedVertexColor(thread const bool& mapped, thread const FaceRecord& rec, thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr, thread int& fragSprite, texture_buffer<uint> uFaceMap, constant Common& U, thread float4& fragColor)
{
    float4 c = fragColor;
    bool _524 = fragSprite >= 0;
    bool _531;
    if (_524)
    {
        _531 = (fragSprite & 131072) != 0;
    }
    else
    {
        _531 = _524;
    }
    if (_531)
    {
        c.w = 1.0;
    }
    if (mapped)
    {
        int codes = rec.aoCodes;
        float a00 = 1.0 - (0.20000000298023223876953125 * float(codes & 3));
        float a10 = 1.0 - (0.20000000298023223876953125 * float((codes >> 2) & 3));
        float a01 = 1.0 - (0.20000000298023223876953125 * float((codes >> 4) & 3));
        float a11 = 1.0 - (0.20000000298023223876953125 * float((codes >> 6) & 3));
        float2 f = fract(uv);
        bool lower = (f.x + f.y) <= 1.0;
        float fx = f.x;
        float fy = f.y;
        float3 lit;
        if (U.uScalarsD_.w > 0.5)
        {
            int4 L = int4(uFaceMap.read(uint((rec.texel + 1))));
            float2 param = float2(float(L.x & 255), float(L.x >> 8));
            float3 c00 = sampleLightmap(param, uLightmap, uLightmapSmplr) * a00;
            float2 param_1 = float2(float(L.y & 255), float(L.y >> 8));
            float3 c10 = sampleLightmap(param_1, uLightmap, uLightmapSmplr) * a10;
            float2 param_2 = float2(float(L.z & 255), float(L.z >> 8));
            float3 c01 = sampleLightmap(param_2, uLightmap, uLightmapSmplr) * a01;
            float2 param_3 = float2(float(L.w & 255), float(L.w >> 8));
            float3 c11 = sampleLightmap(param_3, uLightmap, uLightmapSmplr) * a11;
            float3 _659;
            if (lower)
            {
                _659 = (c00 + ((c10 - c00) * fx)) + ((c01 - c00) * fy);
            }
            else
            {
                _659 = (c11 + ((c10 - c11) * (1.0 - fy))) + ((c01 - c11) * (1.0 - fx));
            }
            lit = _659;
        }
        else
        {
            float _694;
            if (lower)
            {
                _694 = (a00 + ((a10 - a00) * fx)) + ((a01 - a00) * fy);
            }
            else
            {
                _694 = (a11 + ((a10 - a11) * (1.0 - fy))) + ((a01 - a11) * (1.0 - fx));
            }
            lit = float3(_694);
        }
        float3 _731 = rec.color * lit;
        c.x = _731.x;
        c.y = _731.y;
        c.z = _731.z;
        c.w = 1.0;
    }
    return c;
}

static inline __attribute__((always_inline))
float toAbsorbance(thread const float& transmittance)
{
    return fast::clamp(-log(fast::max(transmittance, 9.9999997473787516355514526367188e-05)), 0.0, 4.0);
}

static inline __attribute__((always_inline))
float deviceToLinearDepth(thread const float& deviceDepth, constant OitParams& _79)
{
    float ndc = (deviceDepth - 0.5) * 2.0;
    return _79.OitProjParams.y / (ndc + _79.OitProjParams.x);
}

static inline __attribute__((always_inline))
float normalizeDepth(thread const float& fragmentDeviceDepth, constant OitParams& _79, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord)
{
    float4 depthBoundsSample = DepthBoundsSampler.read(uint2(int2(gl_FragCoord.xy)), 0);
    float closestBoundLinearDepthNegated = depthBoundsSample.x;
    float closestBoundLinearDepth = -closestBoundLinearDepthNegated;
    float furthestBoundLinearDepth = depthBoundsSample.y;
    float param = fragmentDeviceDepth;
    float fragmentLinearDepth = deviceToLinearDepth(param, _79);
    float range = fast::max(furthestBoundLinearDepth - closestBoundLinearDepth, 9.9999997473787516355514526367188e-05);
    float depthWithinBounds = fast::clamp(fragmentLinearDepth - closestBoundLinearDepth, 0.0, range);
    float depthWithHighPrecision = 0.75 * range;
    if (depthWithHighPrecision <= 10.0)
    {
        return depthWithinBounds / range;
    }
    else
    {
        if (depthWithinBounds <= 10.0)
        {
            return (depthWithinBounds / 10.0) * 0.75;
        }
        else
        {
            return 0.75 + (((depthWithinBounds - 10.0) / (range - 10.0)) * 0.25);
        }
    }
}

static inline __attribute__((always_inline))
void addTransmittance(thread const float& transmittance, constant OitParams& _79, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord, thread spvUnsafeArray<float4, 2>& oitCoeffOut)
{
    spvUnsafeArray<float, 8> coefficients;
    for (int i = 0; i < 8; i++)
    {
        coefficients[i] = 0.0;
    }
    float param = transmittance;
    float absorbance = toAbsorbance(param);
    float param_1 = gl_FragCoord.z;
    float originalDepth = normalizeDepth(param_1, _79, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord);
    float depth = (originalDepth * 7.0) / 8.0;
    float averageAbsorbance = absorbance * (1.0 - depth);
    coefficients[0] = averageAbsorbance;
    int depthBinIndex = int(floor(originalDepth * 7.0));
    int treeIndex = depthBinIndex + 8;
    for (int waveletLevel = 0; waveletLevel <= 2; waveletLevel++)
    {
        int power = 2 - waveletLevel;
        int parentIndex = treeIndex >> 1;
        float indexAtParentLevel = float(parentIndex & ((1 << power) - 1));
        int isRightHalf = treeIndex & 1;
        int waveletSign = 1 - (isRightHalf << 1);
        float waveletWidth = exp2(-float(power));
        float waveletHeightScale = exp2(float(power) * 0.5);
        float depthOffsetRelativeToWavelet = depth - (waveletWidth * indexAtParentLevel);
        float distanceFromWaveletEdge = (float(isRightHalf) * waveletWidth) + (float(waveletSign) * depthOffsetRelativeToWavelet);
        float differenceCoefficient = (distanceFromWaveletEdge * waveletHeightScale) * absorbance;
        coefficients[parentIndex] = differenceCoefficient;
        treeIndex = parentIndex;
    }
    for (int attachmentIndex = 0; attachmentIndex < 2; attachmentIndex++)
    {
        oitCoeffOut[attachmentIndex] = float4(coefficients[(attachmentIndex * 4) + 0], coefficients[(attachmentIndex * 4) + 1], coefficients[(attachmentIndex * 4) + 2], coefficients[(attachmentIndex * 4) + 3]);
    }
}

static inline __attribute__((always_inline))
void executeAlphaOnlyPhase(thread const float& deviceDepth, thread const float& alpha, constant OitParams& _79, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord, thread spvUnsafeArray<float4, 2>& oitCoeffOut)
{
    float param = 1.0 - alpha;
    addTransmittance(param, _79, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord, oitCoeffOut);
}

fragment terrain_solid_oit_tr_vk_frag_out terrain_solid_oit_tr_vk_frag(terrain_solid_oit_tr_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], constant Common& U [[buffer(1)]], constant OitParams& _79 [[buffer(4)]], texture2d<float> uTextureAtlas [[texture(0)]], texture2d<float> uSpriteTable [[texture(1)]], texture_buffer<uint> uFaceMap [[texture(2)]], texture2d<float> uLightmap [[texture(3)]], texture2d<float> DepthBoundsSampler [[texture(4)]], texture2d_array<float> uSpriteArray [[texture(7)]], texture2d_array<float> uSpriteArray2 [[texture(8)]], sampler uTextureAtlasSmplr [[sampler(0)]], sampler uSpriteTableSmplr [[sampler(1)]], sampler uLightmapSmplr [[sampler(3)]], sampler DepthBoundsSamplerSmplr [[sampler(4)]], sampler uSpriteArraySmplr [[sampler(7)]], sampler uSpriteArray2Smplr [[sampler(8)]], float4 gl_FragCoord [[position]])
{
    terrain_solid_oit_tr_vk_frag_out out = {};
    spvUnsafeArray<float4, 2> oitCoeffOut = {};
    bool _744 = in.fragSprite >= 0;
    bool _751;
    if (_744)
    {
        _751 = (in.fragSprite & 262144) != 0;
    }
    else
    {
        _751 = _744;
    }
    bool mapped = _751;
    float2 uv = in.fragTexCoord;
    bool _757 = in.fragSprite >= 0;
    bool _763;
    if (_757)
    {
        _763 = (in.fragSprite & 131072) != 0;
    }
    else
    {
        _763 = _757;
    }
    if (_763)
    {
        if ((in.fragAux & 256) != 0)
        {
            float sum = float(in.fragAux & 63) / 16.0;
            int mode = (in.fragAux >> 6) & 3;
            if (mode == 0)
            {
                uv.x = sum - uv.x;
            }
            else
            {
                if (mode == 1)
                {
                    uv.y = sum - uv.y;
                }
            }
        }
    }
    FaceRecord rec = FaceRecord{ float3(1.0), 0, 0, 0 };
    if (mapped)
    {
        float2 param = uv;
        rec = fetchFaceRecord(param, in.fragSprite, in.fragRecord, uFaceMap);
    }
    int _814;
    if (mapped)
    {
        _814 = rec.sprite;
    }
    else
    {
        _814 = in.fragSprite & 65535;
    }
    int param_1 = _814;
    float2 param_2 = uv;
    float4 textureColor = sampleTerrainAtlas(param_1, param_2, in.fragSprite, U, uSpriteArray, uSpriteArraySmplr, uSpriteArray2, uSpriteArray2Smplr, uSpriteTable, uSpriteTableSmplr, uTextureAtlas, uTextureAtlasSmplr);
    bool _841;
    if (!mapped)
    {
        bool _834 = in.fragSprite >= 0;
        bool _840;
        if (_834)
        {
            _840 = (in.fragSprite & 131072) != 0;
        }
        else
        {
            _840 = _834;
        }
        _841 = _840;
    }
    else
    {
        _841 = mapped;
    }
    float _842;
    if (_841)
    {
        _842 = 1.0;
    }
    else
    {
        _842 = in.fragColor.w;
    }
    float vertexAlpha = _842;
    float alpha = textureColor.w * vertexAlpha;
    if (alpha < pc.uAlphaTest)
    {
        discard_fragment();
    }
    bool param_3 = mapped;
    FaceRecord param_4 = rec;
    float2 param_5 = uv;
    float4 vcol = shadedVertexColor(param_3, param_4, param_5, uLightmap, uLightmapSmplr, in.fragSprite, uFaceMap, U, in.fragColor);
    float param_6 = gl_FragCoord.z;
    float param_7 = alpha;
    executeAlphaOnlyPhase(param_6, param_7, _79, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord, oitCoeffOut);
    out.oitCoeffOut_0 = oitCoeffOut[0];
    out.oitCoeffOut_1 = oitCoeffOut[1];
    return out;
}

