// Generated by tools/gen_metal_shaders.py from shaders/terrain_solid_oit_db_vk.frag.spv — do not edit.
// spirv-sha256: 6924c56cadd8a843fb484a8ce09875af10e630cd49d1ae625ec7cad215087bd7
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct FaceRecord
{
    float3 color;
    int aoCodes;
    int sprite;
    int texel;
};

struct OitParams
{
    float4 OitProjParams;
};

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 uSpriteArray_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
    float4 uOverlayColor_;
};

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
};

struct terrain_solid_oit_db_vk_frag_out
{
    float4 oitDepthBoundsOut [[color(0)]];
};

struct terrain_solid_oit_db_vk_frag_in
{
    float2 fragTexCoord [[user(locn0)]];
    float4 fragColor [[user(locn2)]];
    int fragSprite [[user(locn3)]];
    int fragRecord [[user(locn4)]];
    int fragAux [[user(locn5)]];
};

static inline __attribute__((always_inline))
FaceRecord fetchFaceRecord(thread const float2& uv, thread int& fragSprite, thread int& fragRecord, texture_buffer<uint> uFaceMap)
{
    int w = fragSprite & 31;
    int h = (fragSprite >> 5) & 31;
    int tv0 = (fragSprite >> 10) & 15;
    int tu0 = (fragSprite >> 14) & 15;
    int2 cell = clamp(int2(floor(uv)) - int2(tu0, tv0), int2(0), int2(w - 1, h - 1));
    int texel = fragRecord + (2 * (cell.x + (cell.y * w)));
    int4 t = int4(uFaceMap.read(uint(texel)));
    FaceRecord r;
    r.color = float3(int3(t.x & 255, t.x >> 8, t.y & 255)) * 0.0039215688593685626983642578125;
    r.aoCodes = t.y >> 8;
    r.sprite = t.z;
    r.texel = texel;
    return r;
}

static inline __attribute__((always_inline))
float4 sampleTerrainAtlas(thread const int& sprite, thread const float2& uv, thread int& fragSprite, constant Common& U, texture2d_array<float> uSpriteArray, sampler uSpriteArraySmplr, texture2d_array<float> uSpriteArray2, sampler uSpriteArray2Smplr, texture2d<float> uSpriteTable, sampler uSpriteTableSmplr, texture2d<float> uTextureAtlas, sampler uTextureAtlasSmplr)
{
    float2 texDx = dfdx(uv);
    float2 texDy = dfdy(uv);
    if (fragSprite >= 0)
    {
        if (sprite < int(U.uSpriteArray_.x))
        {
            int cap = int(U.uSpriteArray_.y);
            if (sprite < cap)
            {
                float3 _262 = float3(uv, float(sprite));
                return uSpriteArray.sample(uSpriteArraySmplr, _262.xy, uint(rint(_262.z)));
            }
            float3 _274 = float3(uv, float(sprite - cap));
            return uSpriteArray2.sample(uSpriteArray2Smplr, _274.xy, uint(rint(_274.z)));
        }
        float4 rect = uSpriteTable.read(uint2(int2(sprite & 255, sprite >> 8)), 0);
        float2 atlasUV = rect.xy + (fract(uv) * rect.zw);
        return uTextureAtlas.sample(uTextureAtlasSmplr, atlasUV, gradient2d(texDx * rect.zw, texDy * rect.zw));
    }
    return uTextureAtlas.sample(uTextureAtlasSmplr, uv);
}

static inline __attribute__((always_inline))
float3 sampleLightmap(thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr)
{
    return uLightmap.sample(uLightmapSmplr, ((uv * 0.00390625) + float2(0.03125))).xyz;
}

static inline __attribute__((always_inline))
float4 shadedVertexColor(thread const bool& mapped, thread const FaceRecord& rec, thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr, thread int& fragSprite, texture_buffer<uint> uFaceMap, constant Common& U, thread float4& fragColor)
{
    float4 c = fragColor;
    bool _320 = fragSprite >= 0;
    bool _327;
    if (_320)
    {
        _327 = (fragSprite & 131072) != 0;
    }
    else
    {
        _327 = _320;
    }
    if (_327)
    {
        c.w = 1.0;
    }
    if (mapped)
    {
        int codes = rec.aoCodes;
        float a00 = 1.0 - (0.20000000298023223876953125 * float(codes & 3));
        float a10 = 1.0 - (0.20000000298023223876953125 * float((codes >> 2) & 3));
        float a01 = 1.0 - (0.20000000298023223876953125 * float((codes >> 4) & 3));
        float a11 = 1.0 - (0.20000000298023223876953125 * float((codes >> 6) & 3));
        float2 f = fract(uv);
        bool lower = (f.x + f.y) <= 1.0;
        float fx = f.x;
        float fy = f.y;
        float3 lit;
        if (U.uScalarsD_.w > 0.5)
        {
            int4 L = int4(uFaceMap.read(uint((rec.texel + 1))));
            float2 param = float2(float(L.x & 255), float(L.x >> 8));
            float3 c00 = sampleLightmap(param, uLightmap, uLightmapSmplr) * a00;
            float2 param_1 = float2(float(L.y & 255), float(L.y >> 8));
            float3 c10 = sampleLightmap(param_1, uLightmap, uLightmapSmplr) * a10;
            float2 param_2 = float2(float(L.z & 255), float(L.z >> 8));
            float3 c01 = sampleLightmap(param_2, uLightmap, uLightmapSmplr) * a01;
            float2 param_3 = float2(float(L.w & 255), float(L.w >> 8));
            float3 c11 = sampleLightmap(param_3, uLightmap, uLightmapSmplr) * a11;
            float3 _456;
            if (lower)
            {
                _456 = (c00 + ((c10 - c00) * fx)) + ((c01 - c00) * fy);
            }
            else
            {
                _456 = (c11 + ((c10 - c11) * (1.0 - fy))) + ((c01 - c11) * (1.0 - fx));
            }
            lit = _456;
        }
        else
        {
            float _491;
            if (lower)
            {
                _491 = (a00 + ((a10 - a00) * fx)) + ((a01 - a00) * fy);
            }
            else
            {
                _491 = (a11 + ((a10 - a11) * (1.0 - fy))) + ((a01 - a11) * (1.0 - fx));
            }
            lit = float3(_491);
        }
        float3 _528 = rec.color * lit;
        c.x = _528.x;
        c.y = _528.y;
        c.z = _528.z;
        c.w = 1.0;
    }
    return c;
}

static inline __attribute__((always_inline))
float deviceToLinearDepth(thread const float& deviceDepth, constant OitParams& _73)
{
    float ndc = (deviceDepth - 0.5) * 2.0;
    return _73.OitProjParams.y / (ndc + _73.OitProjParams.x);
}

static inline __attribute__((always_inline))
void calculateDepthBounds(thread const float& fragmentDeviceDepth, thread const float& alpha, constant OitParams& _73, thread float4& oitDepthBoundsOut)
{
    float param = fragmentDeviceDepth;
    float fragmentLinearDepth = deviceToLinearDepth(param, _73);
    float nearness = 1.0 - fragmentDeviceDepth;
    float opaqueNearness = (alpha > 0.9900000095367431640625) ? nearness : 0.0;
    oitDepthBoundsOut = float4(-fragmentLinearDepth, fragmentLinearDepth, nearness, opaqueNearness);
}

static inline __attribute__((always_inline))
void executeAlphaOnlyPhase(thread const float& deviceDepth, thread const float& alpha, constant OitParams& _73, thread float4& oitDepthBoundsOut)
{
    if (alpha < 0.00999999977648258209228515625)
    {
        discard_fragment();
    }
    float param = deviceDepth;
    float param_1 = alpha;
    calculateDepthBounds(param, param_1, _73, oitDepthBoundsOut);
}

fragment terrain_solid_oit_db_vk_frag_out terrain_solid_oit_db_vk_frag(terrain_solid_oit_db_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], constant Common& U [[buffer(1)]], constant OitParams& _73 [[buffer(4)]], texture2d<float> uTextureAtlas [[texture(0)]], texture2d<float> uSpriteTable [[texture(1)]], texture_buffer<uint> uFaceMap [[texture(2)]], texture2d<float> uLightmap [[texture(3)]], texture2d_array<float> uSpriteArray [[texture(7)]], texture2d_array<float> uSpriteArray2 [[texture(8)]], sampler uTextureAtlasSmplr [[sampler(0)]], sampler uSpriteTableSmplr [[sampler(1)]], sampler uLightmapSmplr [[sampler(3)]], sampler uSpriteArraySmplr [[sampler(7)]], sampler uSpriteArray2Smplr [[sampler(8)]], float4 gl_FragCoord [[position]])
{
    terrain_solid_oit_db_vk_frag_out out = {};
    bool _541 = in.fragSprite >= 0;
    bool _548;
    if (_541)
    {
        _548 = (in.fragSprite & 262144) != 0;
    }
    else
    {
        _548 = _541;
    }
    bool mapped = _548;
    float2 uv = in.fragTexCoord;
    bool _554 = in.fragSprite >= 0;
    bool _560;
    if (_554)
    {
        _560 = (in.fragSprite & 131072) != 0;
    }
    else
    {
        _560 = _554;
    }
    if (_560)
    {
        if ((in.fragAux & 256) != 0)
        {
            float sum = float(in.fragAux & 63) / 16.0;
            int mode = (in.fragAux >> 6) & 3;
            if (mode == 0)
            {
                uv.x = sum - uv.x;
            }
            else
            {
                if (mode == 1)
                {
                    uv.y = sum - uv.y;
                }
            }
        }
    }
    FaceRecord rec = FaceRecord{ float3(1.0), 0, 0, 0 };
    if (mapped)
    {
        float2 param = uv;
        rec = fetchFaceRecord(param, in.fragSprite, in.fragRecord, uFaceMap);
    }
    int _611;
    if (mapped)
    {
        _611 = rec.sprite;
    }
    else
    {
        _611 = in.fragSprite & 65535;
    }
    int param_1 = _611;
    float2 param_2 = uv;
    float4 textureColor = sampleTerrainAtlas(param_1, param_2, in.fragSprite, U, uSpriteArray, uSpriteArraySmplr, uSpriteArray2, uSpriteArray2Smplr, uSpriteTable, uSpriteTableSmplr, uTextureAtlas, uTextureAtlasSmplr);
    bool _638;
    if (!mapped)
    {
        bool _631 = in.fragSprite >= 0;
        bool _637;
        if (_631)
        {
            _637 = (in.fragSprite & 131072) != 0;
        }
        else
        {
            _637 = _631;
        }
        _638 = _637;
    }
    else
    {
        _638 = mapped;
    }
    float _639;
    if (_638)
    {
        _639 = 1.0;
    }
    else
    {
        _639 = in.fragColor.w;
    }
    float vertexAlpha = _639;
    float alpha = textureColor.w * vertexAlpha;
    if (alpha < pc.uAlphaTest)
    {
        discard_fragment();
    }
    bool param_3 = mapped;
    FaceRecord param_4 = rec;
    float2 param_5 = uv;
    float4 vcol = shadedVertexColor(param_3, param_4, param_5, uLightmap, uLightmapSmplr, in.fragSprite, uFaceMap, U, in.fragColor);
    float param_6 = gl_FragCoord.z;
    float param_7 = alpha;
    executeAlphaOnlyPhase(param_6, param_7, _73, out.oitDepthBoundsOut);
    return out;
}

