// Generated by tools/gen_metal_shaders.py from shaders/terrain_solid_oit_ac_f16_vk.frag.spv — do not edit.
// spirv-sha256: 5f1dbbadf4244d3f1a9fef90370970b95660d312c0ca72b6029f75ba2208a249
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct FaceRecord
{
    half3 color;
    int aoCodes;
    int sprite;
    int texel;
};

struct OitParams
{
    float4 OitProjParams;
};

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 uSpriteArray_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
    float4 uOverlayColor_;
};

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
};

struct terrain_solid_oit_ac_f16_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct terrain_solid_oit_ac_f16_vk_frag_in
{
    float2 fragTexCoord [[user(locn0)]];
    half2 fragFog [[user(locn1)]];
    half4 fragColor [[user(locn2)]];
    int fragSprite [[user(locn3)]];
    int fragRecord [[user(locn4)]];
    int fragAux [[user(locn5)]];
};

static inline __attribute__((always_inline))
FaceRecord fetchFaceRecord(thread const float2& uv, thread int& fragSprite, thread int& fragRecord, texture_buffer<uint> uFaceMap)
{
    int w = fragSprite & 31;
    int h = (fragSprite >> 5) & 31;
    int tv0 = (fragSprite >> 10) & 15;
    int tu0 = (fragSprite >> 14) & 15;
    int2 cell = clamp(int2(floor(uv)) - int2(tu0, tv0), int2(0), int2(w - 1, h - 1));
    int texel = fragRecord + (2 * (cell.x + (cell.y * w)));
    int4 t = int4(uFaceMap.read(uint(texel)));
    FaceRecord r;
    r.color = half3(int3(t.x & 255, t.x >> 8, t.y & 255)) * half(0.0039215087890625);
    r.aoCodes = t.y >> 8;
    r.sprite = t.z;
    r.texel = texel;
    return r;
}

static inline __attribute__((always_inline))
half4 sampleTerrainAtlas(thread const int& sprite, thread const float2& uv, thread int& fragSprite, constant Common& U, texture2d_array<float> uSpriteArray, sampler uSpriteArraySmplr, texture2d_array<float> uSpriteArray2, sampler uSpriteArray2Smplr, texture2d<float> uSpriteTable, sampler uSpriteTableSmplr, texture2d<float> uTextureAtlas, sampler uTextureAtlasSmplr)
{
    float2 texDx = dfdx(uv);
    float2 texDy = dfdy(uv);
    if (fragSprite >= 0)
    {
        if (sprite < int(U.uSpriteArray_.x))
        {
            int cap = int(U.uSpriteArray_.y);
            if (sprite < cap)
            {
                float3 _631 = float3(uv, float(sprite));
                return half4(uSpriteArray.sample(uSpriteArraySmplr, _631.xy, uint(rint(_631.z))));
            }
            float3 _644 = float3(uv, float(sprite - cap));
            return half4(uSpriteArray2.sample(uSpriteArray2Smplr, _644.xy, uint(rint(_644.z))));
        }
        float4 rect = uSpriteTable.read(uint2(int2(sprite & 255, sprite >> 8)), 0);
        float2 atlasUV = rect.xy + (fract(uv) * rect.zw);
        return half4(uTextureAtlas.sample(uTextureAtlasSmplr, atlasUV, gradient2d(texDx * rect.zw, texDy * rect.zw)));
    }
    return half4(uTextureAtlas.sample(uTextureAtlasSmplr, uv));
}

static inline __attribute__((always_inline))
half3 sampleLightmap(thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr)
{
    return half3(uLightmap.sample(uLightmapSmplr, ((uv * 0.00390625) + float2(0.03125))).xyz);
}

static inline __attribute__((always_inline))
half4 shadedVertexColor(thread const bool& mapped, thread const FaceRecord& rec, thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr, thread int& fragSprite, texture_buffer<uint> uFaceMap, constant Common& U, thread half4& fragColor)
{
    half4 c = fragColor;
    bool _693 = fragSprite >= 0;
    bool _700;
    if (_693)
    {
        _700 = (fragSprite & 131072) != 0;
    }
    else
    {
        _700 = _693;
    }
    if (_700)
    {
        c.w = half(1.0);
    }
    if (mapped)
    {
        int codes = rec.aoCodes;
        half a00 = half(1.0) - (half(0.199951171875) * half(codes & 3));
        half a10 = half(1.0) - (half(0.199951171875) * half((codes >> 2) & 3));
        half a01 = half(1.0) - (half(0.199951171875) * half((codes >> 4) & 3));
        half a11 = half(1.0) - (half(0.199951171875) * half((codes >> 6) & 3));
        float2 f = fract(uv);
        bool lower = (f.x + f.y) <= 1.0;
        half fx = half(f.x);
        half fy = half(f.y);
        half3 lit;
        if (U.uScalarsD_.w > 0.5)
        {
            int4 L = int4(uFaceMap.read(uint((rec.texel + 1))));
            float2 param = float2(float(L.x & 255), float(L.x >> 8));
            half3 c00 = sampleLightmap(param, uLightmap, uLightmapSmplr) * a00;
            float2 param_1 = float2(float(L.y & 255), float(L.y >> 8));
            half3 c10 = sampleLightmap(param_1, uLightmap, uLightmapSmplr) * a10;
            float2 param_2 = float2(float(L.z & 255), float(L.z >> 8));
            half3 c01 = sampleLightmap(param_2, uLightmap, uLightmapSmplr) * a01;
            float2 param_3 = float2(float(L.w & 255), float(L.w >> 8));
            half3 c11 = sampleLightmap(param_3, uLightmap, uLightmapSmplr) * a11;
            half3 _830;
            if (lower)
            {
                _830 = (c00 + ((c10 - c00) * fx)) + ((c01 - c00) * fy);
            }
            else
            {
                _830 = (c11 + ((c10 - c11) * (half(1.0) - fy))) + ((c01 - c11) * (half(1.0) - fx));
            }
            lit = _830;
        }
        else
        {
            half _865;
            if (lower)
            {
                _865 = (a00 + ((a10 - a00) * fx)) + ((a01 - a00) * fy);
            }
            else
            {
                _865 = (a11 + ((a10 - a11) * (half(1.0) - fy))) + ((a01 - a11) * (half(1.0) - fx));
            }
            lit = half3(_865);
        }
        half3 _902 = rec.color * lit;
        c.x = _902.x;
        c.y = _902.y;
        c.z = _902.z;
        c.w = half(1.0);
    }
    return c;
}

static inline __attribute__((always_inline))
float linearFog(thread const float& d, thread const float& s, thread const float& e)
{
    if (d <= s)
    {
        return 0.0;
    }
    if (d >= e)
    {
        return 1.0;
    }
    return (d - s) / (e - s);
}

static inline __attribute__((always_inline))
float deviceToLinearDepth(thread const float& deviceDepth, constant OitParams& _106)
{
    float ndc = (deviceDepth - 0.5) * 2.0;
    return _106.OitProjParams.y / (ndc + _106.OitProjParams.x);
}

static inline __attribute__((always_inline))
float normalizeDepth(thread const float& fragmentDeviceDepth, constant OitParams& _106, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord)
{
    float4 depthBoundsSample = DepthBoundsSampler.read(uint2(int2(gl_FragCoord.xy)), 0);
    float closestBoundLinearDepthNegated = depthBoundsSample.x;
    float closestBoundLinearDepth = -closestBoundLinearDepthNegated;
    float furthestBoundLinearDepth = depthBoundsSample.y;
    float param = fragmentDeviceDepth;
    float fragmentLinearDepth = deviceToLinearDepth(param, _106);
    float range = fast::max(furthestBoundLinearDepth - closestBoundLinearDepth, 9.9999997473787516355514526367188e-05);
    float depthWithinBounds = fast::clamp(fragmentLinearDepth - closestBoundLinearDepth, 0.0, range);
    float depthWithHighPrecision = 0.75 * range;
    if (depthWithHighPrecision <= 10.0)
    {
        return depthWithinBounds / range;
    }
    else
    {
        if (depthWithinBounds <= 10.0)
        {
            return (depthWithinBounds / 10.0) * 0.75;
        }
        else
        {
            return 0.75 + (((depthWithinBounds - 10.0) / (range - 10.0)) * 0.25);
        }
    }
}

static inline __attribute__((always_inline))
float toAbsorbance(thread const float& transmittance)
{
    return fast::clamp(-log(fast::max(transmittance, 9.9999997473787516355514526367188e-05)), 0.0, 4.0);
}

static inline __attribute__((always_inline))
float sampleAbsorbance(thread const spvUnsafeArray<float, 8>& coefficients, thread const float& originalDepth, thread const float& currentAbsorbance)
{
    float averageAbsorbance = coefficients[0];
    if (averageAbsorbance == 0.0)
    {
        return 0.0;
    }
    float depthMeasuredInBins = originalDepth * 7.0;
    float depth = depthMeasuredInBins / 8.0;
    float currentAverageAbsorbanceContribution = currentAbsorbance * (1.0 - depth);
    averageAbsorbance -= currentAverageAbsorbanceContribution;
    int treeIndexB = clamp(int(floor(depthMeasuredInBins)), 0, 7);
    bool shouldSampleA = treeIndexB >= 1;
    int _240;
    if (shouldSampleA)
    {
        _240 = treeIndexB - 1;
    }
    else
    {
        _240 = treeIndexB;
    }
    int treeIndexA = _240;
    treeIndexB += 8;
    treeIndexA += 8;
    float sampleB = averageAbsorbance;
    float sampleA = shouldSampleA ? averageAbsorbance : 0.0;
    float _344;
    for (int waveletLevel = 0; waveletLevel <= 2; waveletLevel++)
    {
        int power = 2 - waveletLevel;
        float waveletWidth = exp2(-float(power));
        float waveletHeightScale = exp2(float(power) * 0.5);
        int parentIndexB = treeIndexB >> 1;
        int isRightHalfB = treeIndexB & 1;
        int waveletSignB = 1 - (isRightHalfB << 1);
        float indexAtParentLevel = float(parentIndexB & ((1 << power) - 1));
        float depthOffsetRelativeToWavelet = depth - (waveletWidth * indexAtParentLevel);
        float currentDifferenceCoefficient = (((float(isRightHalfB) * waveletWidth) + (float(waveletSignB) * depthOffsetRelativeToWavelet)) * waveletHeightScale) * currentAbsorbance;
        float differenceCoefficientB = coefficients[parentIndexB];
        differenceCoefficientB -= currentDifferenceCoefficient;
        sampleB -= ((waveletHeightScale * differenceCoefficientB) * float(waveletSignB));
        treeIndexB = parentIndexB;
        if (shouldSampleA)
        {
            int parentIndexA = treeIndexA >> 1;
            if (parentIndexA == parentIndexB)
            {
                _344 = differenceCoefficientB;
            }
            else
            {
                _344 = coefficients[parentIndexA];
            }
            float differenceCoefficientA = _344;
            int isRightHalfA = treeIndexA & 1;
            int waveletSignA = 1 - (isRightHalfA << 1);
            sampleA -= ((waveletHeightScale * differenceCoefficientA) * float(waveletSignA));
            treeIndexA = parentIndexA;
        }
    }
    float _374;
    if (depthMeasuredInBins >= 8.0)
    {
        _374 = 1.0;
    }
    else
    {
        _374 = fract(depthMeasuredInBins);
    }
    float lerpAlpha = _374;
    return mix(sampleA, sampleB, lerpAlpha);
}

static inline __attribute__((always_inline))
float toTransmittance(thread const float& absorbance)
{
    return fast::clamp(exp(-absorbance), 9.9999997473787516355514526367188e-05, 1.0);
}

static inline __attribute__((always_inline))
float sampleTransmittance(thread const int2& pos, thread const float& depth, thread const float& currentTransmittance, texture2d<float> Coeff0, sampler Coeff0Smplr, texture2d<float> Coeff1, sampler Coeff1Smplr)
{
    float4 c0 = Coeff0.read(uint2(pos), 0);
    float4 c1 = Coeff1.read(uint2(pos), 0);
    spvUnsafeArray<float, 8> coefficients;
    coefficients[0] = c0.x;
    coefficients[1] = c0.y;
    coefficients[2] = c0.z;
    coefficients[3] = c0.w;
    coefficients[4] = c1.x;
    coefficients[5] = c1.y;
    coefficients[6] = c1.z;
    coefficients[7] = c1.w;
    float param = currentTransmittance;
    spvUnsafeArray<float, 8> param_1 = coefficients;
    float param_2 = depth;
    float param_3 = toAbsorbance(param);
    float param_4 = sampleAbsorbance(param_1, param_2, param_3);
    return toTransmittance(param_4);
}

static inline __attribute__((always_inline))
float4 sampleColorForAccumulation(thread const float4& color, constant OitParams& _106, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord, texture2d<float> Coeff0, sampler Coeff0Smplr, texture2d<float> Coeff1, sampler Coeff1Smplr)
{
    float transmittance = 1.0 - color.w;
    float accumAlpha = color.w;
    float param = gl_FragCoord.z;
    int2 param_1 = int2(gl_FragCoord.xy);
    float param_2 = normalizeDepth(param, _106, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord);
    float param_3 = transmittance;
    float sampledTransmittance = sampleTransmittance(param_1, param_2, param_3, Coeff0, Coeff0Smplr, Coeff1, Coeff1Smplr);
    return float4(color.xyz * color.w, accumAlpha) * sampledTransmittance;
}

fragment terrain_solid_oit_ac_f16_vk_frag_out terrain_solid_oit_ac_f16_vk_frag(terrain_solid_oit_ac_f16_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], constant Common& U [[buffer(1)]], constant OitParams& _106 [[buffer(4)]], texture2d<float> uTextureAtlas [[texture(0)]], texture2d<float> uSpriteTable [[texture(1)]], texture_buffer<uint> uFaceMap [[texture(2)]], texture2d<float> uLightmap [[texture(3)]], texture2d<float> DepthBoundsSampler [[texture(4)]], texture2d<float> Coeff0 [[texture(5)]], texture2d<float> Coeff1 [[texture(6)]], texture2d_array<float> uSpriteArray [[texture(7)]], texture2d_array<float> uSpriteArray2 [[texture(8)]], sampler uTextureAtlasSmplr [[sampler(0)]], sampler uSpriteTableSmplr [[sampler(1)]], sampler uLightmapSmplr [[sampler(3)]], sampler DepthBoundsSamplerSmplr [[sampler(4)]], sampler Coeff0Smplr [[sampler(5)]], sampler Coeff1Smplr [[sampler(6)]], sampler uSpriteArraySmplr [[sampler(7)]], sampler uSpriteArray2Smplr [[sampler(8)]], float4 gl_FragCoord [[position]])
{
    terrain_solid_oit_ac_f16_vk_frag_out out = {};
    bool _915 = in.fragSprite >= 0;
    bool _922;
    if (_915)
    {
        _922 = (in.fragSprite & 262144) != 0;
    }
    else
    {
        _922 = _915;
    }
    bool mapped = _922;
    float2 uv = in.fragTexCoord;
    bool _928 = in.fragSprite >= 0;
    bool _934;
    if (_928)
    {
        _934 = (in.fragSprite & 131072) != 0;
    }
    else
    {
        _934 = _928;
    }
    if (_934)
    {
        if ((in.fragAux & 256) != 0)
        {
            float sum = float(in.fragAux & 63) / 16.0;
            int mode = (in.fragAux >> 6) & 3;
            if (mode == 0)
            {
                uv.x = sum - uv.x;
            }
            else
            {
                if (mode == 1)
                {
                    uv.y = sum - uv.y;
                }
            }
        }
    }
    FaceRecord rec = FaceRecord{ half3(half(1.0)), 0, 0, 0 };
    if (mapped)
    {
        float2 param = uv;
        rec = fetchFaceRecord(param, in.fragSprite, in.fragRecord, uFaceMap);
    }
    int _985;
    if (mapped)
    {
        _985 = rec.sprite;
    }
    else
    {
        _985 = in.fragSprite & 65535;
    }
    int param_1 = _985;
    float2 param_2 = uv;
    half4 textureColor = sampleTerrainAtlas(param_1, param_2, in.fragSprite, U, uSpriteArray, uSpriteArraySmplr, uSpriteArray2, uSpriteArray2Smplr, uSpriteTable, uSpriteTableSmplr, uTextureAtlas, uTextureAtlasSmplr);
    bool _1012;
    if (!mapped)
    {
        bool _1005 = in.fragSprite >= 0;
        bool _1011;
        if (_1005)
        {
            _1011 = (in.fragSprite & 131072) != 0;
        }
        else
        {
            _1011 = _1005;
        }
        _1012 = _1011;
    }
    else
    {
        _1012 = mapped;
    }
    half _1013;
    if (_1012)
    {
        _1013 = half(1.0);
    }
    else
    {
        _1013 = in.fragColor.w;
    }
    half vertexAlpha = _1013;
    float alpha = float(textureColor.w * vertexAlpha);
    if (alpha < pc.uAlphaTest)
    {
        discard_fragment();
    }
    bool param_3 = mapped;
    FaceRecord param_4 = rec;
    float2 param_5 = uv;
    half4 vcol = shadedVertexColor(param_3, param_4, param_5, uLightmap, uLightmapSmplr, in.fragSprite, uFaceMap, U, in.fragColor);
    half3 finalColor = textureColor.xyz * vcol.xyz;
    if (U.uFogColor_.w > 0.0)
    {
        float param_6 = float(in.fragFog.x);
        float param_7 = U.uFogEnv_.x;
        float param_8 = U.uFogEnv_.y;
        float param_9 = float(in.fragFog.y);
        float param_10 = U.uFogEnv_.z;
        float param_11 = U.uFogEnv_.w;
        float fogValue = fast::max(linearFog(param_6, param_7, param_8), linearFog(param_9, param_10, param_11));
        finalColor = mix(finalColor, half3(U.uFogColor_.xyz), half3(half(fogValue * U.uFogColor_.w)));
    }
    finalColor = mix(half3(U.uFogColor_.xyz), finalColor, half3(half(float((in.fragAux >> 16) & 255) * 0.0039215688593685626983642578125)));
    finalColor = mix(finalColor, half3(U.uOverlayColor_.xyz), half3(half(U.uOverlayColor_.w)));
    out.FragColor = float4(float3(finalColor), alpha);
    float4 param_12 = out.FragColor;
    out.FragColor = sampleColorForAccumulation(param_12, _106, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord, Coeff0, Coeff0Smplr, Coeff1, Coeff1Smplr);
    return out;
}

