// Generated by tools/gen_metal_shaders.py from shaders/terrain_solid_oit_tr_vk.frag.spv — do not edit.
// spirv-sha256: 9b66332a21468ae71470d22e54e0032500ed6baea40aadf1a258d9dab385b53c
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct FaceRecord
{
    float3 color;
    int aoCodes;
    int sprite;
    uint2 lights;
};

struct OitParams
{
    float4 OitProjParams;
};

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 uSpriteArray_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
    float4 uOverlayColor_;
    int4 uRenderOrigin_;
    float4 uTerrainLight_;
};

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
};

struct terrain_solid_oit_tr_vk_frag_out
{
    float4 oitCoeffOut_0 [[color(0)]];
    float4 oitCoeffOut_1 [[color(1)]];
};

struct terrain_solid_oit_tr_vk_frag_in
{
    float2 fragTexCoord [[user(locn0)]];
    float4 fragColor [[user(locn2)]];
    int fragSprite [[user(locn3)]];
    int fragRecord [[user(locn4)]];
    int fragAux [[user(locn5)]];
};

static inline __attribute__((always_inline))
FaceRecord fetchFaceRecord(thread const float2& uv, thread int& fragSprite, texture_buffer<uint> uFaceMap, thread int& fragRecord)
{
    int w = fragSprite & 31;
    int h = (fragSprite >> 5) & 31;
    int tv0 = (fragSprite >> 10) & 15;
    int tu0 = (fragSprite >> 14) & 15;
    int2 cell = clamp(int2(floor(uv)) - int2(tu0, tv0), int2(0), int2(w - 1, h - 1));
    uint4 t = uFaceMap.read(uint(((fragRecord + cell.x) + (cell.y * w))));
    FaceRecord r;
    r.color = float3(int3(int(t.x & 255u), int((t.x >> uint(8)) & 255u), int((t.x >> uint(16)) & 255u))) * 0.0039215688593685626983642578125;
    r.aoCodes = int(t.x >> uint(24));
    r.sprite = int(t.y & 65535u);
    r.lights = t.zw;
    return r;
}

static inline __attribute__((always_inline))
float4 sampleTerrainAtlas(thread const int& sprite, thread const float2& uv, thread int& fragSprite, constant Common& U, texture2d_array<float> uSpriteArray, sampler uSpriteArraySmplr, texture2d_array<float> uSpriteArray2, sampler uSpriteArray2Smplr, texture2d<float> uSpriteTable, sampler uSpriteTableSmplr, texture2d<float> uTextureAtlas, sampler uTextureAtlasSmplr)
{
    float2 texDx = dfdx(uv);
    float2 texDy = dfdy(uv);
    if (fragSprite >= 0)
    {
        if (sprite < int(U.uSpriteArray_.x))
        {
            int cap = int(U.uSpriteArray_.y);
            if (sprite < cap)
            {
                float3 _479 = float3(uv, float(sprite));
                return uSpriteArray.sample(uSpriteArraySmplr, _479.xy, uint(rint(_479.z)));
            }
            float3 _491 = float3(uv, float(sprite - cap));
            return uSpriteArray2.sample(uSpriteArray2Smplr, _491.xy, uint(rint(_491.z)));
        }
        float4 rect = uSpriteTable.read(uint2(int2(sprite & 255, sprite >> 8)), 0);
        float2 atlasUV = rect.xy + (fract(uv) * rect.zw);
        return uTextureAtlas.sample(uTextureAtlasSmplr, atlasUV, gradient2d(texDx * rect.zw, texDy * rect.zw));
    }
    return uTextureAtlas.sample(uTextureAtlasSmplr, uv);
}

static inline __attribute__((always_inline))
float3 sampleLightmap(thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr)
{
    return uLightmap.sample(uLightmapSmplr, ((uv * 0.00390625) + float2(0.03125))).xyz;
}

static inline __attribute__((always_inline))
float4 shadedVertexColor(thread const bool& mapped, thread const FaceRecord& rec, thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr, thread int& fragSprite, constant Common& U, thread float4& fragColor)
{
    float4 c = fragColor;
    bool _536 = fragSprite >= 0;
    bool _543;
    if (_536)
    {
        _543 = (fragSprite & 131072) != 0;
    }
    else
    {
        _543 = _536;
    }
    if (_543)
    {
        c.w = 1.0;
    }
    if (mapped)
    {
        int codes = rec.aoCodes;
        float a00 = 1.0 - (0.20000000298023223876953125 * float(codes & 3));
        float a10 = 1.0 - (0.20000000298023223876953125 * float((codes >> 2) & 3));
        float a01 = 1.0 - (0.20000000298023223876953125 * float((codes >> 4) & 3));
        float a11 = 1.0 - (0.20000000298023223876953125 * float((codes >> 6) & 3));
        float2 f = fract(uv);
        bool lower = (f.x + f.y) <= 1.0;
        float fx = f.x;
        float fy = f.y;
        float3 lit;
        if (U.uScalarsD_.w > 0.5)
        {
            int4 L = int4(int(rec.lights.x & 65535u), int(rec.lights.x >> uint(16)), int(rec.lights.y & 65535u), int(rec.lights.y >> uint(16)));
            float2 l00 = float2(float(L.x & 255), float(L.x >> 8));
            float2 l10 = float2(float(L.y & 255), float(L.y >> 8));
            float2 l01 = float2(float(L.z & 255), float(L.z >> 8));
            float2 l11 = float2(float(L.w & 255), float(L.w >> 8));
            int lightMode = int(U.uTerrainLight_.x);
            if (lightMode == 0)
            {
                float2 param = l00;
                float3 c00 = sampleLightmap(param, uLightmap, uLightmapSmplr) * a00;
                float2 param_1 = l10;
                float3 c10 = sampleLightmap(param_1, uLightmap, uLightmapSmplr) * a10;
                float2 param_2 = l01;
                float3 c01 = sampleLightmap(param_2, uLightmap, uLightmapSmplr) * a01;
                float2 param_3 = l11;
                float3 c11 = sampleLightmap(param_3, uLightmap, uLightmapSmplr) * a11;
                float3 _699;
                if (lower)
                {
                    _699 = (c00 + ((c10 - c00) * fx)) + ((c01 - c00) * fy);
                }
                else
                {
                    _699 = (c11 + ((c10 - c11) * (1.0 - fy))) + ((c01 - c11) * (1.0 - fx));
                }
                lit = _699;
            }
            else
            {
                float2 _735;
                if (lower)
                {
                    _735 = (l00 + ((l10 - l00) * f.x)) + ((l01 - l00) * f.y);
                }
                else
                {
                    _735 = (l11 + ((l10 - l11) * (1.0 - f.y))) + ((l01 - l11) * (1.0 - f.x));
                }
                float2 lc = _735;
                float _774;
                if (lower)
                {
                    _774 = (a00 + ((a10 - a00) * fx)) + ((a01 - a00) * fy);
                }
                else
                {
                    _774 = (a11 + ((a10 - a11) * (1.0 - fy))) + ((a01 - a11) * (1.0 - fx));
                }
                float ao = _774;
                float2 param_4 = lc;
                lit = sampleLightmap(param_4, uLightmap, uLightmapSmplr) * ao;
            }
        }
        else
        {
            float _814;
            if (lower)
            {
                _814 = (a00 + ((a10 - a00) * fx)) + ((a01 - a00) * fy);
            }
            else
            {
                _814 = (a11 + ((a10 - a11) * (1.0 - fy))) + ((a01 - a11) * (1.0 - fx));
            }
            lit = float3(_814);
        }
        float3 _851 = rec.color * lit;
        c.x = _851.x;
        c.y = _851.y;
        c.z = _851.z;
        c.w = 1.0;
    }
    return c;
}

static inline __attribute__((always_inline))
float toAbsorbance(thread const float& transmittance)
{
    return fast::clamp(-log(fast::max(transmittance, 9.9999997473787516355514526367188e-05)), 0.0, 4.0);
}

static inline __attribute__((always_inline))
float deviceToLinearDepth(thread const float& deviceDepth, constant OitParams& _81)
{
    float ndc = (deviceDepth - 0.5) * 2.0;
    return _81.OitProjParams.y / (ndc + _81.OitProjParams.x);
}

static inline __attribute__((always_inline))
float normalizeDepth(thread const float& fragmentDeviceDepth, constant OitParams& _81, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord)
{
    float4 depthBoundsSample = DepthBoundsSampler.read(uint2(int2(gl_FragCoord.xy)), 0);
    float closestBoundLinearDepthNegated = depthBoundsSample.x;
    float closestBoundLinearDepth = -closestBoundLinearDepthNegated;
    float furthestBoundLinearDepth = depthBoundsSample.y;
    float param = fragmentDeviceDepth;
    float fragmentLinearDepth = deviceToLinearDepth(param, _81);
    float range = fast::max(furthestBoundLinearDepth - closestBoundLinearDepth, 9.9999997473787516355514526367188e-05);
    float depthWithinBounds = fast::clamp(fragmentLinearDepth - closestBoundLinearDepth, 0.0, range);
    float depthWithHighPrecision = 0.75 * range;
    if (depthWithHighPrecision <= 10.0)
    {
        return depthWithinBounds / range;
    }
    else
    {
        if (depthWithinBounds <= 10.0)
        {
            return (depthWithinBounds / 10.0) * 0.75;
        }
        else
        {
            return 0.75 + (((depthWithinBounds - 10.0) / (range - 10.0)) * 0.25);
        }
    }
}

static inline __attribute__((always_inline))
void addTransmittance(thread const float& transmittance, constant OitParams& _81, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord, thread spvUnsafeArray<float4, 2>& oitCoeffOut)
{
    spvUnsafeArray<float, 8> coefficients;
    for (int i = 0; i < 8; i++)
    {
        coefficients[i] = 0.0;
    }
    float param = transmittance;
    float absorbance = toAbsorbance(param);
    float param_1 = gl_FragCoord.z;
    float originalDepth = normalizeDepth(param_1, _81, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord);
    float depth = (originalDepth * 7.0) / 8.0;
    float averageAbsorbance = absorbance * (1.0 - depth);
    coefficients[0] = averageAbsorbance;
    int depthBinIndex = int(floor(originalDepth * 7.0));
    int treeIndex = depthBinIndex + 8;
    for (int waveletLevel = 0; waveletLevel <= 2; waveletLevel++)
    {
        int power = 2 - waveletLevel;
        int parentIndex = treeIndex >> 1;
        float indexAtParentLevel = float(parentIndex & ((1 << power) - 1));
        int isRightHalf = treeIndex & 1;
        int waveletSign = 1 - (isRightHalf << 1);
        float waveletWidth = exp2(-float(power));
        float waveletHeightScale = exp2(float(power) * 0.5);
        float depthOffsetRelativeToWavelet = depth - (waveletWidth * indexAtParentLevel);
        float distanceFromWaveletEdge = (float(isRightHalf) * waveletWidth) + (float(waveletSign) * depthOffsetRelativeToWavelet);
        float differenceCoefficient = (distanceFromWaveletEdge * waveletHeightScale) * absorbance;
        coefficients[parentIndex] = differenceCoefficient;
        treeIndex = parentIndex;
    }
    for (int attachmentIndex = 0; attachmentIndex < 2; attachmentIndex++)
    {
        oitCoeffOut[attachmentIndex] = float4(coefficients[(attachmentIndex * 4) + 0], coefficients[(attachmentIndex * 4) + 1], coefficients[(attachmentIndex * 4) + 2], coefficients[(attachmentIndex * 4) + 3]);
    }
}

static inline __attribute__((always_inline))
void executeAlphaOnlyPhase(thread const float& deviceDepth, thread const float& alpha, constant OitParams& _81, texture2d<float> DepthBoundsSampler, sampler DepthBoundsSamplerSmplr, thread float4& gl_FragCoord, thread spvUnsafeArray<float4, 2>& oitCoeffOut)
{
    float param = 1.0 - alpha;
    addTransmittance(param, _81, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord, oitCoeffOut);
}

fragment terrain_solid_oit_tr_vk_frag_out terrain_solid_oit_tr_vk_frag(terrain_solid_oit_tr_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], constant Common& U [[buffer(1)]], constant OitParams& _81 [[buffer(4)]], texture2d<float> uTextureAtlas [[texture(0)]], texture2d<float> uSpriteTable [[texture(1)]], texture_buffer<uint> uFaceMap [[texture(2)]], texture2d<float> uLightmap [[texture(3)]], texture2d<float> DepthBoundsSampler [[texture(4)]], texture2d_array<float> uSpriteArray [[texture(7)]], texture2d_array<float> uSpriteArray2 [[texture(8)]], sampler uTextureAtlasSmplr [[sampler(0)]], sampler uSpriteTableSmplr [[sampler(1)]], sampler uLightmapSmplr [[sampler(3)]], sampler DepthBoundsSamplerSmplr [[sampler(4)]], sampler uSpriteArraySmplr [[sampler(7)]], sampler uSpriteArray2Smplr [[sampler(8)]], float4 gl_FragCoord [[position]])
{
    terrain_solid_oit_tr_vk_frag_out out = {};
    spvUnsafeArray<float4, 2> oitCoeffOut = {};
    bool _864 = in.fragSprite >= 0;
    bool _871;
    if (_864)
    {
        _871 = (in.fragSprite & 262144) != 0;
    }
    else
    {
        _871 = _864;
    }
    bool mapped = _871;
    float2 uv = in.fragTexCoord;
    bool _877 = in.fragSprite >= 0;
    bool _883;
    if (_877)
    {
        _883 = (in.fragSprite & 131072) != 0;
    }
    else
    {
        _883 = _877;
    }
    if (_883)
    {
        if ((in.fragAux & 256) != 0)
        {
            float sum = float(in.fragAux & 63) / 16.0;
            int mode = (in.fragAux >> 6) & 3;
            if (mode == 0)
            {
                uv.x = sum - uv.x;
            }
            else
            {
                if (mode == 1)
                {
                    uv.y = sum - uv.y;
                }
            }
        }
    }
    FaceRecord rec = FaceRecord{ float3(1.0), 0, 0, uint2(0u) };
    if (mapped)
    {
        float2 param = uv;
        rec = fetchFaceRecord(param, in.fragSprite, uFaceMap, in.fragRecord);
    }
    int _935;
    if (mapped)
    {
        _935 = rec.sprite;
    }
    else
    {
        _935 = in.fragSprite & 65535;
    }
    int param_1 = _935;
    float2 param_2 = uv;
    float4 textureColor = sampleTerrainAtlas(param_1, param_2, in.fragSprite, U, uSpriteArray, uSpriteArraySmplr, uSpriteArray2, uSpriteArray2Smplr, uSpriteTable, uSpriteTableSmplr, uTextureAtlas, uTextureAtlasSmplr);
    bool _962;
    if (!mapped)
    {
        bool _955 = in.fragSprite >= 0;
        bool _961;
        if (_955)
        {
            _961 = (in.fragSprite & 131072) != 0;
        }
        else
        {
            _961 = _955;
        }
        _962 = _961;
    }
    else
    {
        _962 = mapped;
    }
    float _963;
    if (_962)
    {
        _963 = 1.0;
    }
    else
    {
        _963 = in.fragColor.w;
    }
    float vertexAlpha = _963;
    float alpha = textureColor.w * vertexAlpha;
    if (alpha < pc.uAlphaTest)
    {
        discard_fragment();
    }
    bool param_3 = mapped;
    FaceRecord param_4 = rec;
    float2 param_5 = uv;
    float4 vcol = shadedVertexColor(param_3, param_4, param_5, uLightmap, uLightmapSmplr, in.fragSprite, U, in.fragColor);
    float param_6 = gl_FragCoord.z;
    float param_7 = alpha;
    executeAlphaOnlyPhase(param_6, param_7, _81, DepthBoundsSampler, DepthBoundsSamplerSmplr, gl_FragCoord, oitCoeffOut);
    out.oitCoeffOut_0 = oitCoeffOut[0];
    out.oitCoeffOut_1 = oitCoeffOut[1];
    return out;
}

