// Generated by tools/gen_metal_shaders.py from shaders/terrain_cutout_vk.frag.spv — do not edit.
// spirv-sha256: b1ad58c9d236f6326ed323a9d828d9c87a7abf8439029d6e632ae30eb7881f80
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct FaceRecord
{
    float3 color;
    int aoCodes;
    int sprite;
    int texel;
};

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 uSpriteArray_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
    float4 uOverlayColor_;
};

struct PushConstants
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
};

struct terrain_cutout_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct terrain_cutout_vk_frag_in
{
    float2 fragTexCoord [[user(locn0)]];
    float2 fragFog [[user(locn1)]];
    float4 fragColor [[user(locn2)]];
    int fragSprite [[user(locn3)]];
    int fragRecord [[user(locn4)]];
    int fragAux [[user(locn5)]];
};

static inline __attribute__((always_inline))
FaceRecord fetchFaceRecord(thread const float2& uv, thread int& fragSprite, thread int& fragRecord, texture_buffer<uint> uFaceMap)
{
    int w = fragSprite & 31;
    int h = (fragSprite >> 5) & 31;
    int tv0 = (fragSprite >> 10) & 15;
    int tu0 = (fragSprite >> 14) & 15;
    int2 cell = clamp(int2(floor(uv)) - int2(tu0, tv0), int2(0), int2(w - 1, h - 1));
    int texel = fragRecord + (2 * (cell.x + (cell.y * w)));
    int4 t = int4(uFaceMap.read(uint(texel)));
    FaceRecord r;
    r.color = float3(int3(t.x & 255, t.x >> 8, t.y & 255)) * 0.0039215688593685626983642578125;
    r.aoCodes = t.y >> 8;
    r.sprite = t.z;
    r.texel = texel;
    return r;
}

static inline __attribute__((always_inline))
float4 sampleTerrainAtlas(thread const int& sprite, thread const float2& uv, thread int& fragSprite, constant Common& U, texture2d_array<float> uSpriteArray, sampler uSpriteArraySmplr, texture2d_array<float> uSpriteArray2, sampler uSpriteArray2Smplr, texture2d<float> uSpriteTable, sampler uSpriteTableSmplr, texture2d<float> uTextureAtlas, sampler uTextureAtlasSmplr)
{
    float2 texDx = dfdx(uv);
    float2 texDy = dfdy(uv);
    if (fragSprite >= 0)
    {
        if (sprite < int(U.uSpriteArray_.x))
        {
            int cap = int(U.uSpriteArray_.y);
            if (sprite < cap)
            {
                float3 _226 = float3(uv, float(sprite));
                return uSpriteArray.sample(uSpriteArraySmplr, _226.xy, uint(rint(_226.z)));
            }
            float3 _238 = float3(uv, float(sprite - cap));
            return uSpriteArray2.sample(uSpriteArray2Smplr, _238.xy, uint(rint(_238.z)));
        }
        float4 rect = uSpriteTable.read(uint2(int2(sprite & 255, sprite >> 8)), 0);
        float2 atlasUV = rect.xy + (fract(uv) * rect.zw);
        return uTextureAtlas.sample(uTextureAtlasSmplr, atlasUV, gradient2d(texDx * rect.zw, texDy * rect.zw));
    }
    return uTextureAtlas.sample(uTextureAtlasSmplr, uv);
}

static inline __attribute__((always_inline))
float3 sampleLightmap(thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr)
{
    return uLightmap.sample(uLightmapSmplr, ((uv * 0.00390625) + float2(0.03125))).xyz;
}

static inline __attribute__((always_inline))
float4 shadedVertexColor(thread const bool& mapped, thread const FaceRecord& rec, thread const float2& uv, texture2d<float> uLightmap, sampler uLightmapSmplr, thread int& fragSprite, texture_buffer<uint> uFaceMap, constant Common& U, thread float4& fragColor)
{
    float4 c = fragColor;
    bool _284 = fragSprite >= 0;
    bool _291;
    if (_284)
    {
        _291 = (fragSprite & 131072) != 0;
    }
    else
    {
        _291 = _284;
    }
    if (_291)
    {
        c.w = 1.0;
    }
    if (mapped)
    {
        int codes = rec.aoCodes;
        float a00 = 1.0 - (0.20000000298023223876953125 * float(codes & 3));
        float a10 = 1.0 - (0.20000000298023223876953125 * float((codes >> 2) & 3));
        float a01 = 1.0 - (0.20000000298023223876953125 * float((codes >> 4) & 3));
        float a11 = 1.0 - (0.20000000298023223876953125 * float((codes >> 6) & 3));
        float2 f = fract(uv);
        bool lower = (f.x + f.y) <= 1.0;
        float fx = f.x;
        float fy = f.y;
        float3 lit;
        if (U.uScalarsD_.w > 0.5)
        {
            int4 L = int4(uFaceMap.read(uint((rec.texel + 1))));
            float2 param = float2(float(L.x & 255), float(L.x >> 8));
            float3 c00 = sampleLightmap(param, uLightmap, uLightmapSmplr) * a00;
            float2 param_1 = float2(float(L.y & 255), float(L.y >> 8));
            float3 c10 = sampleLightmap(param_1, uLightmap, uLightmapSmplr) * a10;
            float2 param_2 = float2(float(L.z & 255), float(L.z >> 8));
            float3 c01 = sampleLightmap(param_2, uLightmap, uLightmapSmplr) * a01;
            float2 param_3 = float2(float(L.w & 255), float(L.w >> 8));
            float3 c11 = sampleLightmap(param_3, uLightmap, uLightmapSmplr) * a11;
            float3 _421;
            if (lower)
            {
                _421 = (c00 + ((c10 - c00) * fx)) + ((c01 - c00) * fy);
            }
            else
            {
                _421 = (c11 + ((c10 - c11) * (1.0 - fy))) + ((c01 - c11) * (1.0 - fx));
            }
            lit = _421;
        }
        else
        {
            float _456;
            if (lower)
            {
                _456 = (a00 + ((a10 - a00) * fx)) + ((a01 - a00) * fy);
            }
            else
            {
                _456 = (a11 + ((a10 - a11) * (1.0 - fy))) + ((a01 - a11) * (1.0 - fx));
            }
            lit = float3(_456);
        }
        float3 _493 = rec.color * lit;
        c.x = _493.x;
        c.y = _493.y;
        c.z = _493.z;
        c.w = 1.0;
    }
    return c;
}

static inline __attribute__((always_inline))
float linearFog(thread const float& d, thread const float& s, thread const float& e)
{
    if (d <= s)
    {
        return 0.0;
    }
    if (d >= e)
    {
        return 1.0;
    }
    return (d - s) / (e - s);
}

fragment terrain_cutout_vk_frag_out terrain_cutout_vk_frag(terrain_cutout_vk_frag_in in [[stage_in]], constant PushConstants& pc [[buffer(0)]], constant Common& U [[buffer(1)]], texture2d<float> uTextureAtlas [[texture(0)]], texture2d<float> uSpriteTable [[texture(1)]], texture_buffer<uint> uFaceMap [[texture(2)]], texture2d<float> uLightmap [[texture(3)]], texture2d_array<float> uSpriteArray [[texture(7)]], texture2d_array<float> uSpriteArray2 [[texture(8)]], sampler uTextureAtlasSmplr [[sampler(0)]], sampler uSpriteTableSmplr [[sampler(1)]], sampler uLightmapSmplr [[sampler(3)]], sampler uSpriteArraySmplr [[sampler(7)]], sampler uSpriteArray2Smplr [[sampler(8)]])
{
    terrain_cutout_vk_frag_out out = {};
    bool _506 = in.fragSprite >= 0;
    bool _513;
    if (_506)
    {
        _513 = (in.fragSprite & 262144) != 0;
    }
    else
    {
        _513 = _506;
    }
    bool mapped = _513;
    float2 uv = in.fragTexCoord;
    bool _519 = in.fragSprite >= 0;
    bool _525;
    if (_519)
    {
        _525 = (in.fragSprite & 131072) != 0;
    }
    else
    {
        _525 = _519;
    }
    if (_525)
    {
        if ((in.fragAux & 256) != 0)
        {
            float sum = float(in.fragAux & 63) / 16.0;
            int mode = (in.fragAux >> 6) & 3;
            if (mode == 0)
            {
                uv.x = sum - uv.x;
            }
            else
            {
                if (mode == 1)
                {
                    uv.y = sum - uv.y;
                }
            }
        }
    }
    FaceRecord rec = FaceRecord{ float3(1.0), 0, 0, 0 };
    if (mapped)
    {
        float2 param = uv;
        rec = fetchFaceRecord(param, in.fragSprite, in.fragRecord, uFaceMap);
    }
    int _576;
    if (mapped)
    {
        _576 = rec.sprite;
    }
    else
    {
        _576 = in.fragSprite & 65535;
    }
    int param_1 = _576;
    float2 param_2 = uv;
    float4 textureColor = sampleTerrainAtlas(param_1, param_2, in.fragSprite, U, uSpriteArray, uSpriteArraySmplr, uSpriteArray2, uSpriteArray2Smplr, uSpriteTable, uSpriteTableSmplr, uTextureAtlas, uTextureAtlasSmplr);
    if (textureColor.w < pc.uAlphaTest)
    {
        discard_fragment();
    }
    bool param_3 = mapped;
    FaceRecord param_4 = rec;
    float2 param_5 = uv;
    float4 vcol = shadedVertexColor(param_3, param_4, param_5, uLightmap, uLightmapSmplr, in.fragSprite, uFaceMap, U, in.fragColor);
    float3 finalColor = textureColor.xyz * vcol.xyz;
    finalColor = mix(finalColor, U.uOverlayColor_.xyz, float3(U.uOverlayColor_.w));
    if (U.uFogColor_.w > 0.0)
    {
        float param_6 = in.fragFog.x;
        float param_7 = U.uFogEnv_.x;
        float param_8 = U.uFogEnv_.y;
        float param_9 = in.fragFog.y;
        float param_10 = U.uFogEnv_.z;
        float param_11 = U.uFogEnv_.w;
        float fogValue = fast::max(linearFog(param_6, param_7, param_8), linearFog(param_9, param_10, param_11));
        finalColor = mix(finalColor, U.uFogColor_.xyz, float3(fogValue * U.uFogColor_.w));
    }
    finalColor = mix(U.uFogColor_.xyz, finalColor, float3(float((in.fragAux >> 16) & 255) * 0.0039215688593685626983642578125));
    out.FragColor = float4(finalColor, textureColor.w * vcol.w);
    return out;
}

