// Generated by tools/gen_metal_shaders.py from shaders/viewmodel_skinned_vk.vert.spv — do not edit.
// spirv-sha256: 67bca047017f8599523317c8d584eff86265faf77c5f7bef1f33a506a37e7494
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
};

struct Bones
{
    float4x4 uBones_[96];
};

struct viewmodel_skinned_vk_vert_out
{
    float2 vUV [[user(locn0)]];
    float3 vNormalCam [[user(locn1)]];
    float4 gl_Position [[position]];
};

struct viewmodel_skinned_vk_vert_in
{
    float3 aPos [[attribute(0)]];
    float2 aUV [[attribute(1)]];
    float3 aNormal [[attribute(2)]];
    uint4 aJoints [[attribute(3)]];
    float4 aWeights [[attribute(4)]];
};

vertex viewmodel_skinned_vk_vert_out viewmodel_skinned_vk_vert(viewmodel_skinned_vk_vert_in in [[stage_in]], constant Common& U [[buffer(1)]], constant Bones& B [[buffer(2)]])
{
    viewmodel_skinned_vk_vert_out out = {};
    float4 skinned;
    float3 nrm;
    if (U.uScalarsD_.y > 0.5)
    {
        int i0 = int(in.aJoints.x);
        int i1 = int(in.aJoints.y);
        int i2 = int(in.aJoints.z);
        int i3 = int(in.aJoints.w);
        float wSum = ((in.aWeights.x + in.aWeights.y) + in.aWeights.z) + in.aWeights.w;
        float4 w = in.aWeights / float4(fast::max(wSum, 9.9999997473787516355514526367188e-05));
        float4x4 _87 = B.uBones_[i0] * w.x;
        float4x4 _93 = B.uBones_[i1] * w.y;
        float4x4 _106 = float4x4(_87[0] + _93[0], _87[1] + _93[1], _87[2] + _93[2], _87[3] + _93[3]);
        float4x4 _112 = B.uBones_[i2] * w.z;
        float4x4 _125 = float4x4(_106[0] + _112[0], _106[1] + _112[1], _106[2] + _112[2], _106[3] + _112[3]);
        float4x4 _131 = B.uBones_[i3] * w.w;
        float4x4 skin = float4x4(_125[0] + _131[0], _125[1] + _131[1], _125[2] + _131[2], _125[3] + _131[3]);
        skinned = skin * float4(in.aPos, 1.0);
        nrm = fast::normalize(float3x3(skin[0].xyz, skin[1].xyz, skin[2].xyz) * in.aNormal);
    }
    else
    {
        skinned = float4(in.aPos, 1.0);
        nrm = in.aNormal;
    }
    out.gl_Position = U.uMVP_ * skinned;
    out.vUV = in.aUV;
    out.vNormalCam = float3x3(U.uModel_[0].xyz, U.uModel_[1].xyz, U.uModel_[2].xyz) * nrm;
    return out;
}

