// Generated by tools/gen_metal_shaders.py from shaders/weather_half_vk.frag.spv — do not edit.
// spirv-sha256: 4fddab4541e3f5061c8ecc4715beea2d29d7aa82d8fe8b792f079eb5f62a7af1
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PC
{
    float4x4 uMVP;
    float2 uScreenSize;
    float uLineWidth;
    float uAlphaTest;
    float4 uColor;
    float4 uUVRange;
    float4 uScalars;
};

struct Common
{
    float4x4 uMVP_;
    float4x4 uModel_;
    float4 uPortalColor_;
    float4 uColorDark_;
    float4 uColorHot_;
    float4 uKeyDir_;
    float4 uTint_;
    float4 uUVRange_;
    float4 uScalarsA_;
    float4 uScalarsB_;
    float4 uScalarsC_;
    float4 uScalarsD_;
    float2 uScreenSize_;
    float2 _pad_;
    float4 uFogColor_;
    float4 uFogEnv_;
    float4 uCamPosBright_;
};

struct weather_half_vk_frag_out
{
    float4 FragColor [[color(0)]];
};

struct weather_half_vk_frag_in
{
    float2 vUV [[user(locn0)]];
    float4 vColor [[user(locn1)]];
    float3 vRenderPos [[user(locn2)]];
};

static inline __attribute__((always_inline))
float previousDepth(thread const int2& texel, thread const int2& size, texture2d<float> uSceneDepth, sampler uSceneDepthSmplr, constant PC& pc)
{
    bool _51 = any(texel < int2(0));
    bool _59;
    if (!_51)
    {
        _59 = any(texel >= size);
    }
    else
    {
        _59 = _51;
    }
    if (_59)
    {
        return 1.0;
    }
    float d = uSceneDepth.read(uint2(texel), 0).x;
    return (d < pc.uAlphaTest) ? 1.0 : d;
}

static inline __attribute__((always_inline))
float linearFog(thread const float& d, thread const float& s, thread const float& e)
{
    if (d <= s)
    {
        return 0.0;
    }
    if (d >= e)
    {
        return 1.0;
    }
    return (d - s) / (e - s);
}

fragment weather_half_vk_frag_out weather_half_vk_frag(weather_half_vk_frag_in in [[stage_in]], constant PC& pc [[buffer(0)]], constant Common& U [[buffer(1)]], texture2d<float> uSprite [[texture(0)]], texture2d<float> uSceneDepth [[texture(1)]], sampler uSpriteSmplr [[sampler(0)]], sampler uSceneDepthSmplr [[sampler(1)]])
{
    weather_half_vk_frag_out out = {};
    float4 c = uSprite.sample(uSpriteSmplr, in.vUV) * in.vColor;
    if (c.w < 0.100000001490116119384765625)
    {
        discard_fragment();
    }
    float4 clip = U.uModel_ * float4(in.vRenderPos, 1.0);
    if (clip.w > 0.0)
    {
        float3 ndc = clip.xyz / float3(clip.w);
        int2 size = int2(uSceneDepth.get_width(), uSceneDepth.get_height());
        float2 pixel = float2((ndc.x * 0.5) + 0.5, 0.5 - (ndc.y * 0.5)) * float2(size);
        int2 base = int2(floor(pixel - float2(0.5)));
        int2 param = base;
        int2 param_1 = size;
        int2 param_2 = base + int2(1, 0);
        int2 param_3 = size;
        int2 param_4 = base + int2(0, 1);
        int2 param_5 = size;
        int2 param_6 = base + int2(1);
        int2 param_7 = size;
        float scene = fast::max(fast::max(previousDepth(param, param_1, uSceneDepth, uSceneDepthSmplr, pc), previousDepth(param_2, param_3, uSceneDepth, uSceneDepthSmplr, pc)), fast::max(previousDepth(param_4, param_5, uSceneDepth, uSceneDepthSmplr, pc), previousDepth(param_6, param_7, uSceneDepth, uSceneDepthSmplr, pc)));
        if (((ndc.z * 0.5) + 0.5) > scene)
        {
            discard_fragment();
        }
    }
    float4 _212 = c;
    float3 _214 = _212.xyz * pc.uScalars.xyz;
    c.x = _214.x;
    c.y = _214.y;
    c.z = _214.z;
    float3 fogDelta = in.vRenderPos - U.uCamPosBright_.xyz;
    float sph = length(fogDelta);
    float cyl = fast::max(length(fogDelta.xz), abs(fogDelta.y));
    float param_8 = sph;
    float param_9 = U.uFogEnv_.x;
    float param_10 = U.uFogEnv_.y;
    float param_11 = cyl;
    float param_12 = U.uFogEnv_.z;
    float param_13 = U.uFogEnv_.w;
    float fogValue = fast::max(linearFog(param_8, param_9, param_10), linearFog(param_11, param_12, param_13));
    float4 _262 = c;
    float3 _273 = mix(_262.xyz, U.uFogColor_.xyz, float3(fogValue * U.uFogColor_.w));
    c.x = _273.x;
    c.y = _273.y;
    c.z = _273.z;
    out.FragColor = float4(c.xyz * c.w, c.w);
    return out;
}

