$ISCC      = "$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe"
$ISS       = "$PSScriptRoot\create_installer.iss"
$Downloads = "$env:USERPROFILE\Downloads"
& $ISCC $ISS /O"$Downloads"
Write-Host "Installer created: $Downloads\ObeyCraftLauncherInstaller.exe"
