#!/usr/bin/env python3
"""Generate src/client/renderer/entity/GeneratedBabyTextures.{hpp,cpp}: which
sheet a baby draws with under the 26.x remodel look.

MC 26.1-26.2 gave every remodeled baby its own texture, `<adult>_baby.png`
beside the adult's (CowRenderer's variant.babyTexture(), CatRenderer,
WolfRenderer, HorseRenderer's variant.baby, SheepWoolLayer's
BABY_SHEEP_WOOL_LOCATION, the collar layers, ...). The rule is mechanical, so
the table is derived from the assets on disk rather than transcribed: every
`assets/textures/entity/**/<name>_baby.png` maps the adult `<name>.png` in
the same folder. Where this engine still carries a sheet under its pre-26
name (cat/tabby.png for cat/cat_tabby.png, turtle/big_sea_turtle.png, ...),
RENAMED says which baby it belongs to; the remodeled adult rabbit's 64x64
sheets ride the same rows as an "adult under the new look" column.

    python3 tools/gen_baby_textures.py
"""

import os
import re

ROOT = "assets/textures/entity"
OUT_HPP = "src/client/renderer/entity/GeneratedBabyTextures.hpp"
OUT_CPP = "src/client/renderer/entity/GeneratedBabyTextures.cpp"

# engine adult tail -> (baby tail, adult-under-new-look tail or "")
RENAMED = {
    # 1.21.x cat sheets are bare names here; 26.x prefixed them.
    **{f"cat/{v}.png": (f"cat/cat_{v}_baby.png", "") for v in (
        "tabby", "black", "red", "siamese", "british_shorthair", "calico",
        "persian", "ragdoll", "white", "jellie", "all_black")},
    # 1.21.5 farm variants: <variant>_<mob> here, <mob>_<variant> in 26.x.
    **{f"{m}/{v}_{m}.png": (f"{m}/{m}_{v}_baby.png", "")
       for m in ("cow", "pig", "chicken") for v in ("temperate", "warm", "cold")},
    "cow/red_mooshroom.png":    ("cow/mooshroom_red_baby.png", ""),
    "cow/brown_mooshroom.png":  ("cow/mooshroom_brown_baby.png", ""),
    "turtle/big_sea_turtle.png": ("turtle/turtle_baby.png", ""),
    "fox/snow_fox.png":         ("fox/fox_snow_baby.png", ""),
    "fox/snow_fox_sleep.png":   ("fox/fox_snow_sleep_baby.png", ""),
    # These two adults live at the entity root in this asset set.
    "dolphin.png":              ("dolphin/dolphin_baby.png", ""),
    "armadillo.png":            ("armadillo/armadillo_baby.png", ""),
    **{f"llama/{v}.png": (f"llama/llama_{v}_baby.png", "") for v in (
        "creamy", "white", "brown", "gray")},
    # SnifferRenderer: the snifflet has its own sheet, not a `_baby` one.
    "sniffer/sniffer.png":      ("sniffer/snifflet.png", ""),
    # The remodeled rabbit: new adult sheets AND baby sheets.
    **{f"rabbit/{v}.png": (f"rabbit/rabbit_{v}_baby.png", f"rabbit/rabbit_{v}.png") for v in (
        "brown", "white", "black", "white_splotched", "gold", "salt", "toast",
        "caerbannog")},
}


def main():
    rows = {}
    for r, _, fs in os.walk(ROOT):
        for f in sorted(fs):
            if not f.endswith("_baby.png"):
                continue
            d = os.path.relpath(r, ROOT).replace(os.sep, "/")
            baby = f"{d}/{f}" if d != "." else f
            adult = f"{d}/{f[:-9]}.png" if d != "." else f"{f[:-9]}.png"
            if os.path.exists(os.path.join(ROOT, adult)):
                rows[adult] = (baby, "")
    for adult, (baby, adult_new) in RENAMED.items():
        if not os.path.exists(os.path.join(ROOT, adult)):
            print(f"  WARNING: RENAMED adult {adult} is not in {ROOT}")
            continue
        if not os.path.exists(os.path.join(ROOT, baby)):
            print(f"  WARNING: baby sheet {baby} is not in {ROOT}")
            continue
        rows[adult] = (baby, adult_new)

    hpp = """// GENERATED by tools/gen_baby_textures.py — do not edit by hand.
//
// The 26.x remodel's sheets: for an adult texture path this renderer picks,
// the baby's `_baby` sheet (and, for the remodeled rabbit, the new adult
// sheet). See the generator's docstring for the rule.
#pragma once

#include <string>
#include <string_view>

namespace Render {

    // `path` is any texture path ending in one of the table's adult tails
    // ("assets/textures/entity/cow/temperate_cow.png"). Returns the baby's
    // sheet when `baby`, the remodeled adult's when not and one exists, and
    // the path unchanged otherwise. Only the New baby look consults this.
    std::string RemodelTexturePath(std::string_view path, bool baby);

    inline constexpr int kBabyTextureCount = %d;

} // namespace Render
""" % len(rows)

    lines = [
        "// GENERATED by tools/gen_baby_textures.py — do not edit by hand.",
        '#include "client/renderer/entity/GeneratedBabyTextures.hpp"',
        "",
        "namespace Render {",
        "",
        "    namespace {",
        "        struct Row { std::string_view adult, baby, adultNew; };",
        "        constexpr Row kRows[kBabyTextureCount] = {",
    ]
    for adult in sorted(rows):
        baby, adult_new = rows[adult]
        lines.append(f'            {{ "{adult}", "{baby}", "{adult_new}" }},')
    lines += [
        "        };",
        "    } // namespace",
        "",
        "    std::string RemodelTexturePath(std::string_view path, bool baby) {",
        "        for (const Row& r : kRows) {",
        "            // Whole-name suffix match: the tail must start a path segment,",
        "            // so cat/black.png never claims cat/all_black.png.",
        "            if (path.size() < r.adult.size()) continue;",
        "            const size_t at = path.size() - r.adult.size();",
        "            if (path.substr(at) != r.adult) continue;",
        "            if (at > 0 && path[at - 1] != '/') continue;",
        "            const std::string_view tail = baby ? r.baby : r.adultNew;",
        "            if (tail.empty()) break;",
        "            return std::string(path.substr(0, at)) + std::string(tail);",
        "        }",
        "        return std::string(path);",
        "    }",
        "",
        "} // namespace Render",
        "",
    ]
    open(OUT_HPP, "w", encoding="utf-8").write(hpp)
    open(OUT_CPP, "w", encoding="utf-8").write("\n".join(lines))
    print(f"{OUT_HPP}: {len(rows)} baby sheets")


if __name__ == "__main__":
    main()
