#!/usr/bin/env python3
"""Bake the block/biome tags the spawn rules consult into C++.

Reads data/minecraft/tags/block/*.json and data/minecraft/tags/worldgen/biome/
*.json (the real vanilla files this repo ships) and emits
src/common/world/spawn/GeneratedSpawnTags.{hpp,cpp}.

Same rationale as gen_mob_spawns.py: the SpawnPlacements predicates consult
these sets several times per spawn attempt, and baking keeps the vanilla data
files usable verbatim. Tag members naming a block this engine does not register
are DROPPED with a note; `#minecraft:` includes are resolved recursively.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BLOCK_TAG_DIR = os.path.join(ROOT, "data", "minecraft", "tags", "block")
BIOME_TAG_DIR = os.path.join(ROOT, "data", "minecraft", "tags", "worldgen", "biome")
OUT_DIR = os.path.join(ROOT, "src", "common", "world", "spawn")

# The tags the spawn system actually reads. Block tags become BlockID sets,
# biome tags become biome-slug sets. Adding a tag here is the whole change.
BLOCK_TAGS = [
    "animals_spawnable_on",
    "armadillo_spawnable_on",
    "axolotls_spawnable_on",
    "bats_spawnable_on",
    "camels_spawnable_on",
    "foxes_spawnable_on",
    "frogs_spawnable_on",
    "goats_spawnable_on",
    "mooshrooms_spawnable_on",
    "parrots_spawnable_on",
    "polar_bears_spawnable_on_alternate",
    "rabbits_spawnable_on",
    "wolves_spawnable_on",
    "prevent_mob_spawning_inside",
    "sand",   # TurtleEggBlock.onSand — the turtle spawn rule
    "enderman_holdable",   # EndermanTakeBlockGoal's pickup set
]

BIOME_TAGS = [
    "allows_surface_slime_spawns",
    "allows_tropical_fish_spawns_at_any_height",
    "more_frequent_drowned_spawns",
    "polar_bears_spawn_on_alternate_blocks",
    "reduce_water_ambient_spawns",
]


def load_block_enum():
    """slug -> (enumerator, enum value), from BlockDefs.inc (single source of
    truth). The value is Air=0 then .inc order, which is exactly how Blocks.hpp
    builds the enum — needed so the emitted arrays are sorted by VALUE and
    binary_search's ordering matches the comparison it performs."""
    inc = os.path.join(ROOT, "src", "common", "world", "block", "BlockDefs.inc")
    known = {"air": ("Air", 0)}
    value = 1
    for m in re.finditer(r'BLOCK_DEF\((\w+),\s*"([a-z_0-9]+)"', open(inc, encoding="utf-8").read()):
        known[m.group(2)] = (m.group(1), value)
        value += 1
    return known


def resolve_tag(tag_dir, name, seen=None):
    """Flatten one tag file to a sorted list of bare slugs, following includes."""
    if seen is None:
        seen = set()
    if name in seen:
        return []
    seen.add(name)

    path = os.path.join(tag_dir, name + ".json")
    if not os.path.isfile(path):
        print(f"  warning: tag file missing: {path}", file=sys.stderr)
        return []

    out = []
    for value in json.load(open(path, encoding="utf-8"))["values"]:
        if isinstance(value, dict):  # {"id": ..., "required": false}
            value = value["id"]
        if value.startswith("#"):
            out.extend(resolve_tag(tag_dir, value.split(":", 1)[1], seen))
        else:
            out.append(value.split(":", 1)[1])
    return sorted(set(out))


def camel(slug):
    return "".join(p.capitalize() for p in slug.split("_"))


def main():
    for d in (BLOCK_TAG_DIR, BIOME_TAG_DIR):
        if not os.path.isdir(d):
            print(f"error: {d} not found", file=sys.stderr)
            return 1

    block_enum = load_block_enum()

    block_sets = {}   # tag -> (kept enumerators sorted by enum value, dropped slugs)
    for tag in BLOCK_TAGS:
        slugs = resolve_tag(BLOCK_TAG_DIR, tag)
        kept, dropped = [], []
        for slug in slugs:
            if slug in block_enum:
                kept.append(block_enum[slug])
            else:
                dropped.append(slug)
        kept = [name for name, _ in sorted(kept, key=lambda kv: kv[1])]
        block_sets[tag] = (kept, dropped)
        if dropped:
            print(f"  note: {tag}: dropped unregistered blocks: {', '.join(dropped)}")

    biome_sets = {tag: resolve_tag(BIOME_TAG_DIR, tag) for tag in BIOME_TAGS}

    hpp = os.path.join(OUT_DIR, "GeneratedSpawnTags.hpp")
    cpp = os.path.join(OUT_DIR, "GeneratedSpawnTags.cpp")

    with open(hpp, "w", encoding="utf-8") as f:
        f.write("""// File: src/common/world/spawn/GeneratedSpawnTags.hpp
// AUTO-GENERATED by tools/gen_spawn_tags.py — DO NOT EDIT BY HAND.
//
// The block and biome tags the spawn rules consult, baked from
// data/minecraft/tags/. Regenerate after any Minecraft version bump.
#pragma once

#include "common/world/block/Blocks.hpp"

#include <string_view>

namespace Game::SpawnTags {

""")
        for tag in BLOCK_TAGS:
            f.write(f"    // BlockTags.{tag.upper()}\n")
            f.write(f"    bool {camel(tag)}(BlockID block);\n")
        f.write("\n")
        for tag in BIOME_TAGS:
            f.write(f"    // BiomeTags.{tag.upper()}\n")
            f.write(f"    bool {camel(tag)}(std::string_view biomeSlug);\n")
        f.write("\n} // namespace Game::SpawnTags\n")

    with open(cpp, "w", encoding="utf-8") as f:
        f.write("""// File: src/common/world/spawn/GeneratedSpawnTags.cpp
// AUTO-GENERATED by tools/gen_spawn_tags.py — DO NOT EDIT BY HAND.
#include "common/world/spawn/GeneratedSpawnTags.hpp"

#include <algorithm>
#include <iterator>

namespace Game::SpawnTags {

    namespace {
        bool Contains(const BlockID* first, const BlockID* last, BlockID block) {
            return std::binary_search(first, last, block);
        }
        bool Contains(const std::string_view* first, const std::string_view* last,
                      std::string_view slug) {
            return std::binary_search(first, last, slug);
        }
    } // namespace

""")
        for tag in BLOCK_TAGS:
            kept, dropped = block_sets[tag]
            name = camel(tag)
            if dropped:
                f.write(f"    // Not registered in BlockDefs.inc, dropped: {', '.join(dropped)}\n")
            if not kept:
                f.write(f"    bool {name}(BlockID) {{ return false; }}\n\n")
                continue
            # Emitted sorted by enum VALUE (BlockDefs.inc order), so the
            # binary_search ordering matches the comparison it performs.
            f.write(f"    static const BlockID k_{name}[] = {{\n")
            for e in kept:
                f.write(f"        BlockID::{e},\n")
            f.write("    };\n")
            f.write(f"    bool {name}(BlockID block) {{\n")
            f.write(f"        return Contains(std::begin(k_{name}), std::end(k_{name}), block);\n")
            f.write(f"    }}\n\n")
        for tag in BIOME_TAGS:
            name = camel(tag)
            slugs = biome_sets[tag]
            if not slugs:
                f.write(f"    bool {name}(std::string_view) {{ return false; }}\n\n")
                continue
            f.write(f"    static const std::string_view k_{name}[] = {{\n")
            for s in slugs:
                f.write(f'        "{s}",\n')
            f.write("    };\n")
            f.write(f"    bool {name}(std::string_view biomeSlug) {{\n")
            f.write(f"        return Contains(std::begin(k_{name}), std::end(k_{name}), biomeSlug);\n")
            f.write(f"    }}\n\n")
        f.write("} // namespace Game::SpawnTags\n")

    print(f"wrote {hpp}")
    print(f"wrote {cpp}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
