#!/usr/bin/env python3
"""Generate the Metal backend's shaders (shaders/metal/*.metal) from the
Vulkan SPIR-V (shaders/*_vk.{vert,frag}.spv) with spirv-cross.

One source of truth: the _vk GLSL compiles to SPIR-V (CMake, glslc), and this
turns each .spv into MSL, so the Metal backend draws with exactly the shaders
Vulkan does. The .metal files are committed like the .spv files are, so a
machine without spirv-cross still builds and runs Metal; the game compiles
them at startup (MTLDevice newLibraryWithSource — no offline Metal toolchain
needed, on the build machine or a player's).

Resource bindings. Vulkan addresses resources by (descriptor set, binding);
Metal by an index per resource kind (buffer / texture / sampler). Before
spirv-cross runs, every DescriptorSet/Binding decoration is rewritten to the
fixed Metal index below (set 0 binding N), and spirv-cross is told to use
the bindings as the MSL indices (--msl-decoration-binding). The table is the
contract with MetalBackend (src/client/renderer/backend/metal/MetalBindings.hpp
mirrors it):

    push constants              buffer(0)   (spirv-cross puts them first)
    set 1 binding 0  Common     buffer(1)
    set 1 binding 1  Bones      buffer(2)
    set 3 binding 0  user UBO   buffer(3)   (terrain SectionOrigins)
    set 6 binding 3  OitParams  buffer(4)
    set 0 binding 0  slot 0     texture(0) + sampler(0)
    set 2 binding 0  slot 1     texture(1) + sampler(1)
    set 4 binding 0  slot 2     texture(2)  (texel buffer: texture_buffer)
    set 5 binding 0  slot 3     texture(3) + sampler(3)
    set 6 binding 0..2  OIT     texture(4..6) + sampler(4..6)
    set 7 binding 0  slot 4     texture(7) + sampler(7)  (the sprite array)
    set 7 binding 1  slot 5     texture(8) + sampler(8)  (its overflow array)
    vertex streams              buffer(30) per-vertex, buffer(29) per-instance

"""

import argparse
import glob
import hashlib
import os
import shutil
import struct
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (set, binding) -> Metal index of that resource's kind. See the docstring.
BINDINGS = {
    (0, 0): 0,
    (1, 0): 1,
    (1, 1): 2,
    (2, 0): 1,
    (3, 0): 3,
    (4, 0): 2,
    (5, 0): 3,
    (6, 0): 4,
    (6, 1): 5,
    (6, 2): 6,
    (6, 3): 4,
    (7, 0): 7,
    (7, 1): 8,
}

OP_DECORATE = 71
DECORATION_BINDING = 33
DECORATION_DESCRIPTOR_SET = 34

HEADER = "// Generated by tools/gen_metal_shaders.py from shaders/{src} — do not edit.\n// spirv-sha256: {digest}\n"

# Bumped whenever the translation itself changes (options, binding table,
# entry naming): it is part of every output's digest, so a bump regenerates
# every file even when no SPIR-V changed.
GENERATOR_VERSION = b"gen_metal_shaders 4: entry <name>_vk_<stage>, decoration bindings, native texel buffers"


def entry_point(spv_name):
    """The MSL function name of a shader: unique per file, so every shader
    links into one shaders.metallib (CMake) — terrain_vk.vert.spv ->
    terrain_vk_vert. MetalBackend::LoadFunction derives the same name."""
    return spv_name[:-len(".spv")].replace(".", "_")


def find_spirv_cross(explicit):
    if explicit:
        return explicit
    candidates = []
    sdk = os.environ.get("VULKAN_SDK")
    if sdk:
        candidates.append(os.path.join(sdk, "bin", "spirv-cross"))
    candidates += sorted(glob.glob(os.path.expanduser("~/VulkanSDK/*/macOS/bin/spirv-cross")), reverse=True)
    found = shutil.which("spirv-cross")
    if found:
        candidates.append(found)
    for c in candidates:
        if os.path.isfile(c) and os.access(c, os.X_OK):
            return c
    return None


def remap_bindings(spirv: bytes, name: str) -> bytes:
    if len(spirv) % 4 != 0 or len(spirv) < 20:
        raise ValueError(f"{name}: not a SPIR-V module")
    words = list(struct.unpack("<%dI" % (len(spirv) // 4), spirv))
    if words[0] != 0x07230203:
        raise ValueError(f"{name}: bad SPIR-V magic")
    set_at, binding_at = {}, {}
    i = 5
    while i < len(words):
        count, op = words[i] >> 16, words[i] & 0xFFFF
        if count == 0:
            raise ValueError(f"{name}: malformed instruction at word {i}")
        if op == OP_DECORATE and count >= 4:
            target, decoration = words[i + 1], words[i + 2]
            if decoration == DECORATION_DESCRIPTOR_SET:
                set_at[target] = i + 3
            elif decoration == DECORATION_BINDING:
                binding_at[target] = i + 3
        i += count
    for target, set_word in set_at.items():
        if target not in binding_at:
            raise ValueError(f"{name}: resource %{target} has a set but no binding")
        key = (words[set_word], words[binding_at[target]])
        if key not in BINDINGS:
            raise ValueError(f"{name}: (set {key[0]}, binding {key[1]}) has no Metal index — "
                             f"add it to BINDINGS here and to MetalBindings.hpp")
        words[set_word] = 0
        words[binding_at[target]] = BINDINGS[key]
    return struct.pack("<%dI" % len(words), *words)


def translate(spirv_cross, spirv: bytes, name: str, scratch: str) -> str:
    path = os.path.join(scratch, name)
    with open(path, "wb") as f:
        f.write(remap_bindings(spirv, name))
    stage = "vert" if ".vert." in name else "frag"
    args = [spirv_cross, "--msl", "--msl-version", "20400",
            "--msl-decoration-binding", "--msl-texture-buffer-native",
            "--rename-entry-point", "main", entry_point(name), stage, path]
    result = subprocess.run(args, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"{name}: spirv-cross failed:\n{result.stderr}")
    msl = result.stdout
    if stage == "vert" and name.startswith("terrain"):
        # The section-origins table is a UBO in GLSL, so spirv-cross binds
        # it in the `constant` address space — meant for data read
        # uniformly across a draw. The terrain vertex shader indexes it by
        # the vertex's own slot (divergent), which Apple's guidance sends
        # to `device`; `const device` keeps the read-only intent. Nothing
        # changes on the CPU side: the same MTLBuffer is bound either way.
        msl = msl.replace("constant SectionOrigins&", "const device SectionOrigins&")
    return msl


def has_source(spv_name):
    """Only SPIR-V the build still makes: <name>_vk.<stage>.spv with its GLSL
    in shaders/, an Improved Transparency variant <name>_oit_<stage>_vk.frag
    .spv of one (CMake's VK_OIT_SHADERS), or a half-precision terrain variant
    <name>_f16_vk.frag.spv (VK_F16_SHADERS). A leftover .spv whose source is
    gone is not translated."""
    glsl = spv_name[:-len(".spv")]
    if os.path.isfile(os.path.join(ROOT, "shaders", glsl)):
        return True
    for stage in ("db", "tr", "ac"):
        marker = f"_oit_{stage}_vk.frag"
        if glsl.endswith(marker):
            return os.path.isfile(os.path.join(ROOT, "shaders", glsl[:-len(marker)] + "_vk.frag"))
    # The half-precision terrain variants (CMake's VK_F16_SHADERS, TERRAIN_F16):
    # <name>_f16_vk.frag, terrain_f16_vk.vert, and the translucent shader's
    # Improved Transparency twins <name>_oit_<stage>_f16_vk.frag.
    for stage in ("db", "tr", "ac"):   # before the plain _f16 test: these end with it too
        marker = f"_oit_{stage}_f16_vk.frag"
        if glsl.endswith(marker):
            return os.path.isfile(os.path.join(ROOT, "shaders", glsl[:-len(marker)] + "_vk.frag"))
    for marker, src in (("_f16_vk.frag", "_vk.frag"), ("_f16_vk.vert", "_vk.vert")):
        if glsl.endswith(marker):
            return os.path.isfile(os.path.join(ROOT, "shaders", glsl[:-len(marker)] + src))
    return False


def recorded_digest(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            f.readline()
            line = f.readline()
        if line.startswith("// spirv-sha256: "):
            return line[len("// spirv-sha256: "):].strip()
    except OSError:
        pass
    return None


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--spirv-cross", help="spirv-cross executable (default: $VULKAN_SDK, ~/VulkanSDK, PATH)")
    ap.add_argument("--spv-dir", action="append", help="directory of *_vk.*.spv (repeatable; later wins)")
    ap.add_argument("--out", default=os.path.join(ROOT, "shaders", "metal"), help="output directory")
    ap.add_argument("--check", action="store_true", help="report stale outputs, write nothing")
    args = ap.parse_args()

    spv_dirs = args.spv_dir or [os.path.join(ROOT, "shaders")]
    inputs = {}
    for d in spv_dirs:
        for p in glob.glob(os.path.join(d, "*_vk.vert.spv")) + glob.glob(os.path.join(d, "*_vk.frag.spv")):
            if has_source(os.path.basename(p)):
                inputs[os.path.basename(p)] = p
    if not inputs:
        print("gen_metal_shaders: no *_vk.*.spv found in " + ", ".join(spv_dirs), file=sys.stderr)
        return 1

    work = []
    for base in sorted(inputs):
        with open(inputs[base], "rb") as f:
            spirv = f.read()
        digest = hashlib.sha256(GENERATOR_VERSION + spirv).hexdigest()
        out = os.path.join(args.out, base[:-len(".spv")] + ".metal")
        if recorded_digest(out) != digest:
            work.append((base, spirv, digest, out))

    if args.check:
        for base, _, _, _ in work:
            print(f"stale: {base}")
        return 1 if work else 0
    if not work:
        return 0

    spirv_cross = find_spirv_cross(args.spirv_cross)
    if not spirv_cross:
        print(f"gen_metal_shaders: {len(work)} shader(s) out of date but spirv-cross was not found "
              f"(install the Vulkan SDK) — keeping the committed .metal files", file=sys.stderr)
        return 0

    os.makedirs(args.out, exist_ok=True)
    scratch = os.path.join(args.out, ".gen")
    os.makedirs(scratch, exist_ok=True)
    failed = 0
    try:
        for base, spirv, digest, out in work:
            try:
                msl = translate(spirv_cross, spirv, base, scratch)
            except (ValueError, RuntimeError) as e:
                print(f"gen_metal_shaders: {e}", file=sys.stderr)
                failed += 1
                continue
            with open(out, "w", encoding="utf-8") as f:
                f.write(HEADER.format(src=base, digest=digest))
                f.write(msl)
            print(f"gen_metal_shaders: {base} -> {os.path.relpath(out, ROOT)}")
    finally:
        shutil.rmtree(scratch, ignore_errors=True)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
