#!/usr/bin/env python3
"""Bake MC's per-biome mob spawn weights into C++.

Reads data/minecraft/worldgen/biome/*.json (the real vanilla files this repo
already ships and already resolves at runtime via MC_DATA_ROOT) and emits
src/common/world/spawn/GeneratedMobSpawns.{hpp,cpp}.

Why bake rather than parse at runtime: the spawner consults this table for
every spawn attempt in every eligible chunk, several times a second. Parsing is
not the cost — the cost is that a runtime parse makes the table a startup
failure mode, and this project already established the "generate to C++" pattern
for recipes (tools/gen_recipes.py) and block shapes (tools/gen_block_shapes.py).

Entries naming a mob this port does not implement are DROPPED with a note, the
same way gen_recipes.py drops recipes for unknown items. That keeps the biome
files usable verbatim as MC ships them: today eight of roughly forty mob types
resolve, and adding a ninth needs no change here.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BIOME_DIR = os.path.join(ROOT, "data", "minecraft", "worldgen", "biome")
OUT_DIR = os.path.join(ROOT, "src", "common", "world", "spawn")

# Mob slug -> Game::EntityTypeId enumerator, read from the GENERATED entity
# table so this generator never falls behind it. It used to hard-code the eight
# mobs that existed at the time, which quietly dropped every spawn row for
# everything added since.
def load_known_mobs():
    hpp = os.path.join(ROOT, "src", "common", "entity", "GeneratedEntityTypes.hpp")
    known = {}
    for slug in re.findall(r'//\s*"([a-z_]+)"', open(hpp, encoding="utf-8").read()):
        known[slug] = "".join(p.capitalize() for p in slug.split("_"))
    return known


KNOWN_MOBS = load_known_mobs()

# MC MobCategory keys as they appear in the biome JSON.
CATEGORIES = ["monster", "creature", "ambient", "water_creature", "water_ambient",
              "underground_water_creature", "axolotls", "misc"]
CATEGORY_ENUM = {
    "monster": "Monster",
    "creature": "Creature",
    "ambient": "Ambient",
    "axolotls": "Axolotls",
    "underground_water_creature": "UndergroundWaterCreature",
    "water_creature": "WaterCreature",
    "water_ambient": "WaterAmbient",
    "misc": "Misc",
}


def main():
    if not os.path.isdir(BIOME_DIR):
        print(f"error: {BIOME_DIR} not found", file=sys.stderr)
        return 1

    biomes = []
    skipped = set()

    for filename in sorted(os.listdir(BIOME_DIR)):
        if not filename.endswith(".json"):
            continue
        slug = filename[:-5]

        with open(os.path.join(BIOME_DIR, filename), encoding="utf-8") as f:
            data = json.load(f)

        spawners = data.get("spawners", {})
        entries = []

        for category in CATEGORIES:
            for entry in spawners.get(category, []):
                mob = entry.get("type", "").removeprefix("minecraft:")
                if mob not in KNOWN_MOBS:
                    skipped.add(mob)
                    continue
                entries.append((
                    CATEGORY_ENUM[category],
                    KNOWN_MOBS[mob],
                    int(entry.get("weight", 0)),
                    int(entry.get("minCount", 1)),
                    int(entry.get("maxCount", 1)),
                ))

        if entries:
            biomes.append((slug, entries))

    os.makedirs(OUT_DIR, exist_ok=True)

    hpp = os.path.join(OUT_DIR, "GeneratedMobSpawns.hpp")
    cpp = os.path.join(OUT_DIR, "GeneratedMobSpawns.cpp")

    with open(hpp, "w", encoding="utf-8") as f:
        f.write("""// File: src/common/world/spawn/GeneratedMobSpawns.hpp
// AUTO-GENERATED by tools/gen_mob_spawns.py — DO NOT EDIT BY HAND.
//
// Per-biome spawn weights, from data/minecraft/worldgen/biome/*.json.
// Regenerate after any Minecraft version bump; see CLAUDE.md.
#pragma once

#include "common/entity/EntityType.hpp"
#include "common/entity/MobCategory.hpp"

#include <cstdint>
#include <string_view>

namespace Game {

    struct MobSpawnEntry {
        MobCategory  category;
        EntityTypeId type;
        int          weight;
        int          minCount;
        int          maxCount;
    };

    struct BiomeSpawnList {
        std::string_view     biome;
        const MobSpawnEntry* entries;
        int                  count;
    };

    // Sorted by biome slug so lookup can binary-search.
    extern const BiomeSpawnList kBiomeSpawnLists[];
    extern const int            kBiomeSpawnListCount;

    // Null when the biome has no spawns for any implemented mob.
    const BiomeSpawnList* FindBiomeSpawnList(std::string_view biomeSlug);

} // namespace Game
""")

    with open(cpp, "w", encoding="utf-8") as f:
        f.write("""// File: src/common/world/spawn/GeneratedMobSpawns.cpp
// AUTO-GENERATED by tools/gen_mob_spawns.py — DO NOT EDIT BY HAND.
#include "common/world/spawn/GeneratedMobSpawns.hpp"

#include <algorithm>

namespace Game {

""")
        for slug, entries in biomes:
            ident = slug.replace("-", "_")
            f.write(f"    static const MobSpawnEntry k_{ident}[] = {{\n")
            for cat, mob, weight, mn, mx in entries:
                f.write(f"        {{ MobCategory::{cat}, EntityTypeId::{mob}, "
                        f"{weight}, {mn}, {mx} }},\n")
            f.write("    };\n\n")

        f.write("    const BiomeSpawnList kBiomeSpawnLists[] = {\n")
        for slug, entries in biomes:
            ident = slug.replace("-", "_")
            f.write(f'        {{ "{slug}", k_{ident}, {len(entries)} }},\n')
        f.write("    };\n\n")
        f.write(f"    const int kBiomeSpawnListCount = {len(biomes)};\n\n")

        f.write("""    const BiomeSpawnList* FindBiomeSpawnList(std::string_view biomeSlug) {
        const auto* begin = kBiomeSpawnLists;
        const auto* end = kBiomeSpawnLists + kBiomeSpawnListCount;
        const auto* it = std::lower_bound(begin, end, biomeSlug,
            [](const BiomeSpawnList& row, std::string_view key) { return row.biome < key; });
        if (it == end || it->biome != biomeSlug) return nullptr;
        return it;
    }

} // namespace Game
""")

    total = sum(len(e) for _, e in biomes)
    print(f"Wrote {len(biomes)} biomes, {total} spawn entries")
    if skipped:
        print(f"Skipped {len(skipped)} unimplemented mob types: "
              f"{', '.join(sorted(skipped))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
