#!/usr/bin/env python3
"""Generate the biome CLIMATE table from the vendored biome definitions.

Reads data/<namespace>/worldgen/biome/*.json and writes
src/common/world/biome/GeneratedBiomeClimate.inc, which BiomeRegistry expands
alongside GeneratedBiomeTable.inc (tools/gen_biomes.py, the colour table).

The two fields of MC's Biome.ClimateSettings the colour table does not carry:

  has_precipitation     -> ClimateSettings.hasPrecipitation
                           (Biome.getPrecipitationAt: NONE when false)
  temperature_modifier  -> ClimateSettings.temperatureModifier
                           ("none" | "frozen"; FROZEN warms patches of a frozen
                           ocean so its ice has holes)

Keyed by slug, not by position: the colour table owns the biome ids (they
travel in ChunkDataS2C), and this one is joined onto it by name at startup, so
the two generators can never disagree about ordering. The slug is the bare
name for minecraft and "<namespace>:<name>" otherwise, as in gen_biomes.py.

Usage:  python3 tools/gen_biome_climate.py
"""

import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(REPO, "data")
OUT = os.path.join(REPO, "src", "common", "world", "biome", "GeneratedBiomeClimate.inc")

MODIFIERS = {None: "None", "none": "None", "frozen": "Frozen"}


def biome_files():
    for ns in sorted(os.listdir(DATA)):
        d = os.path.join(DATA, ns, "worldgen", "biome")
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if not name.endswith(".json"):
                continue
            slug = name[:-5] if ns == "minecraft" else f"{ns}:{name[:-5]}"
            yield slug, os.path.join(d, name)


def main():
    rows = []
    for slug, path in biome_files():
        with open(path, encoding="utf-8") as f:
            d = json.load(f)
        # Both fields are mandatory in the Java codec (Biome.ClimateSettings
        # .CODEC: has_precipitation required, temperature_modifier optional
        # with NONE as the default).
        if "has_precipitation" not in d:
            sys.exit(f"{path}: has_precipitation missing")
        modifier = d.get("temperature_modifier")
        if modifier not in MODIFIERS:
            sys.exit(f"{path}: unknown temperature_modifier {modifier!r}")
        rows.append((slug, bool(d["has_precipitation"]), MODIFIERS[modifier]))

    if not rows:
        sys.exit(f"no biome data found under {DATA}")

    lines = [
        "// GENERATED BY tools/gen_biome_climate.py - DO NOT EDIT BY HAND.",
        "//",
        "// Source: data/<namespace>/worldgen/biome/*.json. Joined onto the colour",
        "// table (GeneratedBiomeTable.inc) by slug in BiomeRegistry, so ordering",
        "// here carries no meaning.",
        "//",
        "// BIOME_CLIMATE(slug, hasPrecipitation, temperatureModifier)",
        "",
    ]
    for slug, precip, modifier in rows:
        lines.append(f'BIOME_CLIMATE("{slug}", {"true" if precip else "false"}, {modifier})')
    lines.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {len(rows)} biomes to {os.path.relpath(OUT, REPO)}")


if __name__ == "__main__":
    main()
