#!/usr/bin/env python3
"""Generate the biome colour table from the vendored vanilla biome definitions.

Reads data/minecraft/worldgen/biome/*.json and writes
src/common/world/biome/GeneratedBiomeTable.inc, which BiomeRegistry expands.

Only the fields that affect block tinting are extracted:

  temperature / downfall   -> the colormap lookup (Biome.getGrassColorFromTexture)
  effects.grass_color      -> BiomeSpecialEffects.grassColorOverride
  effects.foliage_color    -> foliageColorOverride
  effects.dry_foliage_color-> dryFoliageColorOverride
  effects.water_color      -> waterColor (mandatory in vanilla)
  effects.grass_color_modifier -> NONE | DARK_FOREST | SWAMP

Everything else in those files (features, carvers, spawners, sounds) is
worldgen/ambience data the client never consults for colour.

APPEND-AWARE, like tools/gen_items.py: existing ids keep their positions and new
biomes are appended, because the id is what travels in the chunk packet. Always
inspect the diff and confirm nothing was reordered.

Usage:  python3 tools/gen_biomes.py
"""

import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "data", "minecraft", "worldgen", "biome")
OUT = os.path.join(REPO, "src", "common", "world", "biome", "GeneratedBiomeTable.inc")

MODIFIERS = {None: "None", "none": "None",
             "dark_forest": "DarkForest", "swamp": "Swamp"}


def hex_to_rgb(value):
    """'#78a7ff' -> 0x78A7FF. Vanilla writes these as STRING_RGB_COLOR."""
    if value is None:
        return None
    return int(value.lstrip("#"), 16)


def existing_order(path):
    """Slugs already in the generated file, in their current id order."""
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as f:
        return re.findall(r'BIOME_DEF\(\s*"([a-z0-9_]+)"', f.read())


def main():
    if not os.path.isdir(SRC):
        sys.exit(f"biome data not found at {SRC}")

    biomes = {}
    for name in sorted(os.listdir(SRC)):
        if not name.endswith(".json"):
            continue
        slug = name[:-5]
        with open(os.path.join(SRC, name), encoding="utf-8") as f:
            d = json.load(f)
        e = d.get("effects", {})
        biomes[slug] = {
            "temperature": float(d["temperature"]),
            "downfall": float(d["downfall"]),
            "water": hex_to_rgb(e.get("water_color")),
            "grass": hex_to_rgb(e.get("grass_color")),
            "foliage": hex_to_rgb(e.get("foliage_color")),
            "dry": hex_to_rgb(e.get("dry_foliage_color")),
            "modifier": MODIFIERS[e.get("grass_color_modifier")],
        }

    # Keep known slugs at their current ids, append anything new.
    order = [s for s in existing_order(OUT) if s in biomes]
    order += [s for s in sorted(biomes) if s not in order]

    # plains MUST be id 0. Every "no biome data" path in the engine — an
    # unloaded chunk, a blend sample past a border, an accessor that tracks no
    # biomes — returns a literal 0, so id 0 is the de-facto fallback whether or
    # not anything says so. Sorted alphabetically that slot is BADLANDS, whose
    # hard-coded tan grass override (#90814D) then tints every one of those
    # cases olive. Pinning plains here makes "0 == fallback" true instead of
    # merely documented.
    if "plains" in order:
        order.remove("plains")
        order.insert(0, "plains")

    lines = [
        "// GENERATED BY tools/gen_biomes.py - DO NOT EDIT BY HAND.",
        "//",
        "// Source: data/minecraft/worldgen/biome/*.json (vanilla, vendored).",
        "// Regenerate after bumping the MC snapshot; the generator is",
        "// append-aware so existing ids stay put (they travel in ChunkDataS2C).",
        "//",
        "// BIOME_DEF(slug, temperature, downfall, waterColor,",
        "//           hasGrass, grassColor, hasFoliage, foliageColor,",
        "//           hasDry, dryColor, grassModifier)",
        "",
    ]

    def opt(v):
        return ("true", f"0x{v:06X}") if v is not None else ("false", "0x000000")

    for slug in order:
        b = biomes[slug]
        hg, g = opt(b["grass"])
        hf, fo = opt(b["foliage"])
        hd, dr = opt(b["dry"])
        water = f"0x{b['water']:06X}" if b["water"] is not None else "0x3F76E4"
        lines.append(
            f'BIOME_DEF("{slug}", {b["temperature"]:.4f}f, {b["downfall"]:.4f}f, {water}, '
            f'{hg}, {g}, {hf}, {fo}, {hd}, {dr}, GrassColorModifier::{b["modifier"]})'
        )

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"wrote {len(order)} biomes to {os.path.relpath(OUT, REPO)}")
    overrides = sum(1 for s in order
                    if any(biomes[s][k] is not None for k in ("grass", "foliage", "dry")))
    print(f"  {overrides} carry at least one colour override")


if __name__ == "__main__":
    main()
