#!/usr/bin/env python3
"""Generate src/common/data/components/GeneratedGameplayDefaults.inc.

MC 26.3 gives items their data-driven gameplay components through the
Item.Properties builders in Items.java:

    .compostable(ContextIntProviders.COMPOSTABLE_LOW)     -> COMPOSTABLE
    .cookingFuel(ContextIntProviders.COOKING_TIME_COAL)   -> COOKING_FUEL
    .brewingFuel(ContextIntProviders.BREWING_DEFAULT_USES) -> BREWING_FUEL
    .villagerFood(4)                                      -> VILLAGER_FOOD
    .loweredMobVisibility(EntityTypeIds.SKELETON, ...)    -> MOB_VISIBILITY

This walks Items.java's static initialiser one statement at a time, resolves
each statement's ItemIds/BlockItemIds constant to its item id(s) (expanding
the sixteen-colour collections), and writes one row per item that carries any
of them. The provider keys are written as their registry paths
("compostable/low", "cooking/time_coal") — ResolvableInt references, which
GameplayDataComponents resolves exactly as the vanilla ContextIntProviders
bootstrap defines them.

Usage: python3 tools/gen_gameplay_components.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MC = os.path.join(ROOT, "minecraft_code_26.3-pre-2", "decompiled_net", "minecraft")
OUT = os.path.join(ROOT, "src", "common", "data", "components", "GeneratedGameplayDefaults.inc")

COLORS = ["white", "orange", "magenta", "light_blue", "yellow", "lime", "pink", "gray",
          "light_gray", "cyan", "purple", "blue", "brown", "green", "red", "black"]


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def parse_ids(text, single_patterns):
    ids = {}
    for m in re.finditer(r'\b([A-Z0-9_]+)\s*=\s*(?:BlockItemId\.)?create\("([^"]+)"(?:,\s*"([^"]+)")?\)', text):
        name, a, b = m.group(1), m.group(2), m.group(3)
        ids[name] = [b or a]
    for m in re.finditer(r'\b([A-Z0-9_]+)\s*=\s*createSimpleColored\("([^"]+)"\)', text):
        ids[m.group(1)] = [c + "_" + m.group(2) for c in COLORS]
    return ids


def parse_provider_keys(text):
    keys = {}
    for m in re.finditer(r'\b([A-Z0-9_]+)\s*=\s*createKey\("([^"]+)"\)', text):
        keys[m.group(1)] = m.group(2)
    return keys


def statements(text):
    start = text.index("static {")
    body = text[start:]
    depth = 0
    cur = []
    for ch in body[len("static {"):]:
        if ch in "({":
            depth += 1
        elif ch in ")}":
            depth -= 1
            if depth < 0:
                break
        cur.append(ch)
        if ch == ";" and depth == 0:
            yield "".join(cur)
            cur = []


def main():
    items_java = read(os.path.join(MC, "world", "item", "Items.java"))
    item_ids = parse_ids(read(os.path.join(MC, "references", "ItemIds.java")), None)
    block_item_ids = parse_ids(read(os.path.join(MC, "references", "BlockItemIds.java")), None)
    int_keys = parse_provider_keys(read(os.path.join(
        MC, "world", "level", "storage", "loot", "providers", "number", "ints", "ContextIntProviders.java")))
    entity_ids = {}
    for m in re.finditer(r'\b([A-Z0-9_]+)\s*=\s*create\("([^"]+)"\)',
                         read(os.path.join(MC, "world", "entity", "EntityTypeIds.java"))):
        entity_ids[m.group(1)] = m.group(2)

    rows = {}
    order = []
    for st in statements(items_java):
        ref = re.search(r'\b(ItemIds|BlockItemIds)\.([A-Z0-9_]+)', st)
        if not ref:
            continue
        table = item_ids if ref.group(1) == "ItemIds" else block_item_ids
        names = table.get(ref.group(2))
        if not names:
            continue
        compost = re.search(r'\.compostable\(ContextIntProviders\.([A-Z0-9_]+)\)', st)
        fuel = re.search(r'\.cookingFuel\(ContextIntProviders\.([A-Z0-9_]+)\)', st)
        brewing = re.search(r'\.brewingFuel\(ContextIntProviders\.([A-Z0-9_]+)\)', st)
        food = re.search(r'\.villagerFood\((\d+)\)', st)
        vis = re.search(r'\.loweredMobVisibility\(([^)]*)\)', st)
        if not (compost or fuel or brewing or food or vis):
            continue
        visibility = ""
        if vis:
            visibility = ",".join("minecraft:" + entity_ids[e.split(".")[-1].strip()]
                                  for e in vis.group(1).split(","))
        for name in names:
            if name not in rows:
                order.append(name)
            rows[name] = (
                int_keys[compost.group(1)] if compost else "",
                int_keys[fuel.group(1)] if fuel else "",
                int_keys[brewing.group(1)] if brewing else "",
                int(food.group(1)) if food else 0,
                visibility,
            )

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// GENERATED by tools/gen_gameplay_components.py — do not edit by hand.\n")
        f.write("//\n")
        f.write("// MC 26.3 Items.java's data-driven gameplay components, one row per item:\n")
        f.write("// { item id, compostable layers key, cooking_fuel burn_time key,\n")
        f.write("//   brewing_fuel uses key, villager_food nutrition, mob_visibility types }.\n")
        f.write("// Keys are ContextIntProvider registry paths (\"\" = component absent).\n")
        for name in order:
            c, fu, br, fo, vi = rows[name]
            f.write('GAMEPLAY_ITEM("%s", "%s", "%s", "%s", %d, "%s")\n' % (name, c, fu, br, fo, vi))
    print("wrote %d rows to %s" % (len(order), os.path.relpath(OUT, ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
