// File: src/client/renderer/portal/HDRPipeline.hpp
//
// HDR rendering pipeline for the portal feature. Redirects the main
// scene + portal passes into an offscreen RGBA16F render target, then
// composites to the LDR backbuffer through an ACES Filmic tone-map
// fragment shader. Optionally takes a bloom-composite texture from
// BloomPipeline (Phase C) for additive HDR bloom.
//
// Why HDR: Portal renders in linear HDR and tone-maps to display.
// Without HDR, the bright portal rim crest cannot exceed pure white
// in framebuffer terms, so bloom can't pull energy from it. With HDR,
// the rim crest has supra-1.0 RGB values that drive the bloom pass.
//
// Constraint: the entire file is gated on ENABLE_PORTAL_GUN. When the
// feature is off, the global `g_hdrPipeline` doesn't exist and
// PlatformMain's BeginHDRPass/EndHDRPassAndComposite calls are stripped
// by the preprocessor — main scene goes directly to the backbuffer like
// pre-portal-feature code.
//
// Graceful fallback: if the backend does not support render targets
// (CreateRenderTarget returns INVALID_RENDER_TARGET — e.g. early
// Vulkan), Initialize() leaves the pipeline disabled and
// BeginHDRPass / EndHDRPassAndComposite become no-ops. Rendering then
// proceeds to the backbuffer in LDR like before.

#pragma once

#include "common/core/Features.hpp"
#if ENABLE_PORTAL_GUN

#include "../backend/RenderTypes.hpp"
#include <glm/glm.hpp>

namespace Render {

    class HDRPipeline {
    public:
        HDRPipeline();
        ~HDRPipeline();

        // Lazy init — needs g_renderBackend valid. Returns false (and
        // becomes a no-op for the session) if RT support is missing.
        bool Initialize();
        void Shutdown();

        // Returns true if HDR pipeline is active (RT created, shaders
        // loaded). Callers can branch on this for HDR-specific code
        // paths.
        bool IsActive() const { return m_active; }

        // Get the HDR color RT handle — used by BloomPipeline to read
        // the bright crest, and by the refraction sub-pass for sampling
        // the HDR scene.
        RenderTargetHandle GetHDRRenderTarget() const { return m_hdrRT; }
        TextureHandle      GetHDRColorTexture() const;

        // BeginHDRPass: resizes the RT to (w, h) if needed, binds it,
        // clears it. After this call, all rendering goes to the HDR RT.
        void BeginHDRPass(int w, int h);

        // EndHDRPassAndComposite: unbinds the RT, draws a fullscreen
        // triangle with the tone-map shader sampling the HDR RT, and
        // writes the tone-mapped LDR result to the backbuffer.
        //
        // If `bloomColor` is non-INVALID, it's additively combined
        // before tone mapping. Pass INVALID_TEXTURE to skip bloom.
        void EndHDRPassAndComposite(TextureHandle bloomColor = INVALID_TEXTURE);

        // Tunable: linear-space exposure scale applied before tone map.
        // Default 1.0. Lower for darker, higher for brighter mid-tones.
        void  SetExposure(float exposure) { m_exposure = exposure; }
        float GetExposure() const { return m_exposure; }

    private:
        bool                m_active        = false;
        RenderTargetHandle  m_hdrRT         = INVALID_RENDER_TARGET;
        ShaderHandle        m_toneMapShader = INVALID_SHADER;
        MeshHandle          m_fsTriangleMesh = INVALID_MESH;  // dummy mesh — vertices generated by shader
        BufferHandle        m_fsTriangleVB  = INVALID_BUFFER;
        TextureHandle       m_dummyBloom    = INVALID_TEXTURE; // 1x1 black for "no bloom"
        float               m_exposure      = 1.0f;
        int                 m_currentWidth  = 0;
        int                 m_currentHeight = 0;
    };

    extern HDRPipeline g_hdrPipeline;

} // namespace Render

#endif // ENABLE_PORTAL_GUN
