// GENERATED by tools/gen_sulfur_cube.py — do not edit by hand.
//
// MC 26.3's sulfur_cube_archetype registry: what a sulfur cube becomes when
// it swallows a block from each archetype's item tag. Attribute values are
// the FOLDED result of the JSON's modifiers on a fresh attribute (the
// engine's AttributeMap applies them as one add/multiply each); items are
// slugs resolved at runtime (see the generator's docstring).
#pragma once

#include <cstddef>
#include <cstdint>
#include <string_view>

namespace Game {

    enum class SulfurCubeArchetypeId : uint8_t {
        Regular,
        Bouncy,
        SlowBouncy,
        SlowFlat,
        FastFlat,
        Light,
        FastSliding,
        SlowSliding,
        HighResistance,
        Sticky,
        Explosive,
        Hot,
        Count
    };

    struct SulfurCubeArchetypeDef {
        std::string_view name;
        // SulfurCubeArchetypes.archetype(speed, bounce, friction, drag), folded:
        float knockbackResistance;           // add_value -speed (clamped 0..1 by the attribute)
        float explosionKnockbackResistance;  // same amount
        float bounciness;                    // add_value bounce
        float frictionModifier;              // add_multiplied_total → ×friction
        float airDragModifier;               // add_multiplied_total → ×drag
        bool  buoyant;
        // ExplosionData(power, causesFire, fuse), or explodes = false.
        bool  explodes;
        int   explosionPower;
        bool  explosionFire;
        int   explosionFuse;
        // ContactDamage(damageType, amount, attributeToSource), or contact = false.
        bool  contactDamage;
        float contactDamageAmount;
        bool  contactDamageToSource;
        std::string_view contactDamageType;
        // KnockbackModifiers(horizontalPower, verticalPower).
        float knockbackHorizontal;
        float knockbackVertical;
        // SoundSettings' push threshold (blocks/tick, squared compare) and
        // cooldown (seconds) — the sounds themselves have nowhere to play.
        float pushSoundThreshold;
        float pushSoundCooldown;
    };

    extern const SulfurCubeArchetypeDef kSulfurCubeArchetypes[static_cast<size_t>(SulfurCubeArchetypeId::Count)];

    // `#sulfur_cube_swallowable`, each item with the archetype whose tag
    // holds it, in registry order.
    struct SulfurCubeSwallowable {
        std::string_view      itemSlug;
        SulfurCubeArchetypeId archetype;
    };
    extern const SulfurCubeSwallowable kSulfurCubeSwallowable[];
    extern const size_t kSulfurCubeSwallowableCount;

    // `#sulfur_cube_food` — what a baby sulfur cube grows on.
    extern const std::string_view kSulfurCubeFood[];
    extern const size_t kSulfurCubeFoodCount;

} // namespace Game
